import type { ScheduleConfig, Turma } from "@/lib/types";

function alunos(nomes: string[]) {
  return nomes.map((nome, index) => ({ id: `a-${index}-${nome.length}-${index * 7 + 1}`, nome }));
}

export const SEED_CONFIG: ScheduleConfig = {
  nomeEscola: "Escola Municipal em Tempo Integral Dr. Eiraldo Carneiro de França",
  inep: "12004227",
  endereco: "Rua Ernane Moreira Braga, 108, Cohab",
  professorInformatica: "Franc D'nis",
  diasSemana: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
  horaInicio: "08:00",
  horaFim: "15:00",
  intervaloInicio: "12:00",
  intervaloFim: "13:00",
  duracaoSlotMinutos: 60,
  duracaoGrupoMinutos: 30,
  numeroComputadores: 7,
};

export const SEED_TURMAS: Turma[] = [
  {
    id: "t-1a",
    serie: "1º Ano",
    letra: "A",
    professorRegente: "Celina",
    alunos: alunos([
      "Anna Lís Bastos dos Santos",
      "Anthony Pietro Carvalho Braga",
      "Bruna Pontes Saboia",
      "Bruno Almeida Costa",
      "Clara Santos da Silva",
      "Dárvely Cardoso Dias",
      "Davi Costa de França",
      "Enzo Pinto",
      "Ester de Sousa",
      "Evangeline Conceição Souza do Nascimento",
      "Francisco Noah Dimas de Melo",
      "Heittor de Sousa Ferreira",
      "Henzo Miguel Fernandes da Silva",
      "Kaylla Majúh Souza",
      "Luiz Miguel Santa'Ana do Nascimento",
      "Lys Vitória da Silva Nascimento",
      "Maria Luara da Costa Silva",
      "Maria Luna da Costa Silva",
      "Antonia Emilly Muniz da Silva",
      "Dhonata Leão Rodrigues",
      "Gael Costa Soares",
      "Sadrack Uriel Mendonça Cardoso",
      "Alice Souza Linhares",
      "Maria Hanna de Freitas Lima",
      "Josué Dias dos Santos",
    ]),
  },
  {
    id: "t-1b",
    serie: "1º Ano",
    letra: "B",
    professorRegente: "Cirley",
    alunos: alunos([
      "Dheyslan Cardoso de Araújo",
      "Dhieyson Cardoso de Araújo",
      "Emanuela Oliveira de Lima",
      "João Vitor Silva Leitão",
      "Josué Damázio Carvalho",
      "Katriele Silva Sampaio",
      "Kelly Santos Flor",
      "Manuela dos Santos Souza",
      "Miguel de Souza Santos",
      "Natanael Santos Albuquerque",
      "Oseias Pereira Gomes",
      "Pedro Rodrigues do Nascimento Neto",
      "Priscila da Silva",
      "Rebeca Santos Leite",
      "Sophia Cardoso da Silva",
      "Théo Silva Cardoso",
      "Yara da Silva Martins",
      "Yasmin Pontes da Silva",
      "Heythor Lorenzo Tavares Mendonça",
      "Heloisa da Silva Aguiar",
      "Felícia Sousa Leão",
      "Thaemilly da Silva do Nascimento",
      "Naylan da Silva Souza Yawanawá",
      "Naylandson da Silva Souza Yawanawá",
      "Levi da Silva Albuquerque Kaxinawá",
      "Moisés Gomes do Carmo",
    ]),
  },
  {
    id: "t-2a",
    serie: "2º Ano",
    letra: "A",
    professorRegente: "França",
    alunos: alunos([
      "Ana Clara Farias de Lima",
      "Ana Lys da Silva Souza",
      "Analuh da Silva Sousa",
      "Daniela Rodrigues Silva",
      "Eloah Souza da Silva",
      "Emanuelly de Sousa Rocha",
      "Érick Silva Pereira",
      "Fabrício dos Santos Sousa",
      "Isabella Nascimento Matos",
      "Izaquiel Moura",
      "José Railan Parente do Nascimento",
      "Kaúan Moreno Gadelha Shanenawá",
      "Letícia Sousa",
      "Luiz Fernando Souza de Freitas",
      "Maria Luísa de Souza Reis",
      "Maria Valentina Pinheiro Muniz",
      "Miguel Gomes Azevedo",
      "Nycolas Castro Ferreira",
      "Ravih Araújo Moura",
      "Sarah Sophia de Amorim Gomes",
      "Jefferson Rian Simão da Silva",
      "Alyce Matos de Sousa",
      "Antonia Eliza Nogueira Silva",
    ]),
  },
  {
    id: "t-2b",
    serie: "2º Ano",
    letra: "B",
    professorRegente: "Anaiton",
    alunos: alunos([
      "Ana Paula França da Silva",
      "Andreison Silva Araújo",
      "Ezequiel de Sousa Nascimento",
      "Gabriel Jesus de Sousa David",
      "João Miguel Lima da Silva",
      "José Miguel Sousa Silva",
      "Lyara Araújo Freire",
      "Maria Emanuelly de Souza Santos",
      "Pedro Henrique Lima da Silva",
      "Sofia Sousa Lima",
      "Ulisses dos Santos da Silva",
      "Weliton de Almeida Aguiar",
      "Sulamita de Sousa Braga",
      "Jhonatan Lima Tavares",
      "Hiago da Silva Aguiar",
      "Carlos Eduardo da Silva",
      "Enzo Arthur Sousa",
      "Heitor Mendonça",
      "Arthur Lima Freitas",
      "Francisca Thaylla de Souza Fernandes",
      "Yhasmin Nascimento de Souza",
      "Ana Kaylla Souza do Nascimento",
      "João Pedro Sabóia Roque",
      "Sophia Pedrosa do Nascimento Lima",
    ]),
  },
  {
    id: "t-3a",
    serie: "3º Ano",
    letra: "A",
    professorRegente: "Geane",
    alunos: alunos([
      "Ana Lys dos Santos Silva",
      "Anallu Santos",
      "Clara Santos de Oliveira",
      "Clefferson da Silva Bastos",
      "Edivaldo Miguel de Souza Silva",
      "Elias Pinto de Sousa",
      "Enzo da Silva Aguiar",
      "Jaislene Barbosa Lima de Sousa Kaxinawá",
      "Johann Rafael Silva dos Santos",
      "Larissa Manuelly da Silva",
      "Maria Emanuele Pinheiro Almeida",
      "Marta Silva do Nascimento",
      "Matheus Pereira da Silva",
      "Samuel Nascimento Lima",
      "Kaio Silva",
      "Luiz Fernando Alves Melo",
      "João Guilherme Santos da Silva",
      "Ytallo Gabriel da Silva",
      "Maria Alice Tavares Damasceno",
      "Regiely Lima do Nascimento",
      "Lorenzo Freitas de Lima",
    ]),
  },
  {
    id: "t-3b",
    serie: "3º Ano",
    letra: "B",
    professorRegente: "Ane Neris",
    alunos: alunos([
      "Alan Santos Araújo",
      "Aline Almeida Aguiar",
      "Ana Clara Pereira de Deus",
      "Brayan Flor dos Santos",
      "Fernando de Lima dos Santos",
      "Francisco Izequiel da Silva de Sousa",
      "Gustavo de Oliveira",
      "Hávila Damázio Carvalho",
      "Henzo Gabriel Moraes da Silva",
      "Ivanira Moreno da Silva",
      "João Miguel de Sousa Bezerra",
      "Kaio Castro de Sousa",
      "Luis Felipe de Lima Sousa",
      "Paulo Arthur Braga",
      "Pedro Guilherme Almeida da Silva",
      "Railan Almeida Costa",
      "Roziele Silva de Lima",
      "José Vitor de Oliveira do Nascimento",
      "Rian Lucas do Nascimento Silva",
      "Asaph Moura Costa",
      "João Pedro Nogueira Silva",
      "Isabela Gomes do Carmo",
    ]),
  },
  {
    id: "t-4a",
    serie: "4º Ano",
    letra: "A",
    professorRegente: "Raimundo",
    alunos: alunos([
      "Anny Vitória Gomes Valente",
      "Aslyanne Souza Ribeiro",
      "Claudianny Tavares Lima",
      "Daniele da Silva Moreira",
      "Enzo Gabriel da Cruz Ferreira",
      "Enzo Gabriel de Souza Santos",
      "Gabriel Moura Silva",
      "Grazielly Araújo da Costa",
      "Jonatas Almeida Parente",
      "José Eduardo de Sousa Gomes",
      "José Ximenes Aguiar Neto",
      "Juan Pietro Souza Machado",
      "Katriel Silva do Nascimento",
      "Kauã da Silva",
      "Keyla Melissa de Souza Firmino",
      "Maria Issys Sousa Galdino",
      "Maria Júlia Braga da Silva",
      "Mirela Nascimento dos Santos",
      "Sabrina Parente de Souza",
      "Victor Emanuel Rodrigues da Silva",
      "Wandey Raphael Souza e Silva",
      "Wesley de Sousa da Rocha",
      "Yasmim Lo-Ruama Damazio Carvalho",
      "Krishnan Rhana da Costa Lima",
      "Dhemilly Lorana Simão da Silva",
      "Gabriel Tavares Lourenço",
    ]),
  },
  {
    id: "t-4b",
    serie: "4º Ano",
    letra: "B",
    professorRegente: "Elias",
    alunos: alunos([
      "Ana Ester do Nascimento da Silva",
      "Andriele Estefanny Souza dos Santos",
      "Anna Lys Silva de Aaújo",
      "Antonio Everton de Almeida Aguiar",
      "Clarisse Silva Sampaio",
      "Dhenniff da Silva Lima",
      "Franciane Silva Araújo",
      "Ícaro Luís Holanda dos Santos",
      "João Lucas Pereira Paiva",
      "João Miguel Ferreira da Silva",
      "José Dhailan Almeida Costa",
      "Liah Damasceno Barroso",
      "Maria Bianca Parente do Nascimento",
      "Mateus Silva de Lima",
      "Myrella Lima Brasil",
      "Nágila Vitória da Silva Lima",
      "Otávio Díel de Paiva Araújo",
      "Raphael Willyan da Silva Mendonça",
      "Rauan Carlos da Silva Souza",
      "Roserlândio Cardoso da Silva",
      "Suyara de Oliveira",
      "Vitor Manoel de Sousa Araújo",
      "Maria Cecília Sousa de Araújo",
      "Carlos Whaliki Santos da Silva",
      "Melrick Angelo da Silva Inácio",
      "Rian Pontes dos Santos",
    ]),
  },
  {
    id: "t-5a",
    serie: "5º Ano",
    letra: "A",
    professorRegente: "Vanderlandia",
    alunos: alunos([
      "Aléxia Fontinele Ponce",
      "Allana Vitória Sobrinho Parente",
      "Anna Clara de Sousa Amorim",
      "Carlos Daniel Lucas de Lima",
      "Diuliane do Nascimento Pereira",
      "Emanuelly do Nascimento Morais",
      "Fabrício Lima do Nascimento",
      "Geovana de Lima Silva",
      "Hadasha Felix de Aguiar",
      "Isa Gabriela Almeida Damázio",
      "Isabella Pinheiro Almeida",
      "João Luís Lopes de Araújo",
      "Jocivaldo do Nascimento da Silva",
      "José Willians Rodrigues da Silva",
      "Julia Sofia Bastos Raulino",
      "Luciano do Nascimento da Silva",
      "Maria Vitória da Silva do Nascimento",
      "Nycolas Oliveira de Paiva",
      "Pedro Gabriel Pinheiro Muniz",
      "Ronan Nascimento da Silva",
      "Williane Adila do Nascimento Lima",
      "Yan Gomes",
      "Kristen Vitória da Costa Lima",
      "Ruan Júlio do Nascimento Silva",
      "Jhony Remington Souza Santana",
      "Luiz Gustavo Tavares Lourenço",
      "Mary Jane Gomes do Carmo",
    ]),
  },
  {
    id: "t-5b",
    serie: "5º Ano",
    letra: "B",
    professorRegente: "Antonio",
    alunos: alunos([
      "Ana Vitória Souza de Freitas",
      "Davi Luiz de Sousa David",
      "Dheffeson da Silva Bastos",
      "Dheilan Almeida da Costa",
      "Eloysa Souza da Silva",
      "Emanuelle Nascimento de Souza",
      "Fernando Vitor Neri da Silva",
      "Francisco Joaquim da Silva Braga",
      "João Lucas Silva Araújo",
      "José Thalles Fontenele Brandão",
      "Kaique Cavalcante",
      "Keven Miquiato Smyk de Barros",
      "Lorenna Silva Mendonça",
      "Luis Ricardo Sousa Araújo",
      "Maria da Liberdade Moreno da Silva",
      "Maria Eloisa Silva de Souza",
      "Maria Lauane Bispo Pinto",
      "Natanael de Sousa da Rocha",
      "Rayllana Monteiro da Silva",
      "Rian David Almeida da Silva",
      "Stephane Castro de Melo",
      "João Miguel Lima Pereira",
      "Mirla do Nascimento",
      "Francisca Melissa Costa Braga",
      "Nicolas Queiroz de Sousa",
      "Henrique de Freitas Lima",
      "Davi Luiz Souza Neves",
      "Izaquel Pedrosa do Nascimento Lima",
    ]),
  },
];
