import type { ScheduleConfig, Turma } from "@/lib/types";

type AlunoEntry = string | [nome: string, especial: true];

/** `especial` marks the student as flagged "(Especial)" / AEE in the school's official roster. */
function alunos(entradas: AlunoEntry[]) {
  return entradas.map((entrada, index) => {
    const [nome, especial] = Array.isArray(entrada) ? entrada : [entrada, undefined];
    return {
      id: `a-${index}-${nome.length}-${index * 7 + 1}`,
      nome,
      necessidadeEspecial: especial,
    };
  });
}

export const SEED_CONFIG: ScheduleConfig = {
  nomeEscola: "Escola Municipal em Tempo Integral Dr. Eiraldo Carneiro de França",
  inep: "12004227",
  endereco: "Rua Ernane Moreira Braga, 108, Cohab",
  professorInformatica: "Franc D'nis",
  diasSemana: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
  // 3 blocos de 90 min por dia (manhã 1, manhã 2, tarde), cada um rendendo 3
  // grupos de 7 alunos (21 vagas) em vez dos 2 grupos (14 vagas) de antes —
  // quase dobra quantos alunos de cada turma participam por semana, sem
  // esticar o expediente além das 14:45 nem cortar o almoço/descanso.
  horaInicio: "07:30",
  horaFim: "14:45",
  // Almoço + descanso do professor: 2h15, incluindo o tempo de as crianças
  // voltarem e se acomodarem antes da aula da tarde recomeçar às 13:15.
  intervaloInicio: "11:00",
  intervaloFim: "13:15",
  // Recreio da manhã — a aula da manhã 1 já termina exatamente às 9:00 (sem
  // pausa extra antes), e a manhã 2 recomeça exatamente às 9:15.
  recreioInicio: "09:00",
  recreioFim: "09:15",
  duracaoSlotMinutos: 90,
  duracaoGrupoMinutos: 30,
  numeroComputadores: 7,
  conteudoPorDia: {
    Segunda: "Introdução ao computador: partes, ligar/desligar e cuidados com os equipamentos",
    Terça: "Digitação e edição de texto: teclado, maiúsculas, acentos e formatação básica",
    Quarta: "Pesquisa escolar na internet: navegação segura e seleção de fontes confiáveis",
    Quinta: "Jogos educativos e raciocínio lógico: sequências, padrões e resolução de problemas",
    Sexta: "Produção criativa: desenho digital, apresentações e apresentação dos trabalhos",
  },
};

export const SEED_TURMAS: Turma[] = [
  {
    id: "t-1a",
    serie: "1º Ano",
    letra: "A",
    professorRegente: "Celina",
    alunos: alunos([
      "Anna Lís Bastos dos Santos",
      ["Anthony Pietro Carvalho Braga", true],
      ["Bruna Pontes Saboia", true],
      "Bruno Almeida Costa",
      "Clara Santos da Silva",
      "Dárvely Cardoso Dias",
      "Davi Costa de França",
      "Enzo Pinto",
      "Ester de Sousa",
      "Evangeline Conceição Souza do Nascimento",
      "Francisco Noah Dimas de Melo",
      "Heittor de Sousa Ferreira",
      "Henzo Miguel Fernandes da Silva",
      "Kaylla Majúh Souza",
      "Luiz Miguel Santa'Ana do Nascimento",
      "Lys Vitória da Silva Nascimento",
      "Maria Luara da Costa Silva",
      "Maria Luna da Costa Silva",
      "Dhonata Leão Rodrigues",
      ["Gael Costa Soares", true],
      ["Sadrack Uriel Mendonça Cardoso", true],
      "Alice Souza Linhares",
      "Maria Hanna de Freitas Lima",
      "Josué Dias dos Santos",
    ]),
    apoioEspecial: [
      { nome: "Francisca Conceição de Sousa Freitas", funcao: "Mediador(a)" },
      { nome: "Vitória Kertelen Gomes Aguiar", funcao: "Mediador(a)" },
      { nome: "Carlos da Silva Alves", funcao: "Cuidador(a)" },
    ],
  },
  {
    id: "t-1b",
    serie: "1º Ano",
    letra: "B",
    professorRegente: "Cirley",
    alunos: alunos([
      "Emanuela Oliveira de Lima",
      "João Vitor Silva Leitão",
      "Josué Damázio Carvalho",
      "Katriele Silva Sampaio",
      "Manuela dos Santos Souza",
      "Miguel de Souza Santos",
      ["Natanael Santos Albuquerque", true],
      ["Oseias Pereira Gomes", true],
      "Pedro Rodrigues do Nascimento Neto",
      "Priscila da Silva",
      "Rebeca Santos Leite",
      "Sophia Cardoso da Silva",
      "Théo Silva Cardoso",
      "Yara da Silva Martins",
      ["Heythor Lorenzo Tavares Mendonça", true],
      "Felicia Sousa Leão",
      "Thaemilly da Silva do Nascimento",
      "Naylan da Silva Souza Yawanawá",
      "Naylandson da Silva Souza Yawanawá",
      ["Levi da Silva Albuquerque Kaxinawá", true],
      "Moisés Gomes do Carmo",
      "Sophia Pedrosa do Nascimento Lima",
      "Gabriel Surubi Almeida",
      "Ana Lis Silva Cardoso",
      ["Ezequiel Ferreira Machado", true],
    ]),
    apoioEspecial: [
      { nome: "Rute Rocha de Assis Sousa", funcao: "Mediador(a)" },
      { nome: "Magda Marta Lima do Nascimento", funcao: "Mediador(a)" },
    ],
  },
  {
    id: "t-2a",
    serie: "2º Ano",
    letra: "A",
    professorRegente: "França",
    alunos: alunos([
      "Ana Clara Farias de Lima",
      "Ana Lys da Silva Souza",
      "Analuh da Silva Sousa",
      "Daniela Rodrigues Silva",
      ["Eloah Souza da Silva", true],
      "Emanuelly de Sousa Rocha",
      "Érick Silva Pereira",
      "Fabrício dos Santos Sousa",
      "Isabella Nascimento Matos",
      "José Railan Parente do Nascimento",
      ["Kaúan Moreno Gadelha Shanenawá", true],
      "Letícia Sousa",
      "Luiz Fernando Souza de Freitas",
      "Maria Luísa de Souza Reis",
      "Maria Valentina Pinheiro Muniz",
      "Miguel Gomes Azevedo",
      "Nycolas Castro Ferreira",
      "Ravih Araújo Moura",
      "Sarah Sophia de Amorim Gomes",
      "Jefferson Rian Simão da Silva",
      "Alyce Matos de Sousa",
      "Antonia Eliza Nogueira Silva",
      "João Miguel Alves Pinto",
    ]),
  },
  {
    id: "t-2b",
    serie: "2º Ano",
    letra: "B",
    professorRegente: "Anaiton",
    alunos: alunos([
      "Ana Paula França da Silva",
      ["Andreison Silva Araújo", true],
      ["Ezequiel de Sousa Nascimento", true],
      "Gabriel Jesus de Sousa David",
      "João Miguel Lima da Silva",
      "José Miguel Sousa Silva",
      "Lyara Araújo Freire",
      "Maria Emanuelly de Souza Santos",
      ["Pedro Henrique Lima da Silva", true],
      "Sofia Sousa Lima",
      "Weliton de Almeida Aguiar",
      "Sulamita de Sousa Braga",
      "Jhonatan Lima Tavares",
      "Hiago da Silva Aguiar",
      "Carlos Eduardo da Silva",
      "Enzo Arthur Sousa",
      ["Heitor Mendonça", true],
      ["Arthur Lima Freitas", true],
      "Yhasmin Nascimento de Souza",
      "João Pedro Sabóia Roque",
      ["Arthur da Silva Sousa", true],
    ]),
  },
  {
    id: "t-3a",
    serie: "3º Ano",
    letra: "A",
    professorRegente: "Geane",
    alunos: alunos([
      "Ana Lys dos Santos Silva",
      "Anallu Santos",
      "Clara Santos de Oliveira",
      "Clefferson da Silva Bastos",
      "Edivaldo Miguel de Souza Silva",
      "Elias Pinto de Sousa",
      "Jaislene Barbosa Lima de Sousa Kaxinawá",
      "Larissa Manuelly da Silva",
      "Maria Emanuele Pinheiro Almeida",
      "Marta Silva do Nascimento",
      ["Matheus Pereira da Silva", true],
      "Samuel Nascimento Lima",
      "Kaio Silva",
      ["Luiz Fernando Alves Melo", true],
      "João Guilherme Santos da Silva",
      "Ytallo Gabriel da Silva",
      "Maria Alice Tavares Damasceno",
      "Regiely Lima do Nascimento",
      "Lorenzo Freitas de Lima",
      "Andressa Vasconcellos Gomes",
    ]),
    apoioEspecial: [{ nome: "Pliciam Rodrigues Costa", funcao: "Cuidador(a)" }],
  },
  {
    id: "t-3b",
    serie: "3º Ano",
    letra: "B",
    professorRegente: "Ane Neris",
    alunos: alunos([
      "Alan Santos Araújo",
      "Aline Almeida Aguiar",
      "Ana Clara Pereira de Deus",
      "Brayan Flor dos Santos",
      "Fernando de Lima dos Santos",
      "Gustavo de Oliveira",
      "Hávila Damázio Carvalho",
      "Henzo Gabriel Moraes da Silva",
      "Ivanira Moreno da Silva",
      ["João Miguel de Sousa Bezerra", true],
      "Kaio Castro de Sousa",
      "Luis Felipe de Lima Sousa",
      "Paulo Arthur Braga",
      "Pedro Guilherme Almeida da Silva",
      "Railan Almeida Costa",
      "Roziele Silva de Lima",
      "José Vitor de Oliveira do Nascimento",
      "Asaph Moura Costa",
      "João Pedro Nogueira Silva",
      "Isabela Gomes do Carmo",
      "Cauã Deyverson Damazio da Silva",
      ["Cauê Felipe Damazio da Silva", true],
    ]),
    apoioEspecial: [
      { nome: "Nonata Rodrigues Mota de Castro", funcao: "Mediador(a)" },
      { nome: "Maria Janigleuba Sousa de Sousa Deus", funcao: "Mediador(a)" },
      { nome: "Maria Sousa da Silva", funcao: "Mediador(a)" },
    ],
  },
  {
    id: "t-4a",
    serie: "4º Ano",
    letra: "A",
    professorRegente: "Raimundo",
    alunos: alunos([
      "Aslyanne Souza Ribeiro",
      "Claudianny Tavares Lima",
      "Daniele da Silva Moreira",
      "Enzo Gabriel da Cruz Ferreira",
      ["Enzo Gabriel de Souza Santos", true],
      "Gabriel Moura Silva",
      "Jonatas Almeida Parente",
      "José Eduardo de Sousa Gomes",
      "José Ximenes Aguiar Neto",
      ["Juan Pietro Souza Machado", true],
      "Kauã da Silva",
      "Keyla Melissa de Souza Firmino",
      "Maria Júlia Braga da Silva",
      "Mirela Nascimento dos Santos",
      ["Victor Emanuel Rodrigues da Silva", true],
      "Wandey Raphael Souza e Silva",
      ["Wesley de Sousa da Rocha", true],
      "Yasmim Lo-Ruama Damazio Carvalho",
      "Dhemilly Lorana Simão da Silva",
      ["Gabriel Tavares Lourenço", true],
      "Isabella Surubi Almeida",
      "Antônio Eduardo Vasconcellos de Castro",
      "Anielly de Sousa",
    ]),
    apoioEspecial: [
      { nome: "José Lucas de Sousa Silva", funcao: "Mediador(a)" },
      { nome: "Maria Vilma dos Santos da Silva", funcao: "Mediador(a)" },
      { nome: "Roberlanjo Araujo Santos", funcao: "Mediador(a)" },
    ],
  },
  {
    id: "t-4b",
    serie: "4º Ano",
    letra: "B",
    professorRegente: "Elias",
    alunos: alunos([
      "Ana Ester do Nascimento da Silva",
      "Andriele Estefanny Souza dos Santos",
      "Anna Lys Silva de Araújo",
      "Antonio Everton de Almeida Aguiar",
      "Clarisse Silva Sampaio",
      "Dhenniff da Silva Lima",
      "Franciane Silva Araújo",
      ["Ícaro Luís Holanda dos Santos", true],
      "João Lucas Pereira Paiva",
      ["João Miguel Ferreira da Silva", true],
      "José Dhailan Almeida Costa",
      "Maria Bianca Parente do Nascimento",
      ["Mateus Silva de Lima", true],
      "Myrella Lima Brasil",
      "Nágila Vitória da Silva Lima",
      "Otávio Díel de Paiva Araújo",
      "Raphael Willyan da Silva Mendonça",
      ["Rauan Carlos da Silva Souza", true],
      ["Vitor Manoel de Sousa Araújo", true],
      "Maria Cecília Sousa de Araújo",
      ["Carlos Whaliki Santos da Silva", true],
      ["Melrick Angelo da Silva Inácio", true],
      ["João Miguel Sousa do Nascimento", true],
    ]),
    apoioEspecial: [
      { nome: "Francisca Samia Sousa Menezes", funcao: "Mediador(a)" },
      { nome: "Antonia Maria de Freitas Martins", funcao: "Mediador(a)" },
      { nome: "Maria Erinalda de Sousa e Sousa", funcao: "Mediador(a)" },
      { nome: "Antonio Aldeir Gomes de Paiva", funcao: "Mediador(a)" },
    ],
  },
  {
    id: "t-5a",
    serie: "5º Ano",
    letra: "A",
    professorRegente: "Vanderlandia",
    alunos: alunos([
      "Aléxia Fontinele Ponce",
      "Allana Vitória Sobrinho Parente",
      "Anna Clara de Sousa Amorim",
      ["Carlos Daniel Lucas de Lima", true],
      "Diuliane do Nascimento Pereira",
      "Fabrício Lima do Nascimento",
      "Geovana de Lima Silva",
      "Hadasha Felix de Aguiar",
      "Isa Gabriela Almeida Damázio",
      "João Luís Lopes de Araújo",
      "Jocivaldo do Nascimento da Silva",
      "José Willians Rodrigues da Silva",
      "Julia Sofia Bastos Raulino",
      "Luciano do Nascimento da Silva",
      "Maria Vitória da Silva do Nascimento",
      "Nycolas Oliveira de Paiva",
      ["Pedro Gabriel Pinheiro Muniz", true],
      "Ronan Nascimento da Silva",
      "Williane Adila do Nascimento Lima",
      "Yan Gomes",
      "Jhony Remington Souza Santana",
      "Luiz Gustavo Tavares Lourenço",
      "Mary Jane Gomes do Carmo",
      ["Davi Luiz de Oliveira de Lima", true],
      "Rosilene Pereira de Aguiar Kaxinawá",
    ]),
    apoioEspecial: [{ nome: "Christian do Nascimento Sousa", funcao: "Cuidador(a)" }],
  },
  {
    id: "t-5b",
    serie: "5º Ano",
    letra: "B",
    professorRegente: "Antonio",
    alunos: alunos([
      "Ana Vitória Souza de Freitas",
      "Davi Luiz de Sousa David",
      "Dheffeson da Silva Bastos",
      "Dheilan Almeida da Costa",
      "Eloysa Souza da Silva",
      "Emanuelle Nascimento de Souza",
      ["Francisco Joaquim da Silva Braga", true],
      ["João Lucas Silva Araújo", true],
      "José Thalles Fontenele Brandão",
      "Kaique Cavalcante",
      "Keven Miquiato Smyk de Barros",
      "Lorenna Silva Mendonça",
      "Luis Ricardo Sousa Araújo",
      "Maria da Liberdade Moreno da Silva",
      "Maria Eloisa Silva de Souza",
      "Maria Lauane Bispo Pinto",
      "Natanael de Sousa da Rocha",
      "Rayllana Monteiro da Silva",
      "Rian David Almeida da Silva",
      "Stephane Castro de Melo",
      "João Miguel Lima Pereira",
      "Mirla do Nascimento",
      "Francisca Melissa Costa Braga",
      "Nicolas Queiroz de Sousa",
      "Henrique de Freitas Lima",
      "Davi Luiz Souza Neves",
      ["Izaquel Pedrosa do Nascimento Lima", true],
    ]),
    apoioEspecial: [{ nome: "Kalebe Meireles Ribeiro", funcao: "Cuidador(a)" }],
  },
];
