import type { ScheduleConfig, Turma } from "@/lib/types";

function alunos(nomes: string[]) {
  return nomes.map((nome, index) => ({ id: `a-${index}-${nome.length}-${index * 7 + 1}`, nome }));
}

export const SEED_CONFIG: ScheduleConfig = {
  nomeEscola: "Escola Municipal em Tempo Integral Dr. Eiraldo Carneiro de França",
  inep: "12004227",
  endereco: "Rua Ernane Moreira Braga, 108, Cohab",
  professorInformatica: "Franc D'nis",
  diasSemana: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
  horaInicio: "08:00",
  horaFim: "15:00",
  intervaloInicio: "12:00",
  intervaloFim: "13:00",
  duracaoSlotMinutos: 60,
  duracaoGrupoMinutos: 30,
  numeroComputadores: 7,
};

export const SEED_TURMAS: Turma[] = [
  {
    id: "t-1a",
    serie: "1º Ano",
    letra: "A",
    professorRegente: "Celina",
    alunos: alunos([
      "Anna Lís Bastos dos Santos",
      "Anthony Pietro Carvalho Braga",
      "Bruna Pontes Saboia",
      "Bruno Almeida Costa",
      "Clara Santos da Silva",
      "Dárvely Cardoso Dias",
      "Davi Costa de França",
      "Enzo Pinto",
      "Ester de Sousa",
      "Evangeline Conceição Souza do Nascimento",
      "Francisco Noah Dimas de Melo",
      "Heittor de Sousa Ferreira",
      "Henzo Miguel Fernandes da Silva",
      "Kaylla Majúh Souza",
      "Luiz Miguel Santa'Ana do Nascimento",
      "Lys Vitória da Silva Nascimento",
      "Maria Luara da Costa Silva",
      "Maria Luna da Costa Silva",
      "Antonia Emilly Muniz da Silva",
      "Dhonata Leão Rodrigues",
      "Gael Costa Soares",
      "Sadrack Uriel Mendonça Cardoso",
      "Alice Souza Linhares",
      "Maria Hanna de Freitas Lima",
      "Josué Dias dos Santos",
    ]),
  },
  {
    id: "t-1b",
    serie: "1º Ano",
    letra: "B",
    professorRegente: "Cirley",
    alunos: alunos([
      "Dheyslan Cardoso de Araújo",
      "Dhieyson Cardoso de Araújo",
      "Emanuela Oliveira de Lima",
      "João Vitor Silva Leitão",
      "Josué Damázio Carvalho",
      "Katriele Silva Sampaio",
      "Kelly Santos Flor",
      "Manuela dos Santos Souza",
      "Miguel de Souza Santos",
      "Natanael Santos Albuquerque",
      "Oseias Pereira Gomes",
      "Pedro Rodrigues do Nascimento Neto",
      "Priscila da Silva",
      "Rebeca Santos Leite",
      "Sophia Cardoso da Silva",
      "Théo Silva Cardoso",
      "Yara da Silva Martins",
      "Yasmin Pontes da Silva",
      "Heythor Lorenzo Tavares Mendonça",
      "Heloisa da Silva Aguiar",
      "Felícia Sousa Leão",
      "Thaemilly da Silva do Nascimento",
      "Naylan da Silva Souza Yawanawá",
      "Naylandson da Silva Souza Yawanawá",
      "Levi da Silva Albuquerque Kaxinawá",
      "Moisés Gomes do Carmo",
    ]),
  },
  {
    id: "t-2a",
    serie: "2º Ano",
    letra: "A",
    professorRegente: "França",
    alunos: [],
  },
  {
    id: "t-2b",
    serie: "2º Ano",
    letra: "B",
    professorRegente: "Anaiton",
    alunos: alunos([
      "Ana Paula França da Silva",
      "Andreison Silva Araújo",
      "Ezequiel de Sousa Nascimento",
      "Gabriel Jesus de Sousa David",
      "João Miguel Lima da Silva",
      "José Miguel Sousa Silva",
      "Lyara Araújo Freire",
      "Maria Emanuelly de Souza Santos",
      "Pedro Henrique Lima da Silva",
      "Sofia Sousa Lima",
      "Ulisses dos Santos da Silva",
      "Weliton de Almeida Aguiar",
      "Sulamita de Sousa Braga",
      "Jhonatan Lima Tavares",
      "Hiago da Silva Aguiar",
      "Carlos Eduardo da Silva",
      "Enzo Arthur Sousa",
      "Heitor Mendonça",
      "Arthur Lima Freitas",
      "Francisca Thaylla de Souza Fernandes",
      "Yhasmin Nascimento de Souza",
      "Ana Kaylla Souza do Nascimento",
      "João Pedro Sabóia Roque",
      "Sophia Pedrosa do Nascimento Lima",
    ]),
  },
  {
    id: "t-3a",
    serie: "3º Ano",
    letra: "A",
    professorRegente: "Geane",
    alunos: alunos([
      "Ana Lys dos Santos Silva",
      "Anallu Santos",
      "Clara Santos de Oliveira",
      "Clefferson da Silva Bastos",
      "Edivaldo Miguel de Souza Silva",
      "Elias Pinto de Sousa",
      "Enzo da Silva Aguiar",
      "Jaislene Barbosa Lima de Sousa Kaxinawá",
      "Johann Rafael Silva dos Santos",
      "Larissa Manuelly da Silva",
      "Maria Emanuele Pinheiro Almeida",
      "Marta Silva do Nascimento",
      "Matheus Pereira da Silva",
      "Samuel Nascimento Lima",
      "Kaio Silva",
      "Luiz Fernando Alves Melo",
      "João Guilherme Santos da Silva",
      "Ytallo Gabriel da Silva",
      "Maria Alice Tavares Damasceno",
      "Regiely Lima do Nascimento",
      "Lorenzo Freitas de Lima",
    ]),
  },
  {
    id: "t-3b",
    serie: "3º Ano",
    letra: "B",
    professorRegente: "Ane Neris",
    alunos: [],
  },
  {
    id: "t-4a",
    serie: "4º Ano",
    letra: "A",
    professorRegente: "Elias",
    alunos: [],
  },
  {
    id: "t-4b",
    serie: "4º Ano",
    letra: "B",
    professorRegente: "Raimundo",
    alunos: [],
  },
  {
    id: "t-5a",
    serie: "5º Ano",
    letra: "A",
    professorRegente: "Vanderlandia",
    alunos: [],
  },
  {
    id: "t-5b",
    serie: "5º Ano",
    letra: "B",
    professorRegente: "Antonio",
    alunos: [],
  },
];
