import type { DadosI } from "@/lib/diagnostica/tipos";

/**
 * I Avaliação Diagnóstica 2026 (SEME), recorte da Escola Dr. Eiraldo
 * Carneiro de França, extraído da planilha de tabulação da rede.
 *
 * Diferente da II, a planilha da I é consolidada por turma: não há resposta
 * aluno a aluno, só percentuais. Por isso os números daqui alimentam as
 * comparações de turma, e a análise individual continua vindo da II.
 *
 * Cada questão carrega, além do acerto da turma, quanto Feijó e o Acre
 * inteiro acertaram na mesma questão. É o que separa "a turma não aprendeu
 * isso" de "essa questão foi difícil para todo mundo" — sem essa régua, um
 * 44% de acerto não diz se é problema nosso ou da prova.
 */
export const DADOS_I: DadosI = {
  aplicacao: "I",
  titulo: "I Avaliação Diagnóstica 2026",
  escola: "DR. EIRALDO CARNEIRO DE FRANÇA",
  municipio: "FEIJÓ",
  turmas: [
    {
      ano: 1,
      turma: "A",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 18,
      faltosos: 4,
      media: null,
      azuis: null,
      faixas: { insuficiente: null, regular: null, bom: null, otimo: null },
      escrita: { A: 0, B: 0, C1: 0.05, C2: 0.11, C3: 0.06, D: 0.78, E: 0 },
      alfabeticos: 0.05,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [],
    },
    {
      ano: 1,
      turma: "A",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 18,
      faltosos: 4,
      media: 54,
      azuis: 0.55,
      faixas: { insuficiente: 0.06, regular: 0.39, bom: 0.33, otimo: 0.22 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.67,
          hab: "1N1.1 - Utilizar números naturais como indicador de quantidade\r\nou de ordem em diferentes situações cotidianas.",
          feijo: 0.7025,
          acre: 0.8384,
        },
        {
          q: 2,
          acerto: 0.61,
          hab: "1N2.4 - Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos.",
          feijo: 0.61,
          acre: 0.7032,
        },
        {
          q: 3,
          acerto: 0.44,
          hab: "1N1.4 - Comparar quantidades de objetos de dois conjuntos (no\r\nmínimo 20 elementos), por estimativa e/ ou por\r\ncorrespondência (um a um, dois a dois) para indicar “tem mais”,\r\n“tem menos” ou “tem a mesma quantidade.",
          feijo: 0.3475,
          acre: 0.5702,
        },
        {
          q: 4,
          acerto: 0.44,
          hab: "1G1.2 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições.",
          feijo: 0.2137,
          acre: 0.3729,
        },
      ],
    },
    {
      ano: 1,
      turma: "B",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 18,
      faltosos: 3,
      media: null,
      azuis: null,
      faixas: { insuficiente: null, regular: null, bom: null, otimo: null },
      escrita: { A: 0, B: 0, C1: 0, C2: 0, C3: 0, D: 0.94, E: 0.06 },
      alfabeticos: 0,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [],
    },
    {
      ano: 1,
      turma: "B",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 18,
      faltosos: 3,
      media: 51.25,
      azuis: 0.72,
      faixas: { insuficiente: 0, regular: 0.28, bom: 0.44, otimo: 0.28 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.72,
          hab: "1N1.1 - Utilizar números naturais como indicador de quantidade\r\nou de ordem em diferentes situações cotidianas.",
          feijo: 0.7025,
          acre: 0.8384,
        },
        {
          q: 2,
          acerto: 0.72,
          hab: "1N2.4 - Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos.",
          feijo: 0.61,
          acre: 0.7032,
        },
        {
          q: 3,
          acerto: 0.5,
          hab: "1N1.4 - Comparar quantidades de objetos de dois conjuntos (no\r\nmínimo 20 elementos), por estimativa e/ ou por\r\ncorrespondência (um a um, dois a dois) para indicar “tem mais”,\r\n“tem menos” ou “tem a mesma quantidade.",
          feijo: 0.3475,
          acre: 0.5702,
        },
        {
          q: 4,
          acerto: 0.11,
          hab: "1G1.2 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições.",
          feijo: 0.2137,
          acre: 0.3729,
        },
      ],
    },
    {
      ano: 2,
      turma: "A",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 19,
      faltosos: 3,
      media: 36.8,
      azuis: 0.26,
      faixas: { insuficiente: 0.58, regular: 0.16, bom: 0.05, otimo: 0.21 },
      escrita: { A: 0, B: 0.31, C1: 0.16, C2: 0.16, C3: 0, D: 0.37, E: 0 },
      alfabeticos: 0.31,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.42,
          hab: "Relacionar elementos sonoros das palavras com sua \r\nrepresentação escrita.",
          feijo: 0.4012,
          acre: 0.6728,
        },
        { q: 3, acerto: 0.47, hab: "Ler palavras.", feijo: 0.5188, acre: 0.6471 },
        { q: 4, acerto: 0.26, hab: "Ler frases.", feijo: 0.4, acre: 0.5908 },
        {
          q: 5,
          acerto: 0.37,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.5088,
          acre: 0.6132,
        },
        {
          q: 6,
          acerto: 0.32,
          hab: "Localizar uma informação explícita em um texto.",
          feijo: 0.4438,
          acre: 0.5505,
        },
      ],
    },
    {
      ano: 2,
      turma: "A",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 20,
      faltosos: 2,
      media: 55.0,
      azuis: 0.75,
      faixas: { insuficiente: 0.1, regular: 0.15, bom: 0.65, otimo: 0.1 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        { q: 1, acerto: 0.65, hab: "2N2.4 - Realizar contagem.", feijo: 0.5057, acre: 0.7262 },
        {
          q: 2,
          acerto: 0.4,
          hab: "2N1.4 - Comparar quantidades de objetos.",
          feijo: 0.3571,
          acre: 0.5592,
        },
        {
          q: 3,
          acerto: 0.75,
          hab: "2G2.1 – Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás.",
          feijo: 0.5886,
          acre: 0.6877,
        },
        {
          q: 4,
          acerto: 0.7,
          hab: "2M1.1 - Comparar capacidades com base na comparação visual.",
          feijo: 0.7557,
          acre: 0.8381,
        },
        {
          q: 5,
          acerto: 0.2,
          hab: "2E1.2 - Ler e localizar dados expressos em tabelas simples.",
          feijo: 0.4286,
          acre: 0.6011,
        },
        {
          q: 6,
          acerto: 0.6,
          hab: "2N2.1 - Resolver problemas com números naturais envolvendo\r\nadição, utilizando estratégias diversas.",
          feijo: 0.55,
          acre: 0.6877,
        },
      ],
    },
    {
      ano: 2,
      turma: "B",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 13,
      faltosos: 4,
      media: 50.8,
      azuis: 0.39,
      faixas: { insuficiente: 0.23, regular: 0.38, bom: 0.08, otimo: 0.31 },
      escrita: { A: 0.08, B: 0.31, C1: 0, C2: 0.15, C3: 0.23, D: 0.23, E: 0 },
      alfabeticos: 0.39,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.62,
          hab: "Relacionar elementos sonoros das palavras com sua \r\nrepresentação escrita.",
          feijo: 0.4012,
          acre: 0.6728,
        },
        { q: 3, acerto: 0.46, hab: "Ler palavras.", feijo: 0.5188, acre: 0.6471 },
        { q: 4, acerto: 0.31, hab: "Ler frases.", feijo: 0.4, acre: 0.5908 },
        {
          q: 5,
          acerto: 0.69,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.5088,
          acre: 0.6132,
        },
        {
          q: 6,
          acerto: 0.46,
          hab: "Localizar uma informação explícita em um texto.",
          feijo: 0.4438,
          acre: 0.5505,
        },
      ],
    },
    {
      ano: 2,
      turma: "B",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 13,
      faltosos: 4,
      media: 55.3333,
      azuis: 0.85,
      faixas: { insuficiente: 0.15, regular: 0, bom: 0.62, otimo: 0.23 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        { q: 1, acerto: 0.62, hab: "2N2.4 - Realizar contagem.", feijo: 0.5057, acre: 0.7262 },
        {
          q: 2,
          acerto: 0.46,
          hab: "2N1.4 - Comparar quantidades de objetos.",
          feijo: 0.3571,
          acre: 0.5592,
        },
        {
          q: 3,
          acerto: 0.62,
          hab: "2G2.1 – Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás.",
          feijo: 0.5886,
          acre: 0.6877,
        },
        {
          q: 4,
          acerto: 0.77,
          hab: "2M1.1 - Comparar capacidades com base na comparação visual.",
          feijo: 0.7557,
          acre: 0.8381,
        },
        {
          q: 5,
          acerto: 0.54,
          hab: "2E1.2 - Ler e localizar dados expressos em tabelas simples.",
          feijo: 0.4286,
          acre: 0.6011,
        },
        {
          q: 6,
          acerto: 0.31,
          hab: "2N2.1 - Resolver problemas com números naturais envolvendo\r\nadição, utilizando estratégias diversas.",
          feijo: 0.55,
          acre: 0.6877,
        },
      ],
    },
    {
      ano: 3,
      turma: "A",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 14,
      faltosos: 3,
      media: 33.4444,
      azuis: 0.21,
      faixas: { insuficiente: 0.43, regular: 0.36, bom: 0.21, otimo: 0 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.71,
      ortografia: { A: 0, B: 0, C: 0.14, D: 0.57, E: 0.29 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.43,
          hab: "Localizar informações explícitas em um texto.",
          feijo: 0.4371,
          acre: 0.6168,
        },
        {
          q: 3,
          acerto: 0.07,
          hab: "Inferir informações em textos verbais.",
          feijo: 0.3686,
          acre: 0.556,
        },
        {
          q: 4,
          acerto: 0.43,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.5257,
          acre: 0.6904,
        },
        {
          q: 5,
          acerto: 0.71,
          hab: "Inferir informação em textos que articulam linguagem verbal e não verbal.",
          feijo: 0.5457,
          acre: 0.7143,
        },
        {
          q: 6,
          acerto: 0.29,
          hab: "Inferir o assunto de cantos, cantigas e canções.",
          feijo: 0.41,
          acre: 0.5759,
        },
        {
          q: 7,
          acerto: 0.43,
          hab: "Identificar o efeito de sentido produzido pelo uso de recursos\r\ngráfico-visuais em textos multissemióticos.",
          feijo: 0.4857,
          acre: 0.5968,
        },
        {
          q: 8,
          acerto: 0.29,
          hab: "Identificar o assunto de um texto.",
          feijo: 0.3871,
          acre: 0.5676,
        },
        {
          q: 9,
          acerto: 0.29,
          hab: "Identificar o uso do ponto final, ponto de interrogação e ponto de\r\nexclamação para compreensão dos efeitos de sentido no texto.",
          feijo: 0.29,
          acre: 0.4103,
        },
        {
          q: 10,
          acerto: 0.07,
          hab: "Identificar o conflito gerador e sua resolução, além de palavras, expressões e frases que caracterizem personagens e ambientes\r\nda narrativa.",
          feijo: 0.3371,
          acre: 0.3857,
        },
      ],
    },
    {
      ano: 3,
      turma: "A",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 14,
      faltosos: 3,
      media: 37.7,
      azuis: 0.28,
      faixas: { insuficiente: 0.29, regular: 0.43, bom: 0.21, otimo: 0.07 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.57,
          hab: "3M1.5 - Comparar ou ordenar números naturais de até 3\r\nordens.",
          feijo: 0.5863,
          acre: 0.7567,
        },
        {
          q: 2,
          acerto: 0.36,
          hab: "3M1.6 - Identificar a ordem ocupada por um algarismo ou\r\nseu valor posicional em um número natural.",
          feijo: 0.355,
          acre: 0.4898,
        },
        {
          q: 3,
          acerto: 0.14,
          hab: "3M1.7 - Calcular o resultado de adições.",
          feijo: 0.4062,
          acre: 0.6029,
        },
        {
          q: 4,
          acerto: 0.57,
          hab: "3M2.1 - Resolver problemas de adição com os significados\r\nde juntar, acrescentar.",
          feijo: 0.52,
          acre: 0.6075,
        },
        {
          q: 5,
          acerto: 0.21,
          hab: "3M2.1 - Resolver problemas de subtração com os\r\nsignificados de separar, retirar.",
          feijo: 0.2863,
          acre: 0.4766,
        },
        {
          q: 6,
          acerto: 0.21,
          hab: "3M2.2 - Resolver problemas envolvendo dobro, metade,\r\ntriplo e terça parte.",
          feijo: 0.2,
          acre: 0.3833,
        },
        {
          q: 7,
          acerto: 0.71,
          hab: "3M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida padronizadas.",
          feijo: 0.6475,
          acre: 0.8475,
        },
        {
          q: 8,
          acerto: 0.21,
          hab: "3M1.4 - Reconhecer unidades de medida e/ou instrumentos\r\nutilizados para medir comprimento, tempo, massa ou\r\ncapacidade.",
          feijo: 0.305,
          acre: 0.4326,
        },
        {
          q: 9,
          acerto: 0.5,
          hab: "3G1.3 - Identificar e nomear figuras planas (círculo,\r\nquadrado, retângulo e triângulo).",
          feijo: 0.5,
          acre: 0.6418,
        },
        {
          q: 10,
          acerto: 0.29,
          hab: "3E1.2 - Ler dados expressos em gráficos de colunas\r\nsimples.",
          feijo: 0.4287,
          acre: 0.5363,
        },
      ],
    },
    {
      ano: 3,
      turma: "B",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 17,
      faltosos: 2,
      media: 50.8889,
      azuis: 0.53,
      faixas: { insuficiente: 0.06, regular: 0.41, bom: 0.41, otimo: 0.12 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.82,
      ortografia: { A: 0, B: 0.23, C: 0.18, D: 0.41, E: 0.18 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.59,
          hab: "Localizar informações explícitas em um texto.",
          feijo: 0.4371,
          acre: 0.6168,
        },
        {
          q: 3,
          acerto: 0.59,
          hab: "Inferir informações em textos verbais.",
          feijo: 0.3686,
          acre: 0.556,
        },
        {
          q: 4,
          acerto: 0.53,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.5257,
          acre: 0.6904,
        },
        {
          q: 5,
          acerto: 0.59,
          hab: "Inferir informação em textos que articulam linguagem verbal e não verbal.",
          feijo: 0.5457,
          acre: 0.7143,
        },
        {
          q: 6,
          acerto: 0.41,
          hab: "Inferir o assunto de cantos, cantigas e canções.",
          feijo: 0.41,
          acre: 0.5759,
        },
        {
          q: 7,
          acerto: 0.76,
          hab: "Identificar o efeito de sentido produzido pelo uso de recursos\r\ngráfico-visuais em textos multissemióticos.",
          feijo: 0.4857,
          acre: 0.5968,
        },
        {
          q: 8,
          acerto: 0.47,
          hab: "Identificar o assunto de um texto.",
          feijo: 0.3871,
          acre: 0.5676,
        },
        {
          q: 9,
          acerto: 0.29,
          hab: "Identificar o uso do ponto final, ponto de interrogação e ponto de\r\nexclamação para compreensão dos efeitos de sentido no texto.",
          feijo: 0.29,
          acre: 0.4103,
        },
        {
          q: 10,
          acerto: 0.35,
          hab: "Identificar o conflito gerador e sua resolução, além de palavras, expressões e frases que caracterizem personagens e ambientes\r\nda narrativa.",
          feijo: 0.3371,
          acre: 0.3857,
        },
      ],
    },
    {
      ano: 3,
      turma: "B",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 16,
      faltosos: 3,
      media: 48.9,
      azuis: 0.63,
      faixas: { insuficiente: 0.12, regular: 0.25, bom: 0.44, otimo: 0.19 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.5,
          hab: "3M1.5 - Comparar ou ordenar números naturais de até 3\r\nordens.",
          feijo: 0.5863,
          acre: 0.7567,
        },
        {
          q: 2,
          acerto: 0.56,
          hab: "3M1.6 - Identificar a ordem ocupada por um algarismo ou\r\nseu valor posicional em um número natural.",
          feijo: 0.355,
          acre: 0.4898,
        },
        {
          q: 3,
          acerto: 0.56,
          hab: "3M1.7 - Calcular o resultado de adições.",
          feijo: 0.4062,
          acre: 0.6029,
        },
        {
          q: 4,
          acerto: 0.69,
          hab: "3M2.1 - Resolver problemas de adição com os significados\r\nde juntar, acrescentar.",
          feijo: 0.52,
          acre: 0.6075,
        },
        {
          q: 5,
          acerto: 0.06,
          hab: "3M2.1 - Resolver problemas de subtração com os\r\nsignificados de separar, retirar.",
          feijo: 0.2863,
          acre: 0.4766,
        },
        {
          q: 6,
          acerto: 0.13,
          hab: "3M2.2 - Resolver problemas envolvendo dobro, metade,\r\ntriplo e terça parte.",
          feijo: 0.2,
          acre: 0.3833,
        },
        {
          q: 7,
          acerto: 0.63,
          hab: "3M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida padronizadas.",
          feijo: 0.6475,
          acre: 0.8475,
        },
        {
          q: 8,
          acerto: 0.5,
          hab: "3M1.4 - Reconhecer unidades de medida e/ou instrumentos\r\nutilizados para medir comprimento, tempo, massa ou\r\ncapacidade.",
          feijo: 0.305,
          acre: 0.4326,
        },
        {
          q: 9,
          acerto: 0.63,
          hab: "3G1.3 - Identificar e nomear figuras planas (círculo,\r\nquadrado, retângulo e triângulo).",
          feijo: 0.5,
          acre: 0.6418,
        },
        {
          q: 10,
          acerto: 0.63,
          hab: "3E1.2 - Ler dados expressos em gráficos de colunas\r\nsimples.",
          feijo: 0.4287,
          acre: 0.5363,
        },
      ],
    },
    {
      ano: 4,
      turma: "A",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 22,
      faltosos: 2,
      media: 45.0909,
      azuis: 0.41,
      faixas: { insuficiente: 0.14, regular: 0.45, bom: 0.27, otimo: 0.14 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.86,
      ortografia: { A: 0.05, B: 0.27, C: 0.09, D: 0.45, E: 0.14 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.36,
          hab: "Localizar informação explícita em um texto.",
          feijo: 0.475,
          acre: 0.6847,
        },
        {
          q: 3,
          acerto: 0.82,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.7963,
          acre: 0.8239,
        },
        {
          q: 4,
          acerto: 0.09,
          hab: "Inferir o sentido de palavras ou expressões.",
          feijo: 0.1375,
          acre: 0.2127,
        },
        { q: 5, acerto: 0.64, hab: "Inferir o assunto de um texto.", feijo: 0.4875, acre: 0.5375 },
        {
          q: 6,
          acerto: 0.14,
          hab: "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
          feijo: 0.2013,
          acre: 0.2515,
        },
        {
          q: 7,
          acerto: 0.59,
          hab: "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
          feijo: 0.3925,
          acre: 0.5322,
        },
        {
          q: 8,
          acerto: 0.73,
          hab: "Interpretar texto com auxílio de material gráfico diverso \r\n(propagandas, quadrinhos, fotos etc.).",
          feijo: 0.6787,
          acre: 0.6991,
        },
        {
          q: 9,
          acerto: 0.41,
          hab: "Inferir informações implícitas em textos.",
          feijo: 0.4525,
          acre: 0.5325,
        },
        {
          q: 10,
          acerto: 0.32,
          hab: "Analisar efeitos de sentido de recursos multissemióticos em\r\ntextos que circulam em diferentes suportes.",
          feijo: 0.52,
          acre: 0.6717,
        },
        {
          q: 11,
          acerto: 0.41,
          hab: "Identificar o uso adequado do ponto final, ponto de interrogação\r\ne de exclamação para compreensão dos efeitos de sentido no\r\ntexto.",
          feijo: 0.3688,
          acre: 0.4318,
        },
        {
          q: 12,
          acerto: 0.45,
          hab: "Construir sentido de história em quadrinhos e tirinhas,\r\nrelacionando as imagens às palavras e interpretando recursos\r\ngráficos (tipo de balões, letras, onomatopeias).",
          feijo: 0.3625,
          acre: 0.4661,
        },
      ],
    },
    {
      ano: 4,
      turma: "A",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 22,
      faltosos: 2,
      media: 47.0833,
      azuis: 0.55,
      faixas: { insuficiente: 0, regular: 0.45, bom: 0.5, otimo: 0.05 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.45,
          hab: "4N1.4 - Identificar as características do sistema de numeração\r\ndecimal, utilizando a composição e a decomposição de número natural de até a quatro ordens.",
          feijo: 0.3763,
          acre: 0.4328,
        },
        {
          q: 2,
          acerto: 0.32,
          hab: "4N1.2 - Comparar e ordenar números naturais (até a ordem de unidade de milhar) pela compreensão das características do\r\nsistema de numeração decimal (valor posicional e função do\r\nzero).",
          feijo: 0.365,
          acre: 0.5423,
        },
        {
          q: 3,
          acerto: 0.55,
          hab: "4N1.1 - Ler, escrever e comparar números naturais de até a ordem de unidade de milhar.",
          feijo: 0.4563,
          acre: 0.6183,
        },
        {
          q: 4,
          acerto: 0.64,
          hab: "4N1.3 - Construir sequências de números naturais em ordem crescente ou decrescente a partir de um número qualquer,\r\nutilizando uma regularidade estabelecida.",
          feijo: 0.5,
          acre: 0.5892,
        },
        {
          q: 5,
          acerto: 0.5,
          hab: "4N1.5 - Calcular o resultado de adições.",
          feijo: 0.5775,
          acre: 0.6874,
        },
        {
          q: 6,
          acerto: 0.45,
          hab: "4N2.1 - Resolver problemas de subtração com os significados\r\nde separar, retirar, comparar e completar quantidades.",
          feijo: 0.365,
          acre: 0.3908,
        },
        {
          q: 7,
          acerto: 0.64,
          hab: "4N2.2 - Resolver problemas de multiplicação com os\r\nsignificados de adição de parcelas iguais e elementos\r\napresentados em disposição retangular.",
          feijo: 0.5225,
          acre: 0.6871,
        },
        {
          q: 8,
          acerto: 0.45,
          hab: "4M1.5 - Ler horas em relógios digitais e em relógios analógicos.",
          feijo: 0.395,
          acre: 0.5196,
        },
        {
          q: 9,
          acerto: 0.14,
          hab: "4N2.2 - Resolver problemas de divisão de um número natural,\r\ncom os significados de repartição equitativa e de medida.",
          feijo: 0.32,
          acre: 0.4545,
        },
        {
          q: 10,
          acerto: 0.32,
          hab: "4G1.6 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições ou em contornos de faces de sólidos\r\ngeométricos.",
          feijo: 0.4863,
          acre: 0.6703,
        },
        {
          q: 11,
          acerto: 0.55,
          hab: "4E1.2 - Ler e interpretar dados apresentados por meio de tabelas de dupla entrada.",
          feijo: 0.6113,
          acre: 0.6926,
        },
        {
          q: 12,
          acerto: 0.64,
          hab: "4E1.3 - Ler e interpretar dados apresentados por meio de gráficos de barras.",
          feijo: 0.6388,
          acre: 0.8009,
        },
      ],
    },
    {
      ano: 4,
      turma: "B",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 20,
      faltosos: 5,
      media: 43.1818,
      azuis: 0.45,
      faixas: { insuficiente: 0.25, regular: 0.3, bom: 0.25, otimo: 0.2 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.9,
      ortografia: { A: 0.05, B: 0.16, C: 0.16, D: 0.53, E: 0.1 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.65,
          hab: "Localizar informação explícita em um texto.",
          feijo: 0.475,
          acre: 0.6847,
        },
        {
          q: 3,
          acerto: 0.85,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.7963,
          acre: 0.8239,
        },
        {
          q: 4,
          acerto: 0.1,
          hab: "Inferir o sentido de palavras ou expressões.",
          feijo: 0.1375,
          acre: 0.2127,
        },
        { q: 5, acerto: 0.3, hab: "Inferir o assunto de um texto.", feijo: 0.4875, acre: 0.5375 },
        {
          q: 6,
          acerto: 0.1,
          hab: "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
          feijo: 0.2013,
          acre: 0.2515,
        },
        {
          q: 7,
          acerto: 0.45,
          hab: "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
          feijo: 0.3925,
          acre: 0.5322,
        },
        {
          q: 8,
          acerto: 0.6,
          hab: "Interpretar texto com auxílio de material gráfico diverso \r\n(propagandas, quadrinhos, fotos etc.).",
          feijo: 0.6787,
          acre: 0.6991,
        },
        {
          q: 9,
          acerto: 0.6,
          hab: "Inferir informações implícitas em textos.",
          feijo: 0.4525,
          acre: 0.5325,
        },
        {
          q: 10,
          acerto: 0.5,
          hab: "Analisar efeitos de sentido de recursos multissemióticos em\r\ntextos que circulam em diferentes suportes.",
          feijo: 0.52,
          acre: 0.6717,
        },
        {
          q: 11,
          acerto: 0.35,
          hab: "Identificar o uso adequado do ponto final, ponto de interrogação\r\ne de exclamação para compreensão dos efeitos de sentido no\r\ntexto.",
          feijo: 0.3688,
          acre: 0.4318,
        },
        {
          q: 12,
          acerto: 0.25,
          hab: "Construir sentido de história em quadrinhos e tirinhas,\r\nrelacionando as imagens às palavras e interpretando recursos\r\ngráficos (tipo de balões, letras, onomatopeias).",
          feijo: 0.3625,
          acre: 0.4661,
        },
      ],
    },
    {
      ano: 4,
      turma: "B",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 20,
      faltosos: 5,
      media: 46.6667,
      azuis: 0.5,
      faixas: { insuficiente: 0.05, regular: 0.45, bom: 0.4, otimo: 0.1 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.25,
          hab: "4N1.4 - Identificar as características do sistema de numeração\r\ndecimal, utilizando a composição e a decomposição de número natural de até a quatro ordens.",
          feijo: 0.3763,
          acre: 0.4328,
        },
        {
          q: 2,
          acerto: 0.35,
          hab: "4N1.2 - Comparar e ordenar números naturais (até a ordem de unidade de milhar) pela compreensão das características do\r\nsistema de numeração decimal (valor posicional e função do\r\nzero).",
          feijo: 0.365,
          acre: 0.5423,
        },
        {
          q: 3,
          acerto: 0.25,
          hab: "4N1.1 - Ler, escrever e comparar números naturais de até a ordem de unidade de milhar.",
          feijo: 0.4563,
          acre: 0.6183,
        },
        {
          q: 4,
          acerto: 0.4,
          hab: "4N1.3 - Construir sequências de números naturais em ordem crescente ou decrescente a partir de um número qualquer,\r\nutilizando uma regularidade estabelecida.",
          feijo: 0.5,
          acre: 0.5892,
        },
        {
          q: 5,
          acerto: 0.45,
          hab: "4N1.5 - Calcular o resultado de adições.",
          feijo: 0.5775,
          acre: 0.6874,
        },
        {
          q: 6,
          acerto: 0.25,
          hab: "4N2.1 - Resolver problemas de subtração com os significados\r\nde separar, retirar, comparar e completar quantidades.",
          feijo: 0.365,
          acre: 0.3908,
        },
        {
          q: 7,
          acerto: 0.7,
          hab: "4N2.2 - Resolver problemas de multiplicação com os\r\nsignificados de adição de parcelas iguais e elementos\r\napresentados em disposição retangular.",
          feijo: 0.5225,
          acre: 0.6871,
        },
        {
          q: 8,
          acerto: 0.55,
          hab: "4M1.5 - Ler horas em relógios digitais e em relógios analógicos.",
          feijo: 0.395,
          acre: 0.5196,
        },
        {
          q: 9,
          acerto: 0.35,
          hab: "4N2.2 - Resolver problemas de divisão de um número natural,\r\ncom os significados de repartição equitativa e de medida.",
          feijo: 0.32,
          acre: 0.4545,
        },
        {
          q: 10,
          acerto: 0.7,
          hab: "4G1.6 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições ou em contornos de faces de sólidos\r\ngeométricos.",
          feijo: 0.4863,
          acre: 0.6703,
        },
        {
          q: 11,
          acerto: 0.65,
          hab: "4E1.2 - Ler e interpretar dados apresentados por meio de tabelas de dupla entrada.",
          feijo: 0.6113,
          acre: 0.6926,
        },
        {
          q: 12,
          acerto: 0.7,
          hab: "4E1.3 - Ler e interpretar dados apresentados por meio de gráficos de barras.",
          feijo: 0.6388,
          acre: 0.8009,
        },
      ],
    },
    {
      ano: 5,
      turma: "A",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 21,
      faltosos: 2,
      media: 67.3636,
      azuis: 0.43,
      faixas: { insuficiente: 0, regular: 0.57, bom: 0.19, otimo: 0.24 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.86,
      ortografia: { A: 0, B: 0.1, C: 0.19, D: 0.57, E: 0.14 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.81,
          hab: "Localizar informação explícita em um texto.",
          feijo: 0.7838,
          acre: 0.8091,
        },
        {
          q: 3,
          acerto: 0.95,
          hab: "Identificar a ideia central de um texto.",
          feijo: 0.8375,
          acre: 0.8468,
        },
        {
          q: 4,
          acerto: 0.71,
          hab: "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
          feijo: 0.6875,
          acre: 0.6816,
        },
        {
          q: 5,
          acerto: 0.48,
          hab: "Analisar efeitos de sentido decorrentes do uso de advérbios.",
          feijo: 0.46,
          acre: 0.5656,
        },
        {
          q: 6,
          acerto: 0.7,
          hab: "Interpretar texto com auxílio de material gráfico diverso\r\n(propagandas, quadrinhos, foto etc.).",
          feijo: 0.73,
          acre: 0.7875,
        },
        {
          q: 7,
          acerto: 0.81,
          hab: "Inferir uma informação implícita em um texto.",
          feijo: 0.5675,
          acre: 0.6066,
        },
        {
          q: 8,
          acerto: 0.38,
          hab: "Identificar a finalidade de textos de diferentes gêneros.",
          feijo: 0.3138,
          acre: 0.435,
        },
        {
          q: 9,
          acerto: 0.71,
          hab: "Identificar os efeitos de sentido da pontuação e de outras\r\nnotações.",
          feijo: 0.525,
          acre: 0.5794,
        },
        {
          q: 10,
          acerto: 0.67,
          hab: "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
          feijo: 0.6013,
          acre: 0.7055,
        },
        {
          q: 11,
          acerto: 0.81,
          hab: "Inferir o sentido de palavras ou expressões.",
          feijo: 0.5587,
          acre: 0.5858,
        },
        {
          q: 12,
          acerto: 0.38,
          hab: "Analisar relações de causa e consequência entre partes ou\r\nelementos de um texto.",
          feijo: 0.2288,
          acre: 0.4381,
        },
      ],
    },
    {
      ano: 5,
      turma: "A",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 21,
      faltosos: 3,
      media: 61.0833,
      azuis: 0.71,
      faixas: { insuficiente: 0.05, regular: 0.24, bom: 0.38, otimo: 0.33 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.71,
          hab: "5N1.1 - Ler, comparar e ordenar a escrita de números naturais,\r\naté a ordem de milhar.",
          feijo: 0.5975,
          acre: 0.7216,
        },
        {
          q: 2,
          acerto: 0.71,
          hab: "5N1.2 - Identificar a ordem ocupada por um algarismo ou seu\r\nvalor posicional em um número natural de até 4 ordens.",
          feijo: 0.6125,
          acre: 0.6392,
        },
        {
          q: 3,
          acerto: 0.86,
          hab: "5N1.5 - Calcular o resultado de adições de números naturais.",
          feijo: 0.7563,
          acre: 0.8056,
        },
        {
          q: 4,
          acerto: 0.67,
          hab: "5N1.5 - Calcular o resultado de subtrações de números naturais.",
          feijo: 0.45,
          acre: 0.5637,
        },
        {
          q: 5,
          acerto: 0.62,
          hab: "5N2.2 - Resolver situações problema envolvendo diferentes\r\nsignificados da multiplicação: adição de parcelas iguais,\r\norganização retangular.",
          feijo: 0.4612,
          acre: 0.5874,
        },
        {
          q: 6,
          acerto: 0.33,
          hab: "5M2.6 - Resolver problemas que envolvam situações de compra\r\ne venda e formas de pagamento, utilizando termos como troco e\r\ndesconto.",
          feijo: 0.2825,
          acre: 0.3409,
        },
        {
          q: 7,
          acerto: 0.9,
          hab: "5G1.6 - Classificar e comparar figuras planas (triângulo,\r\nquadrado, retângulo, trapézio e paralelogramo) em relação a\r\nseus lados (quantidade, posições relativas e comprimento) e\r\nvértices.",
          feijo: 0.735,
          acre: 0.8226,
        },
        {
          q: 8,
          acerto: 0.57,
          hab: "5N2.1 - Resolver problemas com números naturais envolvendo\r\nadição.",
          feijo: 0.425,
          acre: 0.5591,
        },
        {
          q: 9,
          acerto: 0.24,
          hab: "5M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida não padronizadas e padronizadas mais\r\nusuais (metro, centímetro e milímetro) e diversos instrumentos\r\nde medida.",
          feijo: 0.285,
          acre: 0.4197,
        },
        {
          q: 10,
          acerto: 0.48,
          hab: "5N2.2 - Resolver e elaborar problemas de divisão cujo divisor\r\ntenha no máximo dois algarismos, envolvendo os significados de\r\nrepartição equitativa.",
          feijo: 0.305,
          acre: 0.4073,
        },
        {
          q: 11,
          acerto: 0.76,
          hab: "5E1.2 - Ler, interpretar e analisar dados apresentados em tabelas de dupla entrada.",
          feijo: 0.6763,
          acre: 0.7548,
        },
        {
          q: 12,
          acerto: 0.48,
          hab: "5E1.3 - Ler, interpretar e analisar dados apresentados em gráficos de colunas.",
          feijo: 0.5062,
          acre: 0.6659,
        },
      ],
    },
    {
      ano: 5,
      turma: "B",
      turno: "INTEGRAL",
      disc: "LP",
      participantes: 20,
      faltosos: 3,
      media: 61.8182,
      azuis: 0.85,
      faixas: { insuficiente: 0.1, regular: 0.05, bom: 0.4, otimo: 0.45 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: 0.6,
      ortografia: { A: 0, B: 0.05, C: 0.2, D: 0.35, E: 0.4 },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.9,
          hab: "Localizar informação explícita em um texto.",
          feijo: 0.7838,
          acre: 0.8091,
        },
        {
          q: 3,
          acerto: 0.8,
          hab: "Identificar a ideia central de um texto.",
          feijo: 0.8375,
          acre: 0.8468,
        },
        {
          q: 4,
          acerto: 0.7,
          hab: "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
          feijo: 0.6875,
          acre: 0.6816,
        },
        {
          q: 5,
          acerto: 0.55,
          hab: "Analisar efeitos de sentido decorrentes do uso de advérbios.",
          feijo: 0.46,
          acre: 0.5656,
        },
        {
          q: 6,
          acerto: 0.7,
          hab: "Interpretar texto com auxílio de material gráfico diverso\r\n(propagandas, quadrinhos, foto etc.).",
          feijo: 0.73,
          acre: 0.7875,
        },
        {
          q: 7,
          acerto: 0.65,
          hab: "Inferir uma informação implícita em um texto.",
          feijo: 0.5675,
          acre: 0.6066,
        },
        {
          q: 8,
          acerto: 0.35,
          hab: "Identificar a finalidade de textos de diferentes gêneros.",
          feijo: 0.3138,
          acre: 0.435,
        },
        {
          q: 9,
          acerto: 0.7,
          hab: "Identificar os efeitos de sentido da pontuação e de outras\r\nnotações.",
          feijo: 0.525,
          acre: 0.5794,
        },
        {
          q: 10,
          acerto: 0.7,
          hab: "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
          feijo: 0.6013,
          acre: 0.7055,
        },
        {
          q: 11,
          acerto: 0.65,
          hab: "Inferir o sentido de palavras ou expressões.",
          feijo: 0.5587,
          acre: 0.5858,
        },
        {
          q: 12,
          acerto: 0.1,
          hab: "Analisar relações de causa e consequência entre partes ou\r\nelementos de um texto.",
          feijo: 0.2288,
          acre: 0.4381,
        },
      ],
    },
    {
      ano: 5,
      turma: "B",
      turno: "INTEGRAL",
      disc: "MAT",
      participantes: 20,
      faltosos: 3,
      media: 50.4167,
      azuis: 0.7,
      faixas: { insuficiente: 0.1, regular: 0.2, bom: 0.6, otimo: 0.1 },
      escrita: { A: null, B: null, C1: null, C2: null, C3: null, D: null, E: null },
      alfabeticos: null,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 1,
          acerto: 0.65,
          hab: "5N1.1 - Ler, comparar e ordenar a escrita de números naturais,\r\naté a ordem de milhar.",
          feijo: 0.5975,
          acre: 0.7216,
        },
        {
          q: 2,
          acerto: 0.65,
          hab: "5N1.2 - Identificar a ordem ocupada por um algarismo ou seu\r\nvalor posicional em um número natural de até 4 ordens.",
          feijo: 0.6125,
          acre: 0.6392,
        },
        {
          q: 3,
          acerto: 0.7,
          hab: "5N1.5 - Calcular o resultado de adições de números naturais.",
          feijo: 0.7563,
          acre: 0.8056,
        },
        {
          q: 4,
          acerto: 0.3,
          hab: "5N1.5 - Calcular o resultado de subtrações de números naturais.",
          feijo: 0.45,
          acre: 0.5637,
        },
        {
          q: 5,
          acerto: 0.5,
          hab: "5N2.2 - Resolver situações problema envolvendo diferentes\r\nsignificados da multiplicação: adição de parcelas iguais,\r\norganização retangular.",
          feijo: 0.4612,
          acre: 0.5874,
        },
        {
          q: 6,
          acerto: 0.3,
          hab: "5M2.6 - Resolver problemas que envolvam situações de compra\r\ne venda e formas de pagamento, utilizando termos como troco e\r\ndesconto.",
          feijo: 0.2825,
          acre: 0.3409,
        },
        {
          q: 7,
          acerto: 0.8,
          hab: "5G1.6 - Classificar e comparar figuras planas (triângulo,\r\nquadrado, retângulo, trapézio e paralelogramo) em relação a\r\nseus lados (quantidade, posições relativas e comprimento) e\r\nvértices.",
          feijo: 0.735,
          acre: 0.8226,
        },
        {
          q: 8,
          acerto: 0.55,
          hab: "5N2.1 - Resolver problemas com números naturais envolvendo\r\nadição.",
          feijo: 0.425,
          acre: 0.5591,
        },
        {
          q: 9,
          acerto: 0.15,
          hab: "5M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida não padronizadas e padronizadas mais\r\nusuais (metro, centímetro e milímetro) e diversos instrumentos\r\nde medida.",
          feijo: 0.285,
          acre: 0.4197,
        },
        {
          q: 10,
          acerto: 0.3,
          hab: "5N2.2 - Resolver e elaborar problemas de divisão cujo divisor\r\ntenha no máximo dois algarismos, envolvendo os significados de\r\nrepartição equitativa.",
          feijo: 0.305,
          acre: 0.4073,
        },
        {
          q: 11,
          acerto: 0.65,
          hab: "5E1.2 - Ler, interpretar e analisar dados apresentados em tabelas de dupla entrada.",
          feijo: 0.6763,
          acre: 0.7548,
        },
        {
          q: 12,
          acerto: 0.5,
          hab: "5E1.3 - Ler, interpretar e analisar dados apresentados em gráficos de colunas.",
          feijo: 0.5062,
          acre: 0.6659,
        },
      ],
    },
    {
      ano: 2,
      turma: "ÚNICA",
      turno: "MANHÃ",
      disc: "LP",
      participantes: 12,
      faltosos: 4,
      media: 58.2,
      azuis: 0.58,
      faixas: { insuficiente: 0.25, regular: 0.17, bom: 0.08, otimo: 0.5 },
      escrita: { A: 0, B: 0.25, C1: 0.34, C2: 0.08, C3: 0, D: 0.33, E: 0 },
      alfabeticos: 0.25,
      ortografia: { A: null, B: null, C: null, D: null, E: null },
      redacao: { pouco: null, mediano: null, adequado: null },
      questoes: [
        {
          q: 2,
          acerto: 0.58,
          hab: "Relacionar elementos sonoros das palavras com sua \r\nrepresentação escrita.",
          feijo: 0.4012,
          acre: 0.6728,
        },
        { q: 3, acerto: 0.67, hab: "Ler palavras.", feijo: 0.5188, acre: 0.6471 },
        { q: 4, acerto: 0.58, hab: "Ler frases.", feijo: 0.4, acre: 0.5908 },
        {
          q: 5,
          acerto: 0.5,
          hab: "Reconhecer a finalidade de um texto.",
          feijo: 0.5088,
          acre: 0.6132,
        },
        {
          q: 6,
          acerto: 0.58,
          hab: "Localizar uma informação explícita em um texto.",
          feijo: 0.4438,
          acre: 0.5505,
        },
      ],
    },
  ],
  referencias: {
    "LP-1": {
      feijo: { media: null, azuis: null, alfabeticos: 0.0308, n: 150 },
      acre: { media: null, azuis: null, alfabeticos: 0.0432, n: 7211 },
    },
    "MAT-1": {
      feijo: { media: 47.2, azuis: 0.609, alfabeticos: null, n: 133 },
      acre: { media: 62.4, azuis: 0.7739, alfabeticos: null, n: 5496 },
    },
    "LP-2": {
      feijo: { media: 44.3, azuis: 0.4347, alfabeticos: 0.2697, n: 133 },
      acre: { media: 61.7, azuis: 0.6361, alfabeticos: 0.3139, n: 5591 },
    },
    "MAT-2": {
      feijo: { media: 52.4, azuis: 0.6674, alfabeticos: null, n: 116 },
      acre: { media: 68.8, azuis: 0.8175, alfabeticos: null, n: 5572 },
    },
    "LP-3": {
      feijo: { media: 43.0, azuis: 0.386, alfabeticos: 0.7566, n: 127 },
      acre: { media: 57.1, azuis: 0.6151, alfabeticos: 0.8124, n: 5542 },
    },
    "MAT-3": {
      feijo: { media: 43.1, azuis: 0.4847, alfabeticos: null, n: 137 },
      acre: { media: 58.0, azuis: 0.6706, alfabeticos: null, n: 5716 },
    },
    "LP-4": {
      feijo: { media: 44.3, azuis: 0.4144, alfabeticos: 0.7858, n: 140 },
      acre: { media: 53.6, azuis: 0.588, alfabeticos: 0.8926, n: 5188 },
    },
    "MAT-4": {
      feijo: { media: 46.8, azuis: 0.4654, alfabeticos: null, n: 140 },
      acre: { media: 59.8, azuis: 0.7045, alfabeticos: null, n: 5562 },
    },
    "LP-5": {
      feijo: { media: 57.5, azuis: 0.6151, alfabeticos: 0.7975, n: 153 },
      acre: { media: 64.8, azuis: 0.7434, alfabeticos: 0.9278, n: 5577 },
    },
    "MAT-5": {
      feijo: { media: 50.4, azuis: 0.5349, alfabeticos: null, n: 154 },
      acre: { media: 61.2, azuis: 0.735, alfabeticos: null, n: 5934 },
    },
  },
  habilidades: {
    "MAT-1-1":
      "1N1.1 - Utilizar números naturais como indicador de quantidade\r\nou de ordem em diferentes situações cotidianas.",
    "MAT-2-1": "2N2.4 - Realizar contagem.",
    "MAT-3-1": "3M1.5 - Comparar ou ordenar números naturais de até 3\r\nordens.",
    "MAT-4-1":
      "4N1.4 - Identificar as características do sistema de numeração\r\ndecimal, utilizando a composição e a decomposição de número natural de até a quatro ordens.",
    "MAT-5-1":
      "5N1.1 - Ler, comparar e ordenar a escrita de números naturais,\r\naté a ordem de milhar.",
    "LP-2-2": "Relacionar elementos sonoros das palavras com sua \r\nrepresentação escrita.",
    "LP-3-2": "Localizar informações explícitas em um texto.",
    "LP-4-2": "Localizar informação explícita em um texto.",
    "LP-5-2": "Localizar informação explícita em um texto.",
    "MAT-1-2":
      "1N2.4 - Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos.",
    "MAT-2-2": "2N1.4 - Comparar quantidades de objetos.",
    "MAT-3-2":
      "3M1.6 - Identificar a ordem ocupada por um algarismo ou\r\nseu valor posicional em um número natural.",
    "MAT-4-2":
      "4N1.2 - Comparar e ordenar números naturais (até a ordem de unidade de milhar) pela compreensão das características do\r\nsistema de numeração decimal (valor posicional e função do\r\nzero).",
    "MAT-5-2":
      "5N1.2 - Identificar a ordem ocupada por um algarismo ou seu\r\nvalor posicional em um número natural de até 4 ordens.",
    "LP-2-3": "Ler palavras.",
    "LP-3-3": "Inferir informações em textos verbais.",
    "LP-4-3": "Reconhecer a finalidade de um texto.",
    "LP-5-3": "Identificar a ideia central de um texto.",
    "MAT-1-3":
      "1N1.4 - Comparar quantidades de objetos de dois conjuntos (no\r\nmínimo 20 elementos), por estimativa e/ ou por\r\ncorrespondência (um a um, dois a dois) para indicar “tem mais”,\r\n“tem menos” ou “tem a mesma quantidade.",
    "MAT-2-3":
      "2G2.1 – Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás.",
    "MAT-3-3": "3M1.7 - Calcular o resultado de adições.",
    "MAT-4-3":
      "4N1.1 - Ler, escrever e comparar números naturais de até a ordem de unidade de milhar.",
    "MAT-5-3": "5N1.5 - Calcular o resultado de adições de números naturais.",
    "LP-2-4": "Ler frases.",
    "LP-3-4": "Reconhecer a finalidade de um texto.",
    "LP-4-4": "Inferir o sentido de palavras ou expressões.",
    "LP-5-4": "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
    "MAT-1-4":
      "1G1.2 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições.",
    "MAT-2-4": "2M1.1 - Comparar capacidades com base na comparação visual.",
    "MAT-3-4":
      "3M2.1 - Resolver problemas de adição com os significados\r\nde juntar, acrescentar.",
    "MAT-4-4":
      "4N1.3 - Construir sequências de números naturais em ordem crescente ou decrescente a partir de um número qualquer,\r\nutilizando uma regularidade estabelecida.",
    "MAT-5-4": "5N1.5 - Calcular o resultado de subtrações de números naturais.",
    "LP-2-5": "Reconhecer a finalidade de um texto.",
    "LP-3-5": "Inferir informação em textos que articulam linguagem verbal e não verbal.",
    "LP-4-5": "Inferir o assunto de um texto.",
    "LP-5-5": "Analisar efeitos de sentido decorrentes do uso de advérbios.",
    "MAT-2-5": "2E1.2 - Ler e localizar dados expressos em tabelas simples.",
    "MAT-3-5":
      "3M2.1 - Resolver problemas de subtração com os\r\nsignificados de separar, retirar.",
    "MAT-4-5": "4N1.5 - Calcular o resultado de adições.",
    "MAT-5-5":
      "5N2.2 - Resolver situações problema envolvendo diferentes\r\nsignificados da multiplicação: adição de parcelas iguais,\r\norganização retangular.",
    "LP-2-6": "Localizar uma informação explícita em um texto.",
    "LP-3-6": "Inferir o assunto de cantos, cantigas e canções.",
    "LP-4-6": "Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.",
    "LP-5-6":
      "Interpretar texto com auxílio de material gráfico diverso\r\n(propagandas, quadrinhos, foto etc.).",
    "MAT-2-6":
      "2N2.1 - Resolver problemas com números naturais envolvendo\r\nadição, utilizando estratégias diversas.",
    "MAT-3-6": "3M2.2 - Resolver problemas envolvendo dobro, metade,\r\ntriplo e terça parte.",
    "MAT-4-6":
      "4N2.1 - Resolver problemas de subtração com os significados\r\nde separar, retirar, comparar e completar quantidades.",
    "MAT-5-6":
      "5M2.6 - Resolver problemas que envolvam situações de compra\r\ne venda e formas de pagamento, utilizando termos como troco e\r\ndesconto.",
    "LP-3-7":
      "Identificar o efeito de sentido produzido pelo uso de recursos\r\ngráfico-visuais em textos multissemióticos.",
    "LP-4-7":
      "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
    "LP-5-7": "Inferir uma informação implícita em um texto.",
    "MAT-3-7":
      "3M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida padronizadas.",
    "MAT-4-7":
      "4N2.2 - Resolver problemas de multiplicação com os\r\nsignificados de adição de parcelas iguais e elementos\r\napresentados em disposição retangular.",
    "MAT-5-7":
      "5G1.6 - Classificar e comparar figuras planas (triângulo,\r\nquadrado, retângulo, trapézio e paralelogramo) em relação a\r\nseus lados (quantidade, posições relativas e comprimento) e\r\nvértices.",
    "LP-3-8": "Identificar o assunto de um texto.",
    "LP-4-8":
      "Interpretar texto com auxílio de material gráfico diverso \r\n(propagandas, quadrinhos, fotos etc.).",
    "LP-5-8": "Identificar a finalidade de textos de diferentes gêneros.",
    "MAT-3-8":
      "3M1.4 - Reconhecer unidades de medida e/ou instrumentos\r\nutilizados para medir comprimento, tempo, massa ou\r\ncapacidade.",
    "MAT-4-8": "4M1.5 - Ler horas em relógios digitais e em relógios analógicos.",
    "MAT-5-8": "5N2.1 - Resolver problemas com números naturais envolvendo\r\nadição.",
    "LP-3-9":
      "Identificar o uso do ponto final, ponto de interrogação e ponto de\r\nexclamação para compreensão dos efeitos de sentido no texto.",
    "LP-4-9": "Inferir informações implícitas em textos.",
    "LP-5-9": "Identificar os efeitos de sentido da pontuação e de outras\r\nnotações.",
    "MAT-3-9":
      "3G1.3 - Identificar e nomear figuras planas (círculo,\r\nquadrado, retângulo e triângulo).",
    "MAT-4-9":
      "4N2.2 - Resolver problemas de divisão de um número natural,\r\ncom os significados de repartição equitativa e de medida.",
    "MAT-5-9":
      "5M1.2 - Estimar, medir e comparar comprimentos, utilizando\r\nunidades de medida não padronizadas e padronizadas mais\r\nusuais (metro, centímetro e milímetro) e diversos instrumentos\r\nde medida.",
    "LP-3-10":
      "Identificar o conflito gerador e sua resolução, além de palavras, expressões e frases que caracterizem personagens e ambientes\r\nda narrativa.",
    "LP-4-10":
      "Analisar efeitos de sentido de recursos multissemióticos em\r\ntextos que circulam em diferentes suportes.",
    "LP-5-10":
      "Recuperar relações entre partes de um texto, identificando\r\nsubstituições lexicais ou pronominais que contribuem para a sua\r\ncontinuidade.",
    "MAT-3-10": "3E1.2 - Ler dados expressos em gráficos de colunas\r\nsimples.",
    "MAT-4-10":
      "4G1.6 - Identificar e nomear figuras planas (círculo, quadrado,\r\nretângulo e triângulo) em desenhos apresentados em\r\ndiferentes disposições ou em contornos de faces de sólidos\r\ngeométricos.",
    "MAT-5-10":
      "5N2.2 - Resolver e elaborar problemas de divisão cujo divisor\r\ntenha no máximo dois algarismos, envolvendo os significados de\r\nrepartição equitativa.",
    "LP-4-11":
      "Identificar o uso adequado do ponto final, ponto de interrogação\r\ne de exclamação para compreensão dos efeitos de sentido no\r\ntexto.",
    "LP-5-11": "Inferir o sentido de palavras ou expressões.",
    "MAT-4-11":
      "4E1.2 - Ler e interpretar dados apresentados por meio de tabelas de dupla entrada.",
    "MAT-5-11":
      "5E1.2 - Ler, interpretar e analisar dados apresentados em tabelas de dupla entrada.",
    "LP-4-12":
      "Construir sentido de história em quadrinhos e tirinhas,\r\nrelacionando as imagens às palavras e interpretando recursos\r\ngráficos (tipo de balões, letras, onomatopeias).",
    "LP-5-12":
      "Analisar relações de causa e consequência entre partes ou\r\nelementos de um texto.",
    "MAT-4-12": "4E1.3 - Ler e interpretar dados apresentados por meio de gráficos de barras.",
    "MAT-5-12": "5E1.3 - Ler, interpretar e analisar dados apresentados em gráficos de colunas.",
  },
} as DadosI;
