import type { Questao } from "@/components/school/ferramentas/quiz";
import type { AtividadeBanco } from "@/lib/recomposicao/banco-tipos";

/** Questão com a resposta certa na 1ª opção (a tela embaralha antes de mostrar). */
const q = (id: string, enunciado: string, opcoes: string[], explicacao: string): Questao => ({
  id,
  enunciado,
  opcoes,
  respostaCorreta: 0,
  explicacao,
});

/**
 * Português: atividades para as habilidades com menos acertos na
 * II Avaliação Diagnóstica 2026. Todos os textos são autorais, escritos
 * para a faixa etária.
 */
export const BANCO_LP: AtividadeBanco[] = [
  {
    id: "lp-conectivos",
    disc: "LP",
    series: [4, 5],
    titulo: "Palavras que ligam ideias: porque, mas, então",
    emoji: "🔗",
    conteudo: "Coesão e conectivos",
    habilidades: ["Relacoes logico-discursivas (conjuncoes, adverbios)"],
    niveis: {
      retomada: {
        texto: {
          titulo: "Dica",
          paragrafos: [
            "🔗 PORQUE explica o motivo. Ex.: Levei guarda-chuva porque ia chover.",
            "↔️ MAS mostra uma ideia contrária. Ex.: Estudei, mas esqueci a resposta.",
            "➡️ ENTÃO mostra o resultado. Ex.: Choveu muito, então o jogo acabou.",
          ],
        },
        questoes: [
          q("r1", "Complete: Fiquei com fome ___ não almocei.", ["porque", "mas", "então"], "Não almoçar é o MOTIVO da fome: usamos porque."),
          q("r2", "Complete: O dia estava lindo, ___ Pedro não quis sair.", ["mas", "porque", "então"], "Uma ideia contrária à outra: usamos mas."),
          q("r3", "Complete: O ônibus atrasou, ___ cheguei tarde.", ["então", "mas", "porque"], "Chegar tarde é o RESULTADO do atraso: usamos então."),
          q("r4", "Complete: Corri muito, ___ perdi o ônibus.", ["mas", "porque", "então"], "Correr e mesmo assim perder: são ideias contrárias."),
          q("r5", "Complete: Acabou a merenda, ___ a turma ficou com fome.", ["então", "mas", "porque"], "A fome é o RESULTADO da merenda acabar."),
          q("r6", "Complete: Ela faltou à aula ___ estava doente.", ["porque", "mas", "então"], "A doença é o MOTIVO da falta."),
          q("r7", "Complete: O caderno é pequeno, ___ cabe tudo nele.", ["mas", "porque", "então"], "Ser pequeno e mesmo assim caber tudo: ideias que se opõem."),
          q("r8", "Complete: Esqueci o casaco, ___ fiquei com frio.", ["então", "porque", "mas"], "O frio é o resultado de esquecer o casaco."),
          q("r9", "Complete: Gosto de ler ___ as histórias me divertem.", ["porque", "mas", "então"], "A diversão é o motivo de gostar de ler."),
          q("r10", "Qual palavra sempre apresenta um MOTIVO?", ["porque", "mas", "então"], "Porque responde à pergunta “por quê?”."),
        ],
      },
      pratica: {
        texto: {
          titulo: "A horta da escola",
          paragrafos: [
            "A turma plantou alface na horta da escola. Todos regavam as mudas, mas uma semana choveu forte e algumas folhas estragaram.",
            "Como a turma não desistiu, replantou tudo. Por isso, no fim do mês, a merenda teve salada fresquinha.",
          ],
        },
        questoes: [
          q("p1", "Na frase “Todos regavam as mudas, MAS uma semana choveu forte”, a palavra MAS indica:", ["uma ideia contrária ao que se esperava", "o motivo de algo", "o tempo em que aconteceu", "um lugar"], "Mas liga duas ideias que se opõem: cuidavam bem, porém algo deu errado."),
          q("p2", "“POR ISSO, no fim do mês, a merenda teve salada.” A expressão POR ISSO indica:", ["uma consequência", "uma dúvida", "uma comparação", "um lugar"], "Por isso apresenta o resultado do que veio antes."),
          q("p3", "“COMO a turma não desistiu, replantou tudo.” Aqui, COMO tem o sentido de:", ["porque", "igual a", "quando", "mas"], "Neste caso, como = porque: explica o motivo."),
          q("p4", "Qual palavra poderia substituir MAS sem mudar o sentido?", ["porém", "porque", "então", "quando"], "Porém, contudo e entretanto têm o mesmo sentido de mas."),
          q("p5", "“A turma plantou alface na horta.” Se quiséssemos acrescentar o motivo, começaríamos com:", ["porque", "mas", "então", "quando"], "Porque introduz a causa."),
          q("p6", "“Algumas folhas estragaram, ___ a turma replantou tudo.” Qual conectivo cabe?", ["mas", "porque", "pois", "já que"], "Estragar e ainda assim replantar: oposição."),
          q("p7", "No 2º parágrafo, “Por isso” poderia ser trocado por:", ["portanto", "embora", "apesar de", "porque"], "Por isso e portanto indicam consequência."),
          q("p8", "Qual frase do texto mostra uma CONSEQUÊNCIA?", ["a merenda teve salada fresquinha", "a turma plantou alface", "todos regavam as mudas", "choveu forte"], "A salada é o resultado de replantar."),
          q("p9", "Se o texto dissesse “Choveu forte, PORQUE as folhas estragaram”, o sentido ficaria:", ["errado, porque inverte causa e consequência", "igual ao original", "mais claro", "mais bonito"], "A chuva causou o estrago, e não o contrário."),
          q("p10", "Os conectivos servem no texto para:", ["ligar as ideias e mostrar a relação entre elas", "aumentar o número de palavras", "deixar o texto mais difícil", "separar os parágrafos"], "Eles costuram as ideias umas nas outras."),
        ],
      },
      desafio: {
        texto: {
          titulo: "O campeonato",
          paragrafos: [
            "Embora o time da escola fosse o menor do campeonato, chegou à final. Os jogadores treinavam todos os dias; além disso, estudavam as jogadas dos adversários.",
            "No dia da final, porém, o goleiro torceu o pé. Mesmo assim, o reserva entrou e defendeu um pênalti. Portanto, a taça ficou com a escola.",
          ],
        },
        questoes: [
          q("d1", "“EMBORA o time fosse o menor, chegou à final.” EMBORA indica:", ["uma ideia contrária, que não impediu o resultado", "o motivo da vitória", "o lugar do jogo", "o tempo do jogo"], "Embora = apesar de: ser pequeno não impediu de chegar à final."),
          q("d2", "“ALÉM DISSO, estudavam as jogadas.” A expressão acrescenta:", ["mais uma informação", "uma oposição", "uma conclusão", "uma dúvida"], "Além disso soma uma ideia à anterior."),
          q("d3", "A palavra PORTANTO, no fim do texto, introduz:", ["a conclusão", "uma causa", "uma comparação", "uma pergunta"], "Portanto apresenta a conclusão: a escola ganhou."),
          q("d4", "Qual expressão tem o MESMO sentido de “mesmo assim”?", ["ainda assim", "por causa disso", "além disso", "por exemplo"], "Mesmo assim = ainda assim: apesar do problema, algo aconteceu."),
          q("d5", "“Os jogadores treinavam todos os dias; ALÉM DISSO, estudavam as jogadas.” Se trocássemos por “MAS”, o sentido:", ["mudaria, virando oposição em vez de soma", "ficaria igual", "ficaria mais claro", "sumiria"], "Além disso soma; mas opõe."),
          q("d6", "“No dia da final, PORÉM, o goleiro torceu o pé.” Porém indica:", ["um problema inesperado, contrário ao esperado", "o motivo da final", "o horário do jogo", "a conclusão do texto"], "Porém tem o mesmo valor de mas."),
          q("d7", "Qual conectivo poderia substituir EMBORA no início do texto?", ["apesar de", "por isso", "porque", "logo"], "Embora e apesar de indicam concessão."),
          q("d8", "A ordem “treino → estudo das jogadas → final → taça” é mostrada no texto por meio de:", ["conectivos de adição e de conclusão", "apenas de vírgulas", "perguntas", "onomatopeias"], "Além disso soma; portanto conclui."),
          q("d9", "Se o texto terminasse com “PORTANTO, o time perdeu”, haveria:", ["uma contradição com o que foi contado antes", "uma boa conclusão", "uma nova causa", "nenhuma mudança"], "Portanto anuncia conclusão coerente com o que veio antes."),
          q("d10", "O conectivo MESMO ASSIM, no texto, liga:", ["a lesão do goleiro ao bom desempenho do reserva", "o treino ao estudo", "a taça à escola", "o time ao campeonato"], "Apesar do problema, o reserva defendeu o pênalti."),
        ],
      },
    },
    emSala: [
      "Faça cartões com PORQUE, MAS, ENTÃO, POR ISSO e EMBORA; a turma completa frases do cotidiano escolhendo o cartão.",
      "Peça que reescrevam um parágrafo trocando o conectivo por outro de mesmo sentido.",
      "Leia frases com o conectivo errado (“Choveu, porque o jogo acabou”) e deixe a turma achar o erro.",
    ],
  },
  {
    id: "lp-pontuacao",
    disc: "LP",
    series: [3, 4, 5],
    titulo: "A pontuação muda o sentido",
    emoji: "❗",
    conteudo: "Pontuação e efeitos de sentido",
    habilidades: [
      "Efeitos de sentido da pontuacao e outras notacoes",
      "Uso do ponto final, interrogacao e exclamacao (efeitos de sentido)",
    ],
    niveis: {
      retomada: {
        texto: {
          titulo: "Os sinais",
          paragrafos: [
            "⏺️ Ponto final (.) termina uma frase que informa.",
            "❓ Ponto de interrogação (?) faz uma pergunta.",
            "❗ Ponto de exclamação (!) mostra emoção: alegria, susto, raiva.",
          ],
        },
        questoes: [
          q("r1", "Qual frase é uma PERGUNTA?", ["Você vem amanhã?", "Você vem amanhã.", "Que legal!"], "A pergunta termina com ponto de interrogação (?)."),
          q("r2", "Qual frase mostra SUSTO ou ALEGRIA?", ["Ganhamos o jogo!", "O jogo acabou.", "Quem ganhou o jogo?"], "O ponto de exclamação mostra emoção."),
          q("r3", "“Hoje é sexta-feira.” Essa frase:", ["dá uma informação", "faz uma pergunta", "mostra um grito"], "O ponto final encerra uma frase que informa."),
          q("r4", "Qual frase dá uma INFORMAÇÃO?", ["A prova é na terça.", "A prova é na terça?", "Que prova difícil!"], "O ponto final encerra frases que informam."),
          q("r5", "Qual sinal usamos no fim de “Cuidado com o degrau”?", ["ponto de exclamação (!)", "ponto de interrogação (?)", "ponto final (.)"], "É um aviso forte: pede exclamação."),
          q("r6", "“Onde fica a biblioteca” precisa de qual sinal?", ["ponto de interrogação (?)", "ponto final (.)", "ponto de exclamação (!)"], "É uma pergunta."),
          q("r7", "Para que serve a vírgula em “Comprei pão, leite e ovos”?", ["separar os itens da lista", "fazer uma pergunta", "mostrar susto"], "A vírgula separa uma enumeração."),
          q("r8", "Qual frase mostra RAIVA ou SUSTO?", ["Saia já daí!", "Ele saiu de lá.", "Quem saiu de lá?"], "O ponto de exclamação carrega a emoção."),
          q("r9", "Depois do ponto final, a próxima palavra começa com:", ["letra maiúscula", "letra minúscula", "número"], "Frase nova, letra maiúscula."),
          q("r10", "Os dois-pontos (:) costumam vir antes de:", ["uma lista ou uma fala", "um ponto final", "uma vírgula"], "Eles anunciam o que vem em seguida."),
        ],
      },
      pratica: {
        texto: {
          titulo: "O bilhete",
          paragrafos: [
            "Mãe, a professora avisou: amanhã tem passeio!",
            "Posso ir? Precisa levar lanche, garrafinha e boné.",
            "Estou tão animado!!!",
          ],
        },
        questoes: [
          q("p1", "No bilhete, os DOIS-PONTOS em “a professora avisou:” servem para:", ["anunciar o que a professora disse", "fazer uma pergunta", "terminar o bilhete", "mostrar raiva"], "Os dois-pontos anunciam uma fala, uma explicação ou uma lista."),
          q("p2", "As vírgulas em “lanche, garrafinha e boné” servem para:", ["separar os itens de uma lista", "mostrar dúvida", "indicar uma pergunta", "encerrar a frase"], "A vírgula separa elementos de uma enumeração."),
          q("p3", "Por que a criança usou três pontos de exclamação (!!!)?", ["para mostrar que está muito animada", "para fazer uma pergunta", "porque errou", "para separar palavras"], "Repetir a exclamação reforça a emoção."),
          q("p4", "“Posso ir?” O ponto de interrogação mostra que a criança:", ["está pedindo permissão", "está dando uma ordem", "está brava", "terminou o bilhete"], "É uma pergunta: ela pede autorização à mãe."),
          q("p5", "Por que “Mãe” aparece separado por vírgula no começo do bilhete?", ["porque é a pessoa a quem a criança se dirige", "porque é o nome do lugar", "porque começa uma lista", "por engano"], "A vírgula isola o vocativo (quem é chamado)."),
          q("p6", "Se trocássemos “Posso ir?” por “Posso ir.”, a frase passaria a:", ["afirmar em vez de perguntar", "continuar igual", "virar um grito", "virar uma lista"], "O sinal muda o tipo de frase."),
          q("p7", "Qual parte do bilhete é uma LISTA?", ["lanche, garrafinha e boné", "Mãe", "Posso ir?", "Estou tão animado"], "Os três itens estão separados por vírgula e “e”."),
          q("p8", "O bilhete começa com “Mãe,”. Isso mostra que o texto:", ["é dirigido a uma pessoa específica", "é uma notícia de jornal", "é uma receita", "não tem destinatário"], "O vocativo revela o interlocutor."),
          q("p9", "Se o bilhete não tivesse nenhum sinal de pontuação, a leitura ficaria:", ["confusa, sem saber onde cada ideia termina", "mais rápida e clara", "igual", "mais bonita"], "A pontuação organiza as pausas e o sentido."),
          q("p10", "“amanhã tem passeio!” A exclamação aqui mostra:", ["a animação da criança com a notícia", "uma dúvida", "uma ordem", "o fim do bilhete"], "A emoção da criança aparece no sinal."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Duas frases, dois sentidos",
          paragrafos: [
            "Frase 1: — Vamos comer, crianças!",
            "Frase 2: — Vamos comer crianças!",
            "Frase 3: O quê?! Você pintou o cachorro de azul...",
          ],
        },
        questoes: [
          q("d1", "Na Frase 1, a vírgula mostra que:", ["as crianças estão sendo chamadas para comer", "as crianças serão comidas", "é uma pergunta", "não há diferença"], "A vírgula separa o chamado (crianças). Sem ela, o sentido muda totalmente!"),
          q("d2", "Qual é a diferença entre a Frase 1 e a Frase 2?", ["a falta da vírgula muda o sentido da frase", "a Frase 2 é uma pergunta", "não existe diferença", "a Frase 1 está errada"], "Sem a vírgula, “crianças” vira o que vai ser comido."),
          q("d3", "Em “O quê?!”, os sinais juntos mostram:", ["surpresa e espanto", "calma", "uma ordem", "uma lista"], "Interrogação + exclamação = pergunta cheia de espanto."),
          q("d4", "As reticências (...) no fim da Frase 3 sugerem que:", ["a pessoa ficou sem palavras, pensando", "a frase é uma pergunta", "a frase terminou normalmente", "há uma lista"], "Reticências indicam pausa, hesitação ou algo que ficou no ar."),
          q("d5", "Em “Vamos comer, crianças!”, quem fala está:", ["chamando as crianças para a mesa", "dizendo o que vai comer", "fazendo uma pergunta", "pedindo desculpa"], "A vírgula marca o chamado."),
          q("d6", "Onde colocar a vírgula em “Não espere” para virar um pedido de esperar?", ["Não, espere", "Não espere,", "Não espere", "não dá para mudar"], "“Não, espere” muda completamente o sentido."),
          q("d7", "As reticências e o ponto de exclamação juntos costumam indicar:", ["emoção somada a uma ideia inacabada", "uma lista", "uma pergunta simples", "o fim de um documento"], "Os sinais se somam para dar o tom."),
          q("d8", "Na Frase 3, “Você pintou o cachorro de azul...”, o que fica subentendido?", ["a pessoa está sem palavras diante do que vê", "a pessoa vai pintar também", "a frase foi cortada por engano", "o cachorro é azul de nascença"], "As reticências deixam a reação no ar."),
          q("d9", "Qual mudança de pontuação transformaria a Frase 2 na Frase 1?", ["acrescentar uma vírgula antes de “crianças”", "tirar a exclamação", "acrescentar reticências", "trocar por interrogação"], "Uma vírgula muda quem come e quem é comido."),
          q("d10", "O que essas três frases ensinam sobre a pontuação?", ["que ela muda o sentido, e não é só enfeite", "que ela serve só para deixar bonito", "que pode ser usada de qualquer jeito", "que só vale em poesia"], "Pontuar é parte do significado do texto."),
        ],
      },
    },
    emSala: [
      "Leia a mesma frase em voz alta com ponto final, interrogação e exclamação; a turma adivinha qual sinal foi usado.",
      "Proponha a “caça ao sentido”: frases famosas com e sem vírgula (“Não, espere!” × “Não espere!”).",
      "Reescrita coletiva de uma tirinha, pontuando as falas dos balões.",
    ],
  },
  {
    id: "lp-causa-consequencia",
    disc: "LP",
    series: [5],
    titulo: "Por que aconteceu? (causa e consequência)",
    emoji: "🎯",
    conteudo: "Compreensão de texto",
    habilidades: ["Relacao de causa e consequencia entre partes do texto"],
    niveis: {
      retomada: {
        texto: {
          titulo: "Lembre",
          paragrafos: ["CAUSA é o motivo: por que aconteceu.", "CONSEQUÊNCIA é o resultado: o que aconteceu depois."],
        },
        questoes: [
          q("r1", "“A planta morreu porque ninguém regou.” Qual é a CAUSA?", ["ninguém regou", "a planta morreu", "a planta era bonita"], "O motivo (causa) foi a falta de água."),
          q("r2", "“Choveu muito e a rua alagou.” Qual é a CONSEQUÊNCIA da chuva?", ["a rua alagou", "choveu muito", "o sol apareceu"], "A rua alagar é o resultado da chuva."),
          q("r3", "“Lia estudou bastante, por isso tirou nota boa.” Por que Lia tirou nota boa?", ["porque estudou bastante", "porque tinha sorte", "porque a prova era fácil"], "Estudar foi a causa da nota boa."),
          q("r4", "“O copo quebrou porque caiu no chão.” Qual é a CAUSA?", ["cair no chão", "o copo quebrar", "o chão ser duro"], "O motivo da quebra foi a queda."),
          q("r5", "“Faltou energia, então a geladeira desligou.” Qual é a CONSEQUÊNCIA?", ["a geladeira desligou", "faltou energia", "a comida estragou"], "O desligamento é o resultado."),
          q("r6", "“Davi correu muito e ficou cansado.” Por que Davi ficou cansado?", ["porque correu muito", "porque dormiu pouco", "porque bebeu água"], "Correr foi a causa do cansaço."),
          q("r7", "“Como estava frio, vesti o casaco.” Qual é a causa?", ["estar frio", "vestir o casaco", "o casaco ser novo"], "O frio motivou vestir o casaco."),
          q("r8", "Na frase “Estudei, por isso passei”, a expressão POR ISSO anuncia:", ["a consequência", "a causa", "o lugar"], "Por isso apresenta o resultado."),
          q("r9", "“A rua alagou porque o bueiro estava entupido.” O que veio PRIMEIRO?", ["o bueiro entupido", "a rua alagada", "a chuva parar"], "A causa vem antes da consequência."),
          q("r10", "Qual pergunta ajuda a achar a CAUSA num texto?", ["por que isso aconteceu?", "o que aconteceu depois?", "onde aconteceu?"], "“Por quê?” procura o motivo."),
        ],
      },
      pratica: {
        texto: {
          titulo: "O rio que secou",
          paragrafos: [
            "Durante meses não choveu na região. O rio foi baixando até que os barcos não conseguiram mais navegar.",
            "Sem os barcos, os alimentos demoraram a chegar à cidade, e os preços no mercado subiram.",
          ],
        },
        questoes: [
          q("p1", "Por que os barcos não conseguiram navegar?", ["porque o rio baixou muito", "porque os preços subiram", "porque a cidade cresceu", "porque os barcos quebraram"], "A seca baixou o rio: essa é a causa."),
          q("p2", "Qual foi a consequência de os alimentos demorarem a chegar?", ["os preços subiram", "voltou a chover", "o rio encheu", "os barcos voltaram"], "Com menos comida chegando, o preço aumentou."),
          q("p3", "O que começou toda a sequência de problemas?", ["a falta de chuva", "o preço alto", "o mercado fechado", "os barcos"], "Tudo começou com meses sem chuva."),
          q("p4", "Complete a relação: sem chuva → rio baixo → ___ → preços altos.", ["barcos parados", "rio cheio", "festa na cidade", "mais peixes"], "Cada fato é consequência do anterior."),
          q("p5", "Qual foi a consequência de o rio baixar?", ["os barcos não puderam navegar", "choveu na região", "a cidade cresceu", "os preços caíram"], "Sem profundidade, os barcos pararam."),
          q("p6", "Se tivesse chovido normalmente, o que provavelmente NÃO teria acontecido?", ["a alta dos preços no mercado", "a chegada dos alimentos", "a navegação dos barcos", "a existência do rio"], "Sem a seca, a corrente de problemas não começaria."),
          q("p7", "No texto, “Sem os barcos” introduz:", ["a causa do atraso dos alimentos", "o lugar da história", "uma opinião do autor", "o fim do texto"], "A falta de barcos causou o atraso."),
          q("p8", "Quantos elos tem a corrente de causas do texto?", ["quatro: sem chuva, rio baixo, barcos parados, preços altos", "dois", "um", "seis"], "Cada fato puxa o seguinte."),
          q("p9", "Quem mais sofre com a alta dos preços, segundo o que o texto sugere?", ["as pessoas da cidade que compram no mercado", "os peixes do rio", "os donos dos barcos apenas", "ninguém"], "Se os preços sobem, quem compra é afetado."),
          q("p10", "O texto mostra que um problema da natureza pode:", ["afetar a vida e a economia das pessoas", "resolver-se sozinho sempre", "não ter nenhuma consequência", "acontecer só no inverno"], "A seca chegou até o preço do mercado."),
        ],
      },
      desafio: {
        texto: {
          titulo: "A campanha do óleo",
          paragrafos: [
            "Na cozinha da escola, o óleo usado era jogado na pia. Com o tempo, o cano entupiu e a água suja voltou pelo ralo.",
            "A turma do 5º ano pesquisou o problema e descobriu que um litro de óleo pode poluir milhares de litros de água. Então, criou uma campanha: o óleo passou a ser guardado em garrafas e levado para fazer sabão.",
            "Desde então, o cano não entupiu mais, e a escola ainda ganhou sabão para a limpeza.",
          ],
        },
        questoes: [
          q("d1", "Qual foi a CAUSA do entupimento do cano?", ["o óleo jogado na pia", "a campanha da turma", "o sabão", "a água limpa"], "O óleo na pia entupiu o cano."),
          q("d2", "O que levou a turma a criar a campanha?", ["a descoberta de que o óleo polui muita água", "a falta de sabão", "o pedido de um vizinho", "a chuva forte"], "A pesquisa mostrou o tamanho do problema: por isso a campanha."),
          q("d3", "Quais foram as CONSEQUÊNCIAS da campanha?", ["o cano parou de entupir e a escola ganhou sabão", "o cano entupiu mais", "a cozinha fechou", "a água ficou mais suja"], "A campanha trouxe dois resultados bons."),
          q("d4", "A palavra ENTÃO, no segundo parágrafo, liga:", ["a descoberta ao que a turma decidiu fazer", "duas ideias contrárias", "dois lugares", "uma pergunta à resposta"], "Então introduz a consequência da descoberta."),
          q("d5", "Por que a água suja voltou pelo ralo?", ["porque o cano entupido não deixava a água escoar", "porque choveu muito", "porque faltou sabão", "porque a pia era velha"], "O entupimento foi a causa."),
          q("d6", "A pesquisa da turma foi causa de quê?", ["da criação da campanha do óleo", "do entupimento do cano", "da chuva na cidade", "da falta de sabão"], "Saber do problema motivou a ação."),
          q("d7", "Qual é o encadeamento correto dos fatos?", ["óleo na pia → cano entupido → pesquisa → campanha → cano limpo", "campanha → óleo na pia → cano entupido", "cano limpo → óleo na pia → pesquisa", "pesquisa → cano entupido → óleo na pia"], "Cada etapa causa a seguinte."),
          q("d8", "O sabão produzido pela escola é:", ["uma consequência positiva e inesperada da campanha", "a causa do entupimento", "o motivo da pesquisa", "um problema novo"], "Além de resolver, a campanha trouxe um ganho extra."),
          q("d9", "Se a turma não tivesse agido, o mais provável seria:", ["o cano continuar entupindo", "o cano se desentupir sozinho", "a escola ganhar sabão mesmo assim", "o óleo deixar de poluir"], "Sem mudar a causa, a consequência se repetiria."),
          q("d10", "Que lição sobre causa e consequência o texto ensina?", ["para resolver um problema é preciso agir sobre a sua causa", "basta limpar o cano toda semana", "problemas se resolvem sozinhos", "óleo não polui a água"], "A turma atacou a origem do problema."),
        ],
      },
    },
    emSala: [
      "Monte com a turma uma “corrente de causas” com tiras de papel: cada tira é um fato ligado ao anterior.",
      "Use notícias locais (enchente, seca do rio) e pergunte: por que aconteceu? e o que aconteceu depois?",
      "Peça que o aluno sublinhe a causa de uma cor e a consequência de outra.",
    ],
  },
  {
    id: "lp-texto-imagem",
    disc: "LP",
    series: [3, 4, 5],
    titulo: "Texto com imagem: tirinhas, cartazes e propagandas",
    emoji: "🖼️",
    conteudo: "Leitura multimodal",
    habilidades: [
      "Interpretar texto com material grafico (propagandas, quadrinhos, fotos)",
      "Construir sentido de HQs e tirinhas (baloes, onomatopeias)",
    ],
    niveis: {
      retomada: {
        texto: {
          titulo: "Na tirinha",
          paragrafos: [
            "💬 Balão redondo: a personagem está FALANDO.",
            "💭 Balão de nuvem: a personagem está PENSANDO.",
            "💥 POW! CRASH! TRIM! são onomatopeias: palavras que imitam sons.",
          ],
        },
        questoes: [
          q("r1", "O balão em forma de nuvem 💭 mostra que a personagem está:", ["pensando", "gritando", "dormindo"], "Balão de nuvem = pensamento."),
          q("r2", "“TRIM! TRIM!” imita o som de:", ["um telefone ou despertador tocando", "um cachorro latindo", "a chuva caindo"], "É uma onomatopeia de toque de telefone ou despertador."),
          q("r3", "Um balão com bordas em zigue-zague ⚡ geralmente mostra:", ["um grito", "um cochicho", "um pensamento"], "Bordas tremidas ou pontudas indicam grito ou som forte."),
          q("r4", "O balão redondo 💬 mostra que a personagem está:", ["falando", "pensando", "dormindo"], "Balão redondo = fala."),
          q("r5", "“SPLASH!” imita o som de:", ["algo caindo na água", "uma porta batendo", "um passarinho"], "É a onomatopeia de água."),
          q("r6", "Numa tirinha, os quadros devem ser lidos:", ["da esquerda para a direita, em ordem", "de trás para a frente", "só o último"], "A leitura segue a ordem dos quadrinhos."),
          q("r7", "Um balão com vários bicos apontando para fora indica geralmente:", ["um grito ou som muito alto", "um sussurro", "um sonho"], "Formato do balão indica o tom de voz."),
          q("r8", "Numa tirinha, quem conta a história é:", ["a imagem junto com o texto", "só o texto", "só o título"], "Na linguagem multimodal, imagem e texto se completam."),
          q("r9", "“ZZZZZ” dentro de um balão significa que a personagem está:", ["dormindo", "correndo", "com raiva"], "É a onomatopeia do ronco."),
          q("r10", "A expressão do rosto da personagem serve para mostrar:", ["o que ela está sentindo", "a hora do dia", "o nome dela"], "O desenho comunica emoção."),
        ],
      },
      pratica: {
        texto: {
          titulo: "Tirinha (descrita)",
          paragrafos: [
            "Quadro 1: Nina olha para o céu escuro. Balão de pensamento: “Será que vai chover?”",
            "Quadro 2: Ela sai sem guarda-chuva, assobiando.",
            "Quadro 3: CABRUM! Nina aparece encharcada, com a cara emburrada.",
          ],
        },
        questoes: [
          q("p1", "No quadro 1, Nina está:", ["pensando se vai chover", "falando com a mãe", "gritando", "dormindo"], "O balão é de pensamento."),
          q("p2", "“CABRUM!” representa o som de:", ["um trovão", "uma porta", "um carro", "uma risada"], "É a onomatopeia do trovão."),
          q("p3", "Por que Nina aparece emburrada no último quadro?", ["porque se molhou por não levar guarda-chuva", "porque ganhou um presente", "porque estava com sono", "porque o sol saiu"], "A imagem (encharcada) e a sequência explicam a reação."),
          q("p4", "O humor da tirinha vem de:", ["Nina desconfiar da chuva e mesmo assim sair sem guarda-chuva", "Nina gostar de chuva", "o céu estar azul", "Nina estar em casa"], "O leitor percebe antes dela o que vai acontecer."),
          q("p5", "Qual quadro mostra a CONSEQUÊNCIA da escolha de Nina?", ["o quadro 3", "o quadro 1", "o quadro 2", "nenhum"], "Sair sem guarda-chuva a deixou encharcada."),
          q("p6", "No quadro 2, o assobio sugere que Nina está:", ["despreocupada", "com medo", "com pressa", "chorando"], "Assobiar indica tranquilidade."),
          q("p7", "Qual pista do quadro 1 já avisa o leitor do que vai acontecer?", ["o céu escuro", "o assobio", "a cara emburrada", "o guarda-chuva"], "O céu escuro anuncia a chuva."),
          q("p8", "A tirinha conta a história usando:", ["imagens e texto juntos", "só imagens", "só texto", "só sons"], "É um texto multimodal."),
          q("p9", "Se o quadro 3 fosse retirado, a tirinha perderia:", ["o desfecho e a graça", "o começo", "os personagens", "o cenário"], "O último quadro traz a virada."),
          q("p10", "O que Nina provavelmente aprendeu?", ["a levar guarda-chuva quando desconfia da chuva", "a não olhar para o céu", "a assobiar melhor", "a correr mais rápido"], "A consequência ensina a lição."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Cartaz da campanha",
          paragrafos: [
            "Imagem: um mosquito gigante com um X vermelho por cima.",
            "Texto grande: “10 MINUTOS CONTRA O MOSQUITO”.",
            "Texto pequeno: “Uma vez por semana, olhe vasos, pneus e garrafas. Água parada é casa de mosquito. Secretaria de Saúde.”",
          ],
        },
        questoes: [
          q("d1", "Qual é o objetivo principal do cartaz?", ["convencer as pessoas a eliminar água parada", "vender um produto", "contar uma história", "ensinar a desenhar mosquitos"], "É uma campanha: quer mudar o comportamento das pessoas."),
          q("d2", "O X vermelho sobre o mosquito significa:", ["que devemos combater o mosquito", "que o mosquito é bonito", "um erro de impressão", "que o mosquito é pequeno"], "Na linguagem visual, o X indica proibição ou combate."),
          q("d3", "Por que “10 MINUTOS” aparece em letras grandes?", ["para mostrar que a ação é rápida e fácil", "porque é o nome do mosquito", "para indicar o horário", "porque é o menos importante"], "O destaque chama atenção para a ideia principal."),
          q("d4", "Quem é o responsável pela campanha?", ["a Secretaria de Saúde", "uma loja de pneus", "o mosquito", "uma escola"], "A assinatura no rodapé informa o autor."),
          q("d5", "O público-alvo do cartaz é:", ["a população em geral, que pode ter água parada em casa", "apenas os médicos", "apenas as crianças", "os fabricantes de pneus"], "A campanha fala com quem tem quintal, vasos e garrafas."),
          q("d6", "“Água parada é casa de mosquito” é uma frase que:", ["explica o problema de forma simples e marcante", "vende um produto", "conta uma história", "dá uma instrução técnica"], "É um slogan explicativo."),
          q("d7", "Por que o cartaz cita vasos, pneus e garrafas?", ["porque são lugares comuns onde a água se acumula", "porque são objetos bonitos", "porque estão à venda", "por acaso"], "São exemplos concretos do dia a dia."),
          q("d8", "O tamanho diferente das letras serve para:", ["hierarquizar a informação: primeiro o essencial, depois o detalhe", "economizar tinta", "confundir o leitor", "indicar o preço"], "O destaque organiza a leitura."),
          q("d9", "“Uma vez por semana” informa:", ["com que frequência a ação deve ser feita", "o preço da campanha", "o nome do mosquito", "o local da campanha"], "É a orientação prática do cartaz."),
          q("d10", "A imagem e o texto do cartaz:", ["se completam para transmitir a mesma mensagem", "dizem coisas contrárias", "não têm relação", "só a imagem importa"], "Nos textos multimodais, os dois trabalham juntos."),
        ],
      },
    },
    emSala: [
      "Leve tirinhas de jornal e cubra as falas: a turma cria os balões a partir das imagens.",
      "Faça um mural de onomatopeias com sons da escola (sinal, bola, chuva no telhado).",
      "Analise cartazes reais de campanhas de saúde: imagem, frase de destaque e quem assina.",
    ],
  },
  {
    id: "lp-finalidade",
    disc: "LP",
    series: [2, 3, 4, 5],
    titulo: "Para que serve este texto?",
    emoji: "📮",
    conteudo: "Gêneros textuais",
    habilidades: [
      "Identificar a finalidade de textos de diferentes generos",
      "Reconhecer a finalidade de um texto",
      "Identificar generos (listas, agendas, calendarios, avisos, convites, receitas, legendas)",
      "Ler textos injuntivos instrucionais (receitas, instrucoes)",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "Uma RECEITA de bolo serve para:", ["ensinar a fazer o bolo", "contar uma história", "dar uma notícia"], "Receita ensina, passo a passo."),
          q("r2", "Um CONVITE de aniversário serve para:", ["chamar as pessoas para a festa", "ensinar uma brincadeira", "vender balões"], "O convite chama e informa data, hora e local."),
          q("r3", "Uma LISTA DE COMPRAS serve para:", ["lembrar o que comprar", "contar uma piada", "ensinar a cozinhar"], "A lista ajuda a lembrar os itens."),
          q("r4", "Uma BULA de remédio serve para:", ["informar como tomar o remédio", "contar uma história", "convidar para a festa"], "A bula orienta o uso correto."),
          q("r5", "Uma NOTÍCIA de jornal serve para:", ["informar um fato que aconteceu", "ensinar a fazer bolo", "vender sapatos"], "Notícia informa fatos reais."),
          q("r6", "Um AVISO no mural da escola serve para:", ["comunicar algo importante à comunidade", "contar uma piada", "ensinar matemática"], "O aviso comunica."),
          q("r7", "Uma FÁBULA serve principalmente para:", ["divertir e ensinar uma lição", "vender um produto", "marcar uma consulta"], "Fábulas trazem uma moral."),
          q("r8", "Um CALENDÁRIO serve para:", ["organizar datas e compromissos", "contar uma história", "ensinar a nadar"], "Calendário organiza o tempo."),
          q("r9", "Uma PLACA com “PROIBIDO NADAR” serve para:", ["avisar sobre um perigo e proibir", "ensinar a nadar", "convidar para o rio"], "Placas alertam e ordenam."),
          q("r10", "Um ANÚNCIO de loja serve para:", ["convencer as pessoas a comprar", "contar uma história antiga", "explicar uma doença"], "O anúncio quer vender."),
        ],
      },
      pratica: {
        texto: {
          titulo: "Três textos curtos",
          paragrafos: [
            "Texto A: “Atenção, pais! Reunião na sexta-feira, às 17h, na sala do 4º ano.”",
            "Texto B: “Era uma vez um jabuti que queria voar...”",
            "Texto C: “Misture a farinha e os ovos. Leve ao forno por 30 minutos.”",
          ],
        },
        questoes: [
          q("p1", "O Texto A serve para:", ["avisar sobre uma reunião", "ensinar uma receita", "contar uma história", "vender um produto"], "É um aviso: informa data, hora e local."),
          q("p2", "O Texto B é o começo de:", ["uma história (conto ou fábula)", "uma receita", "um aviso", "uma notícia"], "“Era uma vez” é típico de histórias."),
          q("p3", "O Texto C tem a finalidade de:", ["ensinar como fazer algo", "divertir com uma piada", "convidar para uma festa", "dar uma opinião"], "Verbos como misture e leve dão instruções."),
          q("p4", "Qual texto usa verbos que dão ORDENS (misture, leve)?", ["Texto C", "Texto A", "Texto B", "nenhum"], "Textos de instrução usam verbos no imperativo."),
          q("p5", "Quem provavelmente escreveu o Texto A?", ["a escola ou a direção", "um personagem de história", "um cozinheiro", "uma criança"], "O aviso é dirigido aos pais pela escola."),
          q("p6", "O Texto B provavelmente vai contar:", ["o que acontece com o jabuti que queria voar", "como fazer um bolo", "o horário da reunião", "o preço de um produto"], "“Era uma vez” abre uma narrativa."),
          q("p7", "Qual informação do Texto A NÃO poderia faltar?", ["o dia e a hora da reunião", "o nome do bolo", "o nome do jabuti", "o preço"], "Um aviso precisa de quando e onde."),
          q("p8", "Em qual texto o leitor precisa seguir uma ordem de passos?", ["Texto C", "Texto A", "Texto B", "nenhum"], "A receita tem etapas em sequência."),
          q("p9", "O Texto B se diferencia dos outros porque:", ["conta algo inventado, para divertir", "informa um fato real", "dá instruções", "faz um aviso"], "É ficção."),
          q("p10", "Se alguém quisesse saber a que horas ir à escola, leria:", ["o Texto A", "o Texto B", "o Texto C", "nenhum deles"], "O aviso traz o horário."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Três textos sobre o mesmo tema",
          paragrafos: [
            "Texto 1: “Açaí fresquinho! Leve 2 litros e ganhe tapioca. Só hoje!”",
            "Texto 2: “A produção de açaí no Acre cresceu 20% este ano, segundo a Secretaria de Agricultura.”",
            "Texto 3: “Na minha opinião, o açaí é a fruta mais saborosa da Amazônia.”",
          ],
        },
        questoes: [
          q("d1", "Qual texto tem a finalidade de VENDER?", ["Texto 1", "Texto 2", "Texto 3", "todos"], "Anúncios usam promoção e urgência (“Só hoje!”)."),
          q("d2", "O Texto 2 é uma notícia porque:", ["informa um fato com dados e fonte", "dá uma opinião pessoal", "tenta vender açaí", "conta uma história inventada"], "Notícia informa fatos e cita de onde veio a informação."),
          q("d3", "O Texto 3 expressa:", ["uma opinião", "um fato comprovado", "uma instrução", "um aviso"], "“Na minha opinião” mostra um ponto de vista pessoal."),
          q("d4", "Por que o Texto 1 usa “Só hoje!”?", ["para convencer o cliente a comprar logo", "para informar a data de colheita", "para dar uma instrução", "para contar uma história"], "A urgência é uma estratégia de convencimento."),
          q("d5", "Qual texto apresenta um DADO numérico com fonte?", ["Texto 2", "Texto 1", "Texto 3", "nenhum"], "20% e a Secretaria de Agricultura."),
          q("d6", "A diferença principal entre fato e opinião aparece ao comparar:", ["os textos 2 e 3", "os textos 1 e 2", "os textos 1 e 3", "não aparece"], "O 2 informa um fato; o 3 dá opinião."),
          q("d7", "“Leve 2 litros e ganhe tapioca” é uma estratégia para:", ["atrair o cliente com uma vantagem", "informar a produção", "dar uma opinião", "explicar a receita"], "A promoção é argumento de venda."),
          q("d8", "Se o Texto 3 aparecesse num jornal, provavelmente estaria:", ["na seção de opinião", "na primeira página como notícia", "nos classificados", "na previsão do tempo"], "Opinião tem lugar próprio no jornal."),
          q("d9", "Qual palavra do Texto 3 mais indica que é uma opinião?", ["opinião", "Amazônia", "fruta", "açaí"], "“Na minha opinião” marca o ponto de vista."),
          q("d10", "Os três textos mostram que um mesmo assunto pode:", ["ser tratado com finalidades diferentes", "ter sempre a mesma finalidade", "só virar notícia", "só virar anúncio"], "A finalidade depende de quem escreve e para quê."),
        ],
      },
    },
    emSala: [
      "Monte uma “banca de textos” com bula, receita, convite, notícia e anúncio: a turma classifica pela finalidade.",
      "Pergunte sempre: quem escreveu, para quem e para quê?",
      "Transforme o mesmo assunto em dois gêneros (um aviso e uma história).",
    ],
  },
  {
    id: "lp-inferencia",
    disc: "LP",
    series: [2, 3, 4, 5],
    titulo: "Ler nas entrelinhas (o que o texto não diz)",
    emoji: "🕵️",
    conteudo: "Inferência",
    habilidades: [
      "Inferir informacao implicita em um texto",
      "Inferir o assunto de um texto",
      "Inferir o sentido de palavras ou expressoes",
      "Inferir o sentido de uma palavra ou expressao",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "João chegou pingando água e com o guarda-chuva virado. O que aconteceu lá fora?", ["estava chovendo e ventando", "estava fazendo sol", "estava nevando"], "Pistas: pingando água e guarda-chuva virado."),
          q("r2", "Bia bocejou, esfregou os olhos e deitou no sofá. Como Bia estava?", ["com sono", "com fome", "com raiva"], "Bocejar e esfregar os olhos são sinais de sono."),
          q("r3", "O cachorro abanava o rabo e pulava na porta quando o dono chegou. O cachorro estava:", ["feliz", "triste", "doente"], "Abanar o rabo e pular mostram alegria."),
          q("r4", "Lia entrou na sala tremendo e esfregando as mãos. Como estava o tempo?", ["frio", "muito quente", "abafado"], "Tremer e esfregar as mãos indicam frio."),
          q("r5", "Téo olhou o prato vazio e pediu mais. Téo estava:", ["com fome", "sem fome", "com sono"], "Pedir mais depois de esvaziar o prato indica fome."),
          q("r6", "A sala estava cheia de bolo, balões e presentes. O que estava acontecendo?", ["uma festa de aniversário", "uma aula de matemática", "uma faxina"], "Bolo, balões e presentes = festa."),
          q("r7", "Sofia pegou a mochila, a garrafinha e correu para o portão. Ela estava indo:", ["para a escola", "dormir", "tomar banho"], "Mochila e garrafinha são pistas da escola."),
          q("r8", "O chão estava molhado e havia um guarda-chuva aberto na varanda. O que houve?", ["choveu", "nevou", "fez sol o dia todo"], "Chão molhado e guarda-chuva indicam chuva."),
          q("r9", "Kauã escondeu a prova na mochila e olhou para o chão quando a mãe perguntou da nota. Kauã provavelmente:", ["não foi bem na prova", "tirou a maior nota", "perdeu a prova"], "Esconder e desviar o olhar sugerem nota ruim."),
          q("r10", "O cachorro rosnava com o pelo arrepiado. Ele estava:", ["assustado ou bravo", "feliz", "com sono"], "Rosnar e arrepiar o pelo são sinais de ameaça."),
        ],
      },
      pratica: {
        texto: {
          titulo: "A mesa da cozinha",
          paragrafos: [
            "Quando Caio entrou em casa, sentiu cheiro de bolo. Na mesa havia pratos, copos, balões coloridos e um bolo com oito velinhas.",
            "A mãe fez “psiu!” e apagou a luz. Todos se esconderam atrás do sofá.",
          ],
        },
        questoes: [
          q("p1", "O que estava sendo preparado?", ["uma festa-surpresa de aniversário", "o almoço de domingo", "uma mudança de casa", "uma aula"], "Bolo com velas, balões e todos escondidos: é uma surpresa."),
          q("p2", "Quantos anos o aniversariante provavelmente vai fazer?", ["8 anos", "10 anos", "5 anos", "não dá para saber"], "O bolo tem oito velinhas."),
          q("p3", "Por que a mãe fez “psiu!”?", ["para ninguém fazer barulho e estragar a surpresa", "porque estava com dor", "para chamar o gato", "porque queria dormir"], "O silêncio faz parte da surpresa."),
          q("p4", "Qual é o assunto do texto?", ["a preparação de uma festa-surpresa", "uma receita de bolo", "um dia de chuva", "a limpeza da casa"], "Juntando as pistas, o tema é a festa-surpresa."),
          q("p5", "Como sabemos que a festa era surpresa, se o texto não diz isso?", ["porque todos se esconderam e a mãe pediu silêncio", "porque havia um bolo", "porque Caio entrou em casa", "porque a luz estava acesa"], "As pistas levam a essa conclusão."),
          q("p6", "O aniversariante é provavelmente:", ["o próprio Caio", "a mãe", "o vizinho", "o gato"], "Ele chega e todos se escondem para surpreendê-lo."),
          q("p7", "O cheiro de bolo indica que:", ["o bolo foi feito há pouco tempo, ali mesmo", "o bolo foi comprado ontem", "não havia bolo", "alguém queimou a comida"], "Cheiro forte sugere bolo recém-feito."),
          q("p8", "Qual detalhe permite saber a idade do aniversariante?", ["as oito velinhas", "os balões coloridos", "os copos na mesa", "o sofá"], "As velas costumam indicar a idade."),
          q("p9", "Que emoção Caio provavelmente vai sentir?", ["surpresa e alegria", "medo e raiva", "tédio", "tristeza"], "Uma festa-surpresa costuma alegrar."),
          q("p10", "Informação implícita é aquela que:", ["o leitor descobre juntando pistas", "está escrita com todas as letras", "aparece no título", "está na primeira linha"], "Inferir é concluir a partir das pistas."),
        ],
      },
      desafio: {
        texto: {
          titulo: "O bilhete na geladeira",
          paragrafos: [
            "“Filho, deixei o almoço no forno. Não esqueça de dar comida ao Totó e de fechar o portão, porque ontem ele fugiu de novo. Volto às 18h. Beijos.”",
          ],
        },
        questoes: [
          q("d1", "Quem é Totó, provavelmente?", ["o cachorro da família", "o irmão do menino", "o vizinho", "o professor"], "Ele recebe comida e foge pelo portão: é um animal de estimação."),
          q("d2", "Por que a mãe pede para fechar o portão?", ["para o Totó não fugir outra vez", "porque vai chover", "para o almoço não esfriar", "porque o portão está quebrado"], "“Ontem ele fugiu de novo” explica o pedido."),
          q("d3", "O que a expressão “de novo” revela?", ["que o Totó já tinha fugido outras vezes", "que é a primeira fuga", "que o Totó voltou", "que o portão é novo"], "“De novo” indica repetição."),
          q("d4", "Onde a mãe estava quando o filho leu o bilhete?", ["fora de casa, provavelmente trabalhando", "na cozinha", "dormindo no quarto", "no quintal com o Totó"], "Ela deixou bilhete e disse que volta às 18h."),
          q("d5", "O que o bilhete revela sobre a rotina da família?", ["a mãe sai e o filho fica responsável por algumas tarefas", "ninguém trabalha", "o filho mora sozinho", "a família viaja sempre"], "As tarefas delegadas mostram a rotina."),
          q("d6", "“Deixei o almoço no forno” permite concluir que:", ["a mãe cozinhou antes de sair", "o filho vai cozinhar", "eles vão comer fora", "não há comida em casa"], "Alguém preparou e guardou a comida."),
          q("d7", "Qual palavra do bilhete mostra afeto?", ["Beijos", "forno", "portão", "18h"], "A despedida carinhosa revela o vínculo."),
          q("d8", "Que problema o bilhete tenta evitar?", ["que o Totó fuja outra vez", "que o almoço queime", "que o filho se atrase", "que chova"], "Por isso o pedido de fechar o portão."),
          q("d9", "Qual seria uma conclusão ERRADA a partir do bilhete?", ["que a mãe estava brava com o filho", "que a mãe voltaria às 18h", "que o Totó já fugiu antes", "que há um animal em casa"], "Nada no texto indica irritação."),
          q("d10", "O bilhete mostra que um texto curto pode:", ["trazer muitas informações implícitas", "não informar nada", "ser sempre confuso", "dispensar a leitura atenta"], "Poucas linhas, muitas pistas."),
        ],
      },
    },
    emSala: [
      "Jogo do detetive: leia pistas curtas e a turma descobre o que aconteceu, explicando qual pista usou.",
      "Sempre pergunte “como você sabe?”: a resposta precisa apontar uma pista do texto.",
      "Use imagens sem legenda e peça hipóteses sobre o que está acontecendo.",
    ],
  },
  {
    id: "lp-referencia",
    disc: "LP",
    series: [3, 4, 5],
    titulo: "Quem é “ele”? (palavras que substituem)",
    emoji: "🔄",
    conteudo: "Coesão e referência",
    habilidades: [
      "Relacoes entre partes do texto (substituicoes lexicais/pronominais)",
      "Relacoes entre partes do texto (repeticoes/substituicoes)",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "“Ana ganhou uma boneca. ELA adorou o presente.” Quem é ELA?", ["Ana", "a boneca", "o presente"], "Ela substitui Ana, para não repetir o nome."),
          q("r2", "“O gato subiu na árvore. O BICHANO não queria descer.” O bichano é:", ["o gato", "a árvore", "o dono"], "Bichano é outra forma de chamar o gato."),
          q("r3", "“Pedro e Lia foram à praça. ELES brincaram muito.” ELES são:", ["Pedro e Lia", "a praça", "os brinquedos"], "Eles retoma as duas pessoas citadas."),
          q("r4", "“Comprei um livro. ELE é muito grosso.” Quem é ELE?", ["o livro", "o vendedor", "o preço"], "Ele retoma o livro."),
          q("r5", "“As meninas chegaram. ELAS estavam cansadas.” ELAS são:", ["as meninas", "as mochilas", "as professoras"], "Elas substitui as meninas."),
          q("r6", "“Tomei um suco de caju. A BEBIDA estava gelada.” A bebida é:", ["o suco de caju", "o copo", "o caju na árvore"], "Bebida é outra forma de chamar o suco."),
          q("r7", "“Davi perdeu a mochila. O MENINO ficou triste.” O menino é:", ["Davi", "o irmão de Davi", "o professor"], "Menino retoma Davi."),
          q("r8", "“A professora entrou. ELA cumprimentou a turma.” ELA é:", ["a professora", "a turma", "a diretora"], "Ela substitui a professora."),
          q("r9", "Para que servem palavras como ELE, ELA e ESSE num texto?", ["para não repetir sempre a mesma palavra", "para aumentar o texto", "para confundir"], "Elas retomam algo já dito."),
          q("r10", "“Vi um tucano. A AVE tinha bico enorme.” A ave é:", ["o tucano", "a árvore", "o bico"], "Ave é uma palavra mais geral para tucano."),
        ],
      },
      pratica: {
        texto: {
          titulo: "A onça-pintada",
          paragrafos: [
            "A onça-pintada é o maior felino das Américas. Esse animal vive em florestas e perto de rios.",
            "Ela é ótima nadadora e caça peixes, jacarés e capivaras. Infelizmente, a espécie está ameaçada, porque suas matas estão sendo destruídas.",
          ],
        },
        questoes: [
          q("p1", "“ESSE ANIMAL vive em florestas.” Esse animal é:", ["a onça-pintada", "o jacaré", "a capivara", "o peixe"], "A expressão retoma a onça-pintada."),
          q("p2", "Em “ELA é ótima nadadora”, ELA se refere a:", ["a onça-pintada", "a floresta", "a espécie de peixe", "a capivara"], "Ela substitui o nome do animal."),
          q("p3", "“SUAS matas estão sendo destruídas.” As matas são de quem?", ["da onça-pintada", "dos jacarés", "das pessoas", "dos rios"], "Suas = da onça, a espécie citada antes."),
          q("p4", "Por que o autor usa “esse animal” e “ela” em vez de repetir “onça-pintada”?", ["para não repetir a mesma palavra", "para confundir o leitor", "porque são animais diferentes", "por engano"], "Substituir evita repetições e liga as partes do texto."),
          q("p5", "“A ESPÉCIE está ameaçada.” A espécie é a de:", ["onça-pintada", "jacaré", "capivara", "peixe"], "O texto fala da onça o tempo todo."),
          q("p6", "Qual palavra do texto NÃO se refere à onça-pintada?", ["capivaras", "esse animal", "ela", "suas"], "Capivara é uma das presas."),
          q("p7", "Se todas as substituições fossem trocadas por “onça-pintada”, o texto ficaria:", ["repetitivo e cansativo", "mais claro", "mais curto", "sem sentido"], "As substituições evitam repetição."),
          q("p8", "“O maior felino das Américas” é uma expressão que:", ["caracteriza a onça-pintada", "nomeia outro animal", "indica um lugar", "dá uma opinião"], "É uma substituição por characterização."),
          q("p9", "Qual é a causa da ameaça à espécie, segundo o texto?", ["a destruição das matas", "a caça de peixes", "o excesso de chuva", "o tamanho do animal"], "O texto diz: suas matas estão sendo destruídas."),
          q("p10", "As palavras que retomam outras ajudam o texto a:", ["ficar coeso, com as partes bem ligadas", "ficar mais comprido", "perder o assunto", "mudar de tema"], "Isso se chama coesão."),
        ],
      },
      desafio: {
        texto: {
          titulo: "O presente",
          paragrafos: [
            "Marcos e o avô foram ao mercado comprar um presente para a avó. O idoso escolheu flores; o neto preferiu um bolo.",
            "No fim, levaram os dois. Quando ela abriu a porta, sorriu: “Vocês me conhecem bem!”",
          ],
        },
        questoes: [
          q("d1", "“O IDOSO escolheu flores.” O idoso é:", ["o avô", "Marcos", "o vendedor", "a avó"], "Idoso retoma o avô."),
          q("d2", "“O NETO preferiu um bolo.” O neto é:", ["Marcos", "o avô", "a avó", "o vendedor"], "Marcos é o neto do avô."),
          q("d3", "“Levaram OS DOIS.” Os dois são:", ["as flores e o bolo", "Marcos e o avô", "o avô e a avó", "o mercado e a casa"], "Os dois retoma os presentes escolhidos."),
          q("d4", "Em “Quando ELA abriu a porta”, ELA é:", ["a avó", "a mãe", "a vendedora", "a flor"], "A avó é quem recebe o presente."),
          q("d5", "Quantas pessoas aparecem na história?", ["três: Marcos, o avô e a avó", "duas", "quatro", "uma"], "Neto, avô e avó."),
          q("d6", "“Vocês me conhecem bem!” Quem são “vocês”?", ["Marcos e o avô", "a avó e o avô", "os vendedores", "os vizinhos"], "Os dois que levaram os presentes."),
          q("d7", "Em “me conhecem bem”, o “me” se refere a:", ["a avó", "Marcos", "o avô", "o mercado"], "Quem fala é a avó."),
          q("d8", "Por que o autor escreve “o idoso” e “o neto” em vez dos nomes?", ["para evitar repetição e mostrar a relação entre eles", "porque esqueceu os nomes", "para esconder quem são", "por engano"], "As substituições também informam o parentesco."),
          q("d9", "Se trocássemos “os dois” por “as flores”, o texto:", ["perderia a informação de que levaram bolo também", "ficaria igual", "ficaria mais claro", "mudaria de personagem"], "“Os dois” engloba flores e bolo."),
          q("d10", "O sorriso da avó permite concluir que ela:", ["gostou dos presentes", "ficou decepcionada", "não reconheceu os dois", "estava com pressa"], "Sorrir e elogiar mostram satisfação."),
        ],
      },
    },
    emSala: [
      "Leia um texto em que o nome se repete o tempo todo e reescreva com a turma usando ele, ela, esse animal.",
      "Peça que liguem com setas cada pronome à palavra que ele substitui.",
      "Brincadeira “quem é quem?”: frases com vários personagens e perguntas sobre os pronomes.",
    ],
  },
  {
    id: "lp-narrativa",
    disc: "LP",
    series: [3, 4, 5],
    titulo: "Entendendo a história: personagens, conflito e final",
    emoji: "📖",
    conteudo: "Narrativa",
    habilidades: [
      "Ler e compreender narrativas",
      "Conflito gerador do enredo e elementos da narrativa",
      "Conflito gerador e elementos da narrativa",
    ],
    niveis: {
      retomada: {
        texto: {
          titulo: "O passarinho",
          paragrafos: [
            "Um passarinho caiu do ninho. Tomás viu e ficou preocupado.",
            "Ele subiu na escada com cuidado e colocou o filhote de volta. A mãe passarinho cantou feliz.",
          ],
        },
        questoes: [
          q("r1", "Quem ajudou o passarinho?", ["Tomás", "a mãe passarinho", "um gato"], "Tomás subiu na escada e devolveu o filhote."),
          q("r2", "Qual foi o PROBLEMA da história?", ["o passarinho caiu do ninho", "Tomás caiu da escada", "a mãe passarinho sumiu"], "O problema (conflito) é o filhote fora do ninho."),
          q("r3", "Como a história termina?", ["a mãe passarinho canta feliz", "o passarinho vai embora", "Tomás chora"], "O final resolve o problema."),
          q("r4", "Em que lugar se passa a história do passarinho?", ["perto de um ninho, onde há uma árvore", "numa praia", "numa escola"], "Tomás sobe a escada até o ninho."),
          q("r5", "Quem são os personagens?", ["Tomás, o filhote e a mãe passarinho", "só Tomás", "Tomás e um gato"], "Três personagens participam."),
          q("r6", "Como Tomás se sentiu ao ver o filhote no chão?", ["preocupado", "com raiva", "com sono"], "O texto diz que ele ficou preocupado."),
          q("r7", "O que Tomás usou para chegar ao ninho?", ["uma escada", "uma corda", "um galho"], "Ele subiu na escada."),
          q("r8", "A história tem um final:", ["feliz", "triste", "assustador"], "A mãe passarinho canta feliz."),
          q("r9", "Toda história costuma ter:", ["começo, problema e final", "só um final", "apenas personagens"], "É a estrutura da narrativa."),
          q("r10", "O que Tomás demonstrou ao ajudar o passarinho?", ["cuidado com os animais", "medo de altura", "pressa"], "A atitude revela o caráter do personagem."),
        ],
      },
      pratica: {
        texto: {
          titulo: "A bola perdida",
          paragrafos: [
            "Na hora do recreio, a bola nova da turma caiu no quintal da dona Zefa, que tinha fama de brava.",
            "Ninguém queria buscá-la. Até que Yara, a mais tímida, tomou coragem e bateu no portão.",
            "Dona Zefa abriu, sorriu e devolveu a bola junto com um pacote de biscoitos. Desde aquele dia, a turma passou a visitá-la.",
          ],
        },
        questoes: [
          q("p1", "Qual é o conflito (problema) da história?", ["a bola caiu no quintal de uma vizinha que parecia brava", "a bola furou", "Yara ficou doente", "o recreio acabou"], "O problema é recuperar a bola sem coragem de pedir."),
          q("p2", "Onde a história acontece?", ["na escola e na casa vizinha", "numa praia", "numa floresta", "num hospital"], "O espaço: recreio da escola e quintal ao lado."),
          q("p3", "Qual é o momento de maior tensão?", ["quando Yara bate no portão", "quando a bola é nova", "quando comem biscoitos", "quando o recreio começa"], "É o clímax: o que dona Zefa vai fazer?"),
          q("p4", "O que a história mostra sobre dona Zefa?", ["que a fama de brava não era verdade", "que ela era mesmo muito brava", "que ela não gostava de crianças", "que ela era a professora"], "O desfecho quebra a expectativa."),
          q("p5", "Quem é a personagem principal da história?", ["Yara", "dona Zefa", "a bola", "o professor"], "É ela quem resolve o conflito."),
          q("p6", "Qual característica de Yara torna a atitude dela mais marcante?", ["ela era a mais tímida da turma", "ela era a mais alta", "ela era a mais velha", "ela era a capitã"], "Vencer a própria timidez dá força à cena."),
          q("p7", "Quando a história acontece?", ["na hora do recreio", "de madrugada", "no fim de semana", "nas férias"], "O texto informa o momento."),
          q("p8", "O que muda na turma depois do desfecho?", ["passam a visitar dona Zefa", "trocam de escola", "param de jogar bola", "perdem a bola"], "O final transforma a relação."),
          q("p9", "A “fama de brava” de dona Zefa era:", ["uma ideia que a turma tinha, e não a verdade", "um fato comprovado", "uma informação do narrador confiável", "o nome dela"], "O desfecho desmente a fama."),
          q("p10", "Qual lição a história sugere?", ["não julgar as pessoas pela fama que têm", "nunca pedir nada aos vizinhos", "não jogar bola na escola", "tímidos não devem falar"], "O enredo desfaz um preconceito."),
        ],
      },
      desafio: {
        texto: {
          titulo: "O mapa do avô",
          paragrafos: [
            "Depois que o avô morreu, Lucas encontrou no sótão um mapa desenhado à mão, com um X perto do igarapé.",
            "Ele e a prima Sofia seguiram as pistas durante toda a manhã. Quando finalmente cavaram no lugar marcado, acharam só uma lata enferrujada.",
            "Dentro havia fotos antigas da família e um bilhete: “O maior tesouro são as pessoas que a gente ama.” Os dois voltaram para casa em silêncio, abraçados.",
          ],
        },
        questoes: [
          q("d1", "O que dá início à aventura (situação inicial que gera o conflito)?", ["Lucas encontra o mapa do avô", "Sofia perde a bicicleta", "o igarapé transborda", "a lata enferruja"], "O mapa desperta a busca."),
          q("d2", "Por que o final surpreende o leitor?", ["o “tesouro” não era ouro, mas lembranças da família", "eles não acham nada", "o mapa era falso", "o avô aparece"], "A expectativa era riqueza; o tesouro era afetivo."),
          q("d3", "“Voltaram em silêncio, abraçados” mostra que eles estavam:", ["emocionados", "com raiva um do outro", "cansados de brincar", "com medo do escuro"], "O silêncio e o abraço revelam emoção."),
          q("d4", "Qual é a mensagem principal da história?", ["as pessoas que amamos valem mais que riquezas", "é perigoso cavar buracos", "mapas sempre mentem", "não se deve entrar no sótão"], "A frase do bilhete resume a mensagem."),
          q("d5", "Quem são os personagens da aventura?", ["Lucas e a prima Sofia", "Lucas e o avô", "Sofia e a avó", "apenas Lucas"], "Os dois primos seguem as pistas."),
          q("d6", "Onde o mapa foi encontrado?", ["no sótão", "no igarapé", "na escola", "no quintal"], "Informação explícita no 1º parágrafo."),
          q("d7", "Quanto tempo durou a busca?", ["toda a manhã", "uma semana", "poucos minutos", "um ano"], "O texto diz: durante toda a manhã."),
          q("d8", "O que havia dentro da lata?", ["fotos antigas e um bilhete", "moedas de ouro", "um novo mapa", "nada"], "Informação explícita no 3º parágrafo."),
          q("d9", "O momento de maior expectativa da narrativa é:", ["quando eles cavam no lugar marcado pelo X", "quando encontram o mapa", "quando voltam para casa", "quando o avô morre"], "É o clímax: o que haverá ali?"),
          q("d10", "Por que o avô teria deixado esse “tesouro”?", ["para ensinar aos netos o que ele considerava mais valioso", "para escondê-lo dos ladrões", "porque não tinha dinheiro", "por engano"], "O bilhete revela a intenção."),
        ],
      },
    },
    emSala: [
      "Use a “mão da história”: cada dedo é um elemento (quem, onde, quando, problema, solução).",
      "Leia até o conflito e pare: a turma escreve ou desenha o final antes de ouvir o original.",
      "Compare finais: o esperado × o que o autor escolheu.",
    ],
  },
  {
    id: "lp-ideia-central",
    disc: "LP",
    series: [3, 4, 5],
    titulo: "Qual é a ideia principal?",
    emoji: "💡",
    conteudo: "Compreensão de texto",
    habilidades: [
      "Identificar a ideia central de um texto",
      "Localizar informacao explicita em um texto",
      "Localizar informacoes explicitas em um texto",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "“O cão late, o gato mia e a vaca muge.” O texto fala sobre:", ["sons dos animais", "comida dos animais", "cores dos animais"], "Todas as frases falam de sons."),
          q("r2", "“Escove os dentes, tome banho e lave as mãos.” O assunto é:", ["higiene", "esporte", "viagem"], "São cuidados de higiene."),
          q("r3", "“A maçã, a banana e a manga são gostosas e fazem bem.” A ideia principal é:", ["frutas são gostosas e saudáveis", "a maçã é vermelha", "a manga é amarela"], "A ideia que junta tudo é: frutas fazem bem."),
          q("r4", "“O ônibus, o carro e a bicicleta levam pessoas.” O assunto é:", ["meios de transporte", "cores dos veículos", "preço das passagens"], "Todos os exemplos são transportes."),
          q("r5", "“Chove, venta e faz sol.” O texto fala de:", ["o tempo (clima)", "comida", "esportes"], "Todas as palavras descrevem o tempo."),
          q("r6", "“O médico cuida dos doentes, o professor ensina e o pedreiro constrói.” O assunto é:", ["profissões", "escolas", "hospitais"], "São exemplos de profissões."),
          q("r7", "“Beba água, coma frutas e durma bem.” A ideia principal é:", ["cuidar da saúde", "fazer compras", "estudar mais"], "São hábitos saudáveis."),
          q("r8", "“Leia o enunciado, pense e só depois responda.” O texto ensina:", ["como fazer uma prova com atenção", "como cozinhar", "como brincar"], "São orientações de estudo."),
          q("r9", "Para achar a ideia principal, devemos perguntar:", ["sobre o que o texto fala o tempo todo?", "quantas palavras tem?", "quem é o autor?"], "A ideia principal atravessa o texto inteiro."),
          q("r10", "“A arara é azul, a arara come frutas, a arara vive na mata.” O texto fala sobre:", ["a arara", "as frutas", "a mata"], "Todas as frases tratam da arara."),
        ],
      },
      pratica: {
        texto: {
          titulo: "As abelhas",
          paragrafos: [
            "As abelhas são muito importantes para a natureza. Ao voar de flor em flor, elas levam o pólen e ajudam as plantas a produzir frutos.",
            "Sem elas, alimentos como maçã, café e castanha ficariam raros. Por isso, é preciso proteger as abelhas e evitar venenos nas plantações.",
          ],
        },
        questoes: [
          q("p1", "Qual é a ideia principal do texto?", ["as abelhas são importantes e precisam ser protegidas", "as abelhas picam as pessoas", "o café é gostoso", "as flores são coloridas"], "Todo o texto defende a importância das abelhas."),
          q("p2", "Segundo o texto, o que as abelhas levam de flor em flor?", ["o pólen", "a água", "o veneno", "as sementes de café"], "Informação explícita: elas levam o pólen."),
          q("p3", "Qual alimento o texto cita que ficaria raro sem abelhas?", ["castanha", "arroz", "feijão", "peixe"], "O texto cita maçã, café e castanha."),
          q("p4", "Qual seria um bom título para o texto?", ["Abelhas: pequenas e essenciais", "Como fazer mel", "O perigo das abelhas", "Flores do jardim"], "O título deve resumir a ideia principal."),
          q("p5", "Por que o autor cita maçã, café e castanha?", ["para dar exemplos concretos do que depende das abelhas", "para ensinar uma receita", "para vender esses alimentos", "por acaso"], "Os exemplos reforçam o argumento."),
          q("p6", "O que o texto pede que se evite nas plantações?", ["venenos", "água", "flores", "abelhas"], "Informação explícita no 2º parágrafo."),
          q("p7", "Segundo o texto, as abelhas ajudam as plantas a:", ["produzir frutos", "crescer mais altas", "mudar de cor", "perder folhas"], "O pólen permite a formação dos frutos."),
          q("p8", "Qual frase resume melhor o 1º parágrafo?", ["as abelhas ajudam as plantas ao levar o pólen", "as abelhas são perigosas", "as flores são bonitas", "o mel é doce"], "O parágrafo explica o papel das abelhas."),
          q("p9", "A expressão “Por isso” no 2º parágrafo introduz:", ["a conclusão de que é preciso protegê-las", "uma nova informação sem ligação", "uma pergunta", "uma dúvida"], "É a consequência do que foi exposto."),
          q("p10", "Qual título NÃO serviria para o texto?", ["O perigo das picadas de abelha", "Abelhas: pequenas e essenciais", "Por que proteger as abelhas", "Abelhas e a produção de alimentos"], "Esse título trata de outro assunto."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Menos telas, mais movimento",
          paragrafos: [
            "Pesquisas mostram que muitas crianças passam mais de quatro horas por dia diante de celulares e televisores.",
            "Especialistas alertam que esse tempo pode atrapalhar o sono, a visão e a concentração nos estudos. Eles recomendam brincar ao ar livre, praticar esportes e ler livros.",
            "Pequenas mudanças, como desligar o celular uma hora antes de dormir, já fazem diferença.",
          ],
        },
        questoes: [
          q("d1", "Qual é a ideia central?", ["o excesso de telas prejudica as crianças, e é possível mudar esse hábito", "os celulares são caros", "as crianças devem assistir mais TV", "esportes são perigosos"], "O texto aponta o problema e sugere soluções."),
          q("d2", "Quais problemas o excesso de tela pode causar?", ["no sono, na visão e na concentração", "na altura e no peso", "na fala e na audição", "nenhum problema"], "Informação explícita no 2º parágrafo."),
          q("d3", "Qual parágrafo traz uma sugestão simples para mudar o hábito?", ["o terceiro", "o primeiro", "o segundo", "nenhum"], "Desligar o celular antes de dormir está no último parágrafo."),
          q("d4", "Qual frase NÃO resume bem o texto?", ["crianças devem usar telas o dia todo", "o tempo de tela precisa ser equilibrado", "brincar e ler são boas alternativas", "o excesso de telas faz mal"], "A frase contraria o que o texto defende."),
          q("d5", "Quantas horas por dia muitas crianças passam diante das telas, segundo o texto?", ["mais de quatro", "menos de uma", "exatamente duas", "o texto não diz"], "Informação explícita no 1º parágrafo."),
          q("d6", "Quem faz os alertas citados no texto?", ["especialistas", "as próprias crianças", "os fabricantes de celular", "os professores"], "O 2º parágrafo cita especialistas."),
          q("d7", "Quais alternativas às telas o texto recomenda?", ["brincar ao ar livre, praticar esportes e ler", "assistir a mais TV", "jogar no computador", "dormir o dia todo"], "Informação explícita no 2º parágrafo."),
          q("d8", "A estrutura do texto é:", ["problema, consequências e soluções", "só opinião", "só uma história", "uma receita"], "Cada parágrafo cumpre uma função."),
          q("d9", "“Pequenas mudanças já fazem diferença” serve para:", ["mostrar que a solução é possível e simples", "assustar o leitor", "vender um aplicativo", "encerrar sem conclusão"], "O texto termina encorajando a ação."),
          q("d10", "O texto pode ser classificado como:", ["um texto informativo que também orienta", "uma fábula", "um anúncio", "uma receita"], "Informa dados e recomenda atitudes."),
        ],
      },
    },
    emSala: [
      "Depois de ler, peça que a turma resuma o texto em uma frase de até 10 palavras.",
      "Escolha entre três títulos qual resume melhor o texto, e justifique.",
      "Sublinhe as informações explícitas de uma cor e a ideia central de outra.",
    ],
  },
  {
    id: "lp-rimas-sons",
    disc: "LP",
    series: [1, 2],
    titulo: "Rimas e sons das palavras",
    emoji: "🎵",
    conteudo: "Consciência fonológica",
    habilidades: [
      "Identificar rimas",
      "Comparar palavras (sons de silabas iniciais, mediais e finais)",
      "Ler palavras",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "Qual palavra RIMA com GATO? 🐱", ["PATO 🦆", "BOLA ⚽", "CASA 🏠"], "GATO e PATO terminam com o mesmo som: -ATO."),
          q("r2", "Qual palavra começa com o mesmo som de BOLA? ⚽", ["BOLO 🎂", "MALA 🧳", "FACA 🔪"], "BOLA e BOLO começam com BO."),
          q("r3", "Qual palavra RIMA com MÃO? ✋", ["PÃO 🍞", "PÉ 🦶", "SOL ☀️"], "MÃO e PÃO terminam com -ÃO."),
          q("r4", "Qual palavra RIMA com BOLA? ⚽", ["SACOLA 🛍️", "CARRO 🚗", "PEIXE 🐟"], "BOLA e SACOLA terminam em -OLA."),
          q("r5", "Qual palavra RIMA com FLOR? 🌸", ["COR 🎨", "FOLHA 🍃", "GATO 🐱"], "FLOR e COR terminam em -OR."),
          q("r6", "Qual palavra começa com o mesmo som de SAPO? 🐸", ["SACO", "PATO", "MALA"], "SA-PO e SA-CO começam com SA."),
          q("r7", "Qual palavra RIMA com DEDO?", ["MEDO", "MÃO", "PÉ"], "DEDO e MEDO terminam em -EDO."),
          q("r8", "Qual palavra começa com o mesmo som de CASA? 🏠", ["CAVALO 🐴", "MESA", "PORTA"], "CA-SA e CA-VALO começam com CA."),
          q("r9", "Qual palavra RIMA com PÃO? 🍞", ["CHÃO", "PATO", "BOLO"], "PÃO e CHÃO terminam em -ÃO."),
          q("r10", "Duas palavras RIMAM quando:", ["terminam com o mesmo som", "começam com a mesma letra", "têm o mesmo tamanho"], "A rima está no som final."),
        ],
      },
      pratica: {
        questoes: [
          q("p1", "Qual palavra rima com JANELA?", ["PANELA", "JARRA", "CADEIRA", "MESA"], "JANELA e PANELA terminam em -ELA."),
          q("p2", "Qual palavra começa com a mesma sílaba de MACACO?", ["MALA", "SAPO", "COPO", "PATO"], "MA-CACO e MA-LA."),
          q("p3", "Qual palavra termina com a mesma sílaba de CAVALO?", ["GALO", "CAVA", "LOBO", "BOLA"], "CAVA-LO e GA-LO terminam com LO."),
          q("p4", "Em qual par as palavras RIMAM?", ["CORAÇÃO e LIMÃO", "CASA e BOLA", "SAPO e SOL", "LUA e LEITE"], "Coração e limão terminam em -ÃO."),
          q("p5", "Qual palavra rima com ESCOLA?", ["VIOLA", "ESCADA", "CADERNO", "AMIGO"], "ESCOLA e VIOLA terminam em -OLA."),
          q("p6", "Qual palavra começa com a mesma sílaba de BORBOLETA?", ["BORRACHA", "BOLA", "PORTA", "CAVALO"], "BOR-BOLETA e BOR-RACHA."),
          q("p7", "Qual palavra RIMA com MENINA?", ["PISCINA", "MENINO", "MESA", "BONECA"], "MENINA e PISCINA terminam com o mesmo som: -INA."),
          q("p8", "Em qual destes pares as duas palavras terminam com o mesmo som?", ["JANELA e PANELA", "CASA e CARRO", "PATO e PENA", "SOL e SAL"], "JANELA e PANELA terminam em -ELA."),
          q("p9", "Quantas sílabas tem SAPATO?", ["3 (SA-PA-TO)", "2", "4", "5"], "SA-PA-TO: três palmas."),
          q("p10", "Qual palavra tem MAIS sílabas?", ["BICICLETA", "BOLA", "GATO", "MÃO"], "BI-CI-CLE-TA tem quatro."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Versinho",
          paragrafos: ["A formiga tão pequena", "carregava uma folha inteira.", "Trabalhava sem ter pena,", "subindo a bananeira."],
        },
        questoes: [
          q("d1", "Quais palavras rimam no versinho?", ["PEQUENA e PENA", "FORMIGA e FOLHA", "MANHÃ e NOITE", "TÃO e UMA"], "PEQUENA e PENA terminam em -ENA."),
          q("d2", "Qual palavra do versinho rima com INTEIRA?", ["BANANEIRA", "FORMIGA", "PEQUENA", "TRABALHAVA"], "INTEIRA e BANANEIRA terminam em -EIRA."),
          q("d3", "Quantas sílabas tem a palavra FORMIGA?", ["3 (FOR-MI-GA)", "2", "4", "5"], "FOR-MI-GA: três sílabas."),
          q("d4", "Qual palavra tem a mesma sílaba do MEIO de FORMIGA?", ["CAMISA (CA-MI-SA)", "FOGO", "GALINHA", "MOLA"], "A sílaba do meio é MI: ca-MI-sa."),
          q("d5", "Quantos versos tem o versinho?", ["4", "2", "3", "6"], "Cada linha é um verso."),
          q("d6", "O que a formiga carregava?", ["uma folha inteira", "uma semente", "uma pedra", "uma flor"], "Informação explícita no versinho."),
          q("d7", "Onde a formiga subia?", ["na bananeira", "na parede", "na árvore de manga", "no muro"], "O último verso informa."),
          q("d8", "“Trabalhava sem ter pena” quer dizer que a formiga:", ["trabalhava com muito esforço, sem reclamar", "tinha dó de si mesma", "não gostava de trabalhar", "estava com pena de alguém"], "A expressão indica esforço sem lamento."),
          q("d9", "Quantas sílabas tem BANANEIRA?", ["4 (BA-NA-NEI-RA)", "3", "5", "2"], "BA-NA-NEI-RA: quatro."),
          q("d10", "O esquema de rimas do versinho é:", ["1º verso rima com o 3º, e o 2º com o 4º", "todos os versos rimam entre si", "nenhum verso rima", "só os dois últimos rimam"], "PEQUENA/PENA e INTEIRA/BANANEIRA."),
        ],
      },
    },
    emSala: [
      "Roda de rimas com o nome dos alunos (“Ana banana”, “João feijão”).",
      "Bingo de sílabas iniciais com figuras.",
      "Palmas para contar as sílabas de palavras do cotidiano.",
    ],
  },
  {
    id: "lp-letras-frases",
    disc: "LP",
    series: [1, 2],
    titulo: "Letras, palavras e frases",
    emoji: "🔤",
    conteudo: "Alfabetização",
    habilidades: [
      "Distinguir letras do alfabeto de outros sinais graficos",
      "Reconhecer a segmentacao de palavras na escrita",
      "Ler frases",
      "Localizar informacao explicita em um texto",
    ],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "Qual destes é uma LETRA?", ["B", "7", "★"], "B é uma letra do alfabeto; 7 é número e ★ é um desenho."),
          q("r2", "Qual destes é um NÚMERO?", ["5", "M", "A"], "5 é um número; M e A são letras."),
          q("r3", "Quantas palavras há em: O GATO DORME", ["3", "1", "5"], "O / GATO / DORME: três palavras, separadas por espaços."),
          q("r4", "Entre M, 3 e +, qual é uma LETRA?", ["M", "3", "+"], "M é letra; 3 é número e + é um sinal."),
          q("r5", "Quantas palavras há em: A BOLA ROLOU", ["3", "2", "4"], "A / BOLA / ROLOU."),
          q("r6", "Qual destes NÃO é uma letra?", ["9", "P", "S"], "9 é um número."),
          q("r7", "Quantas letras tem a palavra SOL?", ["3", "2", "4"], "S, O, L."),
          q("r8", "O que separa uma palavra da outra quando escrevemos?", ["o espaço", "a cor da caneta", "o desenho"], "O espaço marca o fim de cada palavra."),
          q("r9", "Qual grupo tem SÓ números?", ["2 7 9", "A B C", "A 2 C"], "Os outros grupos têm letras."),
          q("r10", "Toda frase começa com:", ["letra maiúscula", "letra minúscula", "número"], "É uma regra da escrita."),
        ],
      },
      pratica: {
        questoes: [
          q("p1", "Qual frase está escrita com os espaços certos?", ["A BOLA É AZUL.", "ABOLA ÉAZUL.", "A BO LA É A ZUL.", "ABOLAÉAZUL."], "Cada palavra fica separada por um espaço."),
          q("p2", "Leia: “O sapo pulou no lago.” Onde o sapo pulou?", ["no lago", "na árvore", "na cama", "no carro"], "A frase diz: no lago."),
          q("p3", "Leia: “Bia comeu uma maçã vermelha.” De que cor era a maçã?", ["vermelha", "verde", "amarela", "azul"], "A cor está escrita na frase."),
          q("p4", "Qual grupo tem SÓ letras?", ["L E O", "L 3 O", "★ E O", "1 2 3"], "3, ★ e 1 2 3 não são letras."),
          q("p5", "Qual frase está escrita corretamente?", ["O menino come pão.", "Omenino comepão.", "O me nino co me pão.", "omeninocomepão"], "Cada palavra separada, com maiúscula e ponto."),
          q("p6", "Leia: “A galinha botou três ovos.” Quantos ovos ela botou?", ["três", "dois", "cinco", "um"], "A frase informa o número."),
          q("p7", "Leia: “O carro azul parou na esquina.” Onde o carro parou?", ["na esquina", "na garagem", "na praça", "na escola"], "Informação explícita na frase."),
          q("p8", "Quantas palavras há em “A menina canta”?", ["3", "2", "4", "5"], "A / menina / canta."),
          q("p9", "Em qual grupo aparecem apenas letras do alfabeto?", ["C A D", "C 4 D", "★ A D", "4 5 6"], "Os outros têm números ou símbolos."),
          q("p10", "Leia: “Téo guardou o lápis na mochila.” O que Téo guardou?", ["o lápis", "a mochila", "o caderno", "a borracha"], "A frase diz o que foi guardado."),
        ],
      },
      desafio: {
        texto: {
          titulo: "Bilhete",
          paragrafos: ["Oi, Lia! Amanhã é o piquenique na praça, às 9 horas. Leve uma fruta e um suco. Beijos, Davi."],
        },
        questoes: [
          q("d1", "Quem escreveu o bilhete?", ["Davi", "Lia", "a professora", "a mãe"], "Quem escreve assina no final."),
          q("d2", "Onde será o piquenique?", ["na praça", "na escola", "na praia", "na casa de Lia"], "Está escrito: na praça."),
          q("d3", "O que Lia deve levar?", ["uma fruta e um suco", "um bolo", "uma bola", "nada"], "O bilhete pede fruta e suco."),
          q("d4", "Quantas palavras há em “Leve uma fruta”?", ["3", "2", "4", "12"], "Leve / uma / fruta."),
          q("d5", "Para quem é o bilhete?", ["para Lia", "para Davi", "para a professora", "para a mãe"], "O bilhete começa com “Oi, Lia!”."),
          q("d6", "A que horas será o piquenique?", ["às 9 horas", "às 10 horas", "às 8 horas", "à tarde"], "Informação explícita no bilhete."),
          q("d7", "Quando será o piquenique?", ["amanhã", "hoje", "no sábado", "na semana que vem"], "O bilhete diz: amanhã."),
          q("d8", "Quantas palavras há em “Beijos, Davi”?", ["2", "1", "3", "4"], "Beijos / Davi."),
          q("d9", "Qual palavra do bilhete é um NOME de pessoa?", ["Lia", "praça", "fruta", "suco"], "Lia e Davi são nomes próprios."),
          q("d10", "Por que “Amanhã” começa com letra maiúscula no bilhete?", ["porque começa uma frase nova", "porque é nome de pessoa", "por engano", "porque é a palavra mais importante"], "Depois do ponto, começa frase nova."),
        ],
      },
    },
    emSala: [
      "Separe cartões com letras, números e símbolos; a turma classifica em três caixas.",
      "Escreva frases sem espaços no quadro e peça que as crianças marquem onde cada palavra termina.",
      "Leitura de bilhetes e listas da rotina da turma.",
    ],
  },
  {
    id: "lp-locutor",
    disc: "LP",
    series: [4],
    titulo: "Quem fala com quem? (locutor e interlocutor)",
    emoji: "🗣️",
    conteudo: "Variação e interlocução",
    habilidades: ["Marcas linguisticas do locutor e do interlocutor"],
    niveis: {
      retomada: {
        questoes: [
          q("r1", "Num bilhete que termina com “Beijos, vovó”, quem escreveu?", ["a vovó", "o neto", "o carteiro"], "Quem assina é quem escreveu (o locutor)."),
          q("r2", "“Querida professora, obrigado pelas aulas!” Para quem é a mensagem?", ["para a professora", "para a mãe", "para um amigo"], "O interlocutor é a professora."),
          q("r3", "“E aí, parceiro, bora jogar bola?” Esse jeito de falar é:", ["informal, entre amigos", "formal, de um documento", "de uma notícia"], "Gírias como “bora” mostram conversa entre amigos."),
          q("r4", "“Prezados senhores, informamos que...” Esse começo é:", ["formal", "informal", "uma piada"], "Palavras como “prezados” e “informamos” são formais."),
          q("r5", "Numa carta que termina com “Atenciosamente, Ana Souza”, quem escreveu?", ["Ana Souza", "o destinatário", "o carteiro"], "A assinatura identifica o locutor."),
          q("r6", "“Oi, mãe! Chego mais tarde.” Quem é o interlocutor?", ["a mãe", "o filho", "a professora"], "Interlocutor é a quem se fala."),
          q("r7", "Numa receita que diz “Misture bem”, quem está sendo orientado?", ["quem vai cozinhar", "o autor da receita", "o vendedor"], "O leitor é o interlocutor."),
          q("r8", "“Vossa Excelência” é uma forma de tratamento usada:", ["em situações muito formais", "entre amigos", "com animais"], "É usada com autoridades."),
          q("r9", "Numa placa “Não pise na grama”, quem fala?", ["quem cuida do lugar", "a grama", "quem passa"], "A placa é a voz do responsável pelo espaço."),
          q("r10", "O jeito de falar muda de acordo com:", ["quem escuta e a situação", "o dia da semana", "a cor da roupa"], "Isso se chama adequação da linguagem."),
        ],
      },
      pratica: {
        texto: {
          titulo: "Duas mensagens",
          paragrafos: [
            "Mensagem 1: “Senhor diretor, solicitamos a reforma do bebedouro do 2º andar. Atenciosamente, alunos do 4º A.”",
            "Mensagem 2: “Mano, o bebedouro tá quebrado de novo, que saco!”",
          ],
        },
        questoes: [
          q("p1", "Quem escreveu a Mensagem 1?", ["alunos do 4º A", "o diretor", "a merendeira", "um irmão"], "A assinatura mostra quem escreve."),
          q("p2", "Para quem foi escrita a Mensagem 1?", ["para o diretor", "para um amigo", "para a família", "para o bebedouro"], "“Senhor diretor” indica o interlocutor."),
          q("p3", "Qual mensagem usa linguagem formal?", ["a Mensagem 1", "a Mensagem 2", "as duas", "nenhuma"], "Palavras como “solicitamos” e “atenciosamente” são formais."),
          q("p4", "“Mano” e “tá” mostram que a Mensagem 2 é:", ["uma conversa informal entre conhecidos", "um documento oficial", "uma notícia", "uma receita"], "São marcas de linguagem informal."),
          q("p5", "Qual é o assunto das duas mensagens?", ["o bebedouro quebrado", "a merenda", "a reforma da quadra", "a aula de português"], "Ambas tratam do mesmo problema."),
          q("p6", "Quem escreveu, provavelmente, a Mensagem 2?", ["um aluno falando com um colega", "o diretor", "a secretaria", "um jornalista"], "“Mano” indica conversa entre colegas."),
          q("p7", "“Solicitamos” poderia ser trocado, na fala informal, por:", ["pedimos", "exigimos judicialmente", "cancelamos", "informamos"], "Pedir é a versão simples de solicitar."),
          q("p8", "Por que a Mensagem 1 é mais adequada para o diretor?", ["porque respeita a formalidade esperada nessa situação", "porque é mais curta", "porque tem gírias", "porque é mais engraçada"], "A situação pede linguagem formal."),
          q("p9", "“Que saco!” na Mensagem 2 expressa:", ["irritação de quem fala", "um elogio", "uma pergunta", "um pedido formal"], "É uma expressão de desagrado informal."),
          q("p10", "As duas mensagens mostram que:", ["podemos dizer a mesma coisa de formas diferentes, conforme o interlocutor", "só a formal está certa", "só a informal está certa", "as duas são iguais"], "As duas são adequadas em contextos diferentes."),
        ],
      },
      desafio: {
        questoes: [
          q("d1", "Qual forma é a mais adequada para escrever ao prefeito?", ["Excelentíssimo senhor prefeito,", "Fala aí, prefeito!", "E aí, mano prefeito,", "Oi, sumido!"], "Para autoridades, usamos linguagem formal."),
          q("d2", "“Uai, sô, cê num vai?” Essas marcas mostram:", ["o jeito de falar de uma região", "um erro de digitação", "uma língua estrangeira", "um texto científico"], "Variação regional do português."),
          q("d3", "Num anúncio, “Você merece este tênis!”, o “você” se refere a:", ["o leitor, o possível comprador", "o vendedor", "o tênis", "o dono da loja"], "O anúncio conversa diretamente com o leitor."),
          q("d4", "Por que um mesmo aluno fala de um jeito com os amigos e de outro na entrevista da escola?", ["porque adequamos a linguagem à situação e ao interlocutor", "porque esqueceu as palavras", "porque é proibido gírias", "não existe diferença"], "Adequação linguística."),
          q("d5", "Numa entrevista de emprego, o mais adequado é usar:", ["linguagem formal e cuidadosa", "muitas gírias", "apelidos", "abreviações de mensagem"], "A situação formal pede linguagem formal."),
          q("d6", "Numa mensagem para o melhor amigo, usar “Excelentíssimo senhor” soaria:", ["estranho, formal demais para a situação", "perfeito", "desrespeitoso", "obrigatório"], "A adequação vale nos dois sentidos."),
          q("d7", "Expressões regionais como “oxente” e “égua” mostram:", ["a variedade do português falado no Brasil", "erros de português", "uma língua estrangeira", "falta de estudo"], "Variação linguística não é erro."),
          q("d8", "Num livro didático, o “você” das perguntas se refere a:", ["o aluno que está lendo", "o autor", "o professor apenas", "ninguém"], "O material conversa com o estudante."),
          q("d9", "Numa carta de reclamação a uma loja, o tom adequado é:", ["firme, mas respeitoso e formal", "agressivo e com xingamentos", "de brincadeira", "cheio de gírias"], "Formalidade não impede firmeza."),
          q("d10", "Saber mudar o jeito de falar conforme a situação é sinal de:", ["domínio da língua", "falta de personalidade", "erro gramatical", "timidez"], "Quem domina a língua transita entre os registros."),
        ],
      },
    },
    emSala: [
      "Reescreva uma mensagem informal de WhatsApp como carta formal ao diretor.",
      "Encene diálogos entre personagens diferentes (avó, amigo, diretor) e perceba as mudanças no jeito de falar.",
      "Pesquise expressões regionais do Acre com as famílias.",
    ],
  },
];
