/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CoordenacaoRouteImport } from './routes/coordenacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TvRouteImport } from './routes/tv'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAlunosRouteImport } from './routes/dashboard/alunos'
import { Route as DashboardAulasRouteImport } from './routes/dashboard/aulas'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard/configuracoes'
import { Route as DashboardFaltasRouteImport } from './routes/dashboard/faltas'
import { Route as DashboardFrequenciaRouteImport } from './routes/dashboard/frequencia'
import { Route as DashboardGruposRouteImport } from './routes/dashboard/grupos'
import { Route as DashboardProgramacaoRouteImport } from './routes/dashboard/programacao'
import { Route as DashboardTurmasIndexRouteImport } from './routes/dashboard/turmas/index'
import { Route as DashboardTurmasTurmaIdRouteImport } from './routes/dashboard/turmas/$turmaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoRoute = CoordenacaoRouteImport.update({
  id: '/coordenacao',
  path: '/coordenacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunosRoute = DashboardAlunosRouteImport.update({
  id: '/dashboard/alunos',
  path: '/dashboard/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAulasRoute = DashboardAulasRouteImport.update({
  id: '/dashboard/aulas',
  path: '/dashboard/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/dashboard/configuracoes',
  path: '/dashboard/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFaltasRoute = DashboardFaltasRouteImport.update({
  id: '/dashboard/faltas',
  path: '/dashboard/faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFrequenciaRoute = DashboardFrequenciaRouteImport.update({
  id: '/dashboard/frequencia',
  path: '/dashboard/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/dashboard/grupos',
  path: '/dashboard/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramacaoRoute = DashboardProgramacaoRouteImport.update({
  id: '/dashboard/programacao',
  path: '/dashboard/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasIndexRoute = DashboardTurmasIndexRouteImport.update({
  id: '/dashboard/turmas/',
  path: '/dashboard/turmas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasTurmaIdRoute = DashboardTurmasTurmaIdRouteImport.update({
  id: '/dashboard/turmas/$turmaId',
  path: '/dashboard/turmas/$turmaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas': typeof DashboardTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/coordenacao'
    | '/login'
    | '/tv'
    | '/dashboard/alunos'
    | '/dashboard/aulas'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/dashboard/'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/coordenacao'
    | '/login'
    | '/tv'
    | '/dashboard/alunos'
    | '/dashboard/aulas'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/dashboard'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/coordenacao'
    | '/login'
    | '/tv'
    | '/dashboard/alunos'
    | '/dashboard/aulas'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/dashboard/'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CoordenacaoRoute: typeof CoordenacaoRoute
  LoginRoute: typeof LoginRoute
  TvRoute: typeof TvRoute
  DashboardAlunosRoute: typeof DashboardAlunosRoute
  DashboardAulasRoute: typeof DashboardAulasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardFaltasRoute: typeof DashboardFaltasRoute
  DashboardFrequenciaRoute: typeof DashboardFrequenciaRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardProgramacaoRoute: typeof DashboardProgramacaoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTurmasTurmaIdRoute: typeof DashboardTurmasTurmaIdRoute
  DashboardTurmasIndexRoute: typeof DashboardTurmasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao': {
      id: '/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof CoordenacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/alunos': {
      id: '/dashboard/alunos'
      path: '/dashboard/alunos'
      fullPath: '/dashboard/alunos'
      preLoaderRoute: typeof DashboardAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/aulas': {
      id: '/dashboard/aulas'
      path: '/dashboard/aulas'
      fullPath: '/dashboard/aulas'
      preLoaderRoute: typeof DashboardAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/dashboard/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/faltas': {
      id: '/dashboard/faltas'
      path: '/dashboard/faltas'
      fullPath: '/dashboard/faltas'
      preLoaderRoute: typeof DashboardFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/frequencia': {
      id: '/dashboard/frequencia'
      path: '/dashboard/frequencia'
      fullPath: '/dashboard/frequencia'
      preLoaderRoute: typeof DashboardFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/dashboard/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/programacao': {
      id: '/dashboard/programacao'
      path: '/dashboard/programacao'
      fullPath: '/dashboard/programacao'
      preLoaderRoute: typeof DashboardProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/': {
      id: '/dashboard/turmas/'
      path: '/dashboard/turmas'
      fullPath: '/dashboard/turmas/'
      preLoaderRoute: typeof DashboardTurmasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/$turmaId': {
      id: '/dashboard/turmas/$turmaId'
      path: '/dashboard/turmas/$turmaId'
      fullPath: '/dashboard/turmas/$turmaId'
      preLoaderRoute: typeof DashboardTurmasTurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CoordenacaoRoute: CoordenacaoRoute,
  LoginRoute: LoginRoute,
  TvRoute: TvRoute,
  DashboardAlunosRoute: DashboardAlunosRoute,
  DashboardAulasRoute: DashboardAulasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardFaltasRoute: DashboardFaltasRoute,
  DashboardFrequenciaRoute: DashboardFrequenciaRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardProgramacaoRoute: DashboardProgramacaoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTurmasTurmaIdRoute: DashboardTurmasTurmaIdRoute,
  DashboardTurmasIndexRoute: DashboardTurmasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
