/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as CoordenacaoRouteImport } from './routes/coordenacao'
import { Route as InfotecaRouteImport } from './routes/infoteca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AlunoIndexRouteImport } from './routes/aluno/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAcessosRouteImport } from './routes/dashboard/acessos'
import { Route as DashboardAlunosRouteImport } from './routes/dashboard/alunos'
import { Route as DashboardAtividadesRouteImport } from './routes/dashboard/atividades'
import { Route as DashboardAulasRouteImport } from './routes/dashboard/aulas'
import { Route as DashboardAvaliacaoRouteImport } from './routes/dashboard/avaliacao'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard/configuracoes'
import { Route as DashboardFaltasRouteImport } from './routes/dashboard/faltas'
import { Route as DashboardFichasAcessoRouteImport } from './routes/dashboard/fichas-acesso'
import { Route as DashboardFrequenciaRouteImport } from './routes/dashboard/frequencia'
import { Route as DashboardGruposRouteImport } from './routes/dashboard/grupos'
import { Route as DashboardProgramacaoRouteImport } from './routes/dashboard/programacao'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas/index'
import { Route as FerramentasFerramentaRouteImport } from './routes/ferramentas/$ferramenta'
import { Route as MediadorIndexRouteImport } from './routes/mediador/index'
import { Route as ProfessorIndexRouteImport } from './routes/professor/index'
import { Route as AlunoTurmaIdIndexRouteImport } from './routes/aluno/$turmaId/index'
import { Route as DashboardTurmasIndexRouteImport } from './routes/dashboard/turmas/index'
import { Route as DashboardTurmasTurmaIdRouteImport } from './routes/dashboard/turmas/$turmaId'
import { Route as ProfessorTurmaIdIndexRouteImport } from './routes/professor/$turmaId/index'
import { Route as ProfessorTurmaIdChamadaRouteImport } from './routes/professor/$turmaId/chamada'
import { Route as AlunoTurmaIdAlunoIdIndexRouteImport } from './routes/aluno/$turmaId/$alunoId/index'
import { Route as AlunoTurmaIdAlunoIdTrilhaRouteImport } from './routes/aluno/$turmaId/$alunoId/trilha'
import { Route as MediadorTurmaIdApoioIndexIndexRouteImport } from './routes/mediador/$turmaId/$apoioIndex/index'
import { Route as MediadorTurmaIdApoioIndexRelatorioRouteImport } from './routes/mediador/$turmaId/$apoioIndex/relatorio'
import { Route as ProfessorTurmaIdAlunoAlunoIdRouteImport } from './routes/professor/$turmaId/aluno/$alunoId'
import { Route as ProfessorTurmaIdFerramentasIndexRouteImport } from './routes/professor/$turmaId/ferramentas/index'
import { Route as ProfessorTurmaIdFerramentasFerramentaRouteImport } from './routes/professor/$turmaId/ferramentas/$ferramenta'
import { Route as AlunoTurmaIdAlunoIdFerramentasIndexRouteImport } from './routes/aluno/$turmaId/$alunoId/ferramentas/index'
import { Route as AlunoTurmaIdAlunoIdFerramentasFerramentaRouteImport } from './routes/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
import { Route as MediadorTurmaIdApoioIndexFerramentasIndexRouteImport } from './routes/mediador/$turmaId/$apoioIndex/ferramentas/index'
import { Route as MediadorTurmaIdApoioIndexFerramentasFerramentaRouteImport } from './routes/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoRoute = CoordenacaoRouteImport.update({
  id: '/coordenacao',
  path: '/coordenacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InfotecaRoute = InfotecaRouteImport.update({
  id: '/infoteca',
  path: '/infoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/aluno/',
  path: '/aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAcessosRoute = DashboardAcessosRouteImport.update({
  id: '/dashboard/acessos',
  path: '/dashboard/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunosRoute = DashboardAlunosRouteImport.update({
  id: '/dashboard/alunos',
  path: '/dashboard/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAtividadesRoute = DashboardAtividadesRouteImport.update({
  id: '/dashboard/atividades',
  path: '/dashboard/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAulasRoute = DashboardAulasRouteImport.update({
  id: '/dashboard/aulas',
  path: '/dashboard/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAvaliacaoRoute = DashboardAvaliacaoRouteImport.update({
  id: '/dashboard/avaliacao',
  path: '/dashboard/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/dashboard/configuracoes',
  path: '/dashboard/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFaltasRoute = DashboardFaltasRouteImport.update({
  id: '/dashboard/faltas',
  path: '/dashboard/faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFichasAcessoRoute = DashboardFichasAcessoRouteImport.update({
  id: '/dashboard/fichas-acesso',
  path: '/dashboard/fichas-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFrequenciaRoute = DashboardFrequenciaRouteImport.update({
  id: '/dashboard/frequencia',
  path: '/dashboard/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/dashboard/grupos',
  path: '/dashboard/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramacaoRoute = DashboardProgramacaoRouteImport.update({
  id: '/dashboard/programacao',
  path: '/dashboard/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/ferramentas/',
  path: '/ferramentas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasFerramentaRoute = FerramentasFerramentaRouteImport.update({
  id: '/ferramentas/$ferramenta',
  path: '/ferramentas/$ferramenta',
  getParentRoute: () => rootRouteImport,
} as any)
const MediadorIndexRoute = MediadorIndexRouteImport.update({
  id: '/mediador/',
  path: '/mediador/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/professor/',
  path: '/professor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoTurmaIdIndexRoute = AlunoTurmaIdIndexRouteImport.update({
  id: '/aluno/$turmaId/',
  path: '/aluno/$turmaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasIndexRoute = DashboardTurmasIndexRouteImport.update({
  id: '/dashboard/turmas/',
  path: '/dashboard/turmas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasTurmaIdRoute = DashboardTurmasTurmaIdRouteImport.update({
  id: '/dashboard/turmas/$turmaId',
  path: '/dashboard/turmas/$turmaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorTurmaIdIndexRoute = ProfessorTurmaIdIndexRouteImport.update({
  id: '/professor/$turmaId/',
  path: '/professor/$turmaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorTurmaIdChamadaRoute = ProfessorTurmaIdChamadaRouteImport.update({
  id: '/professor/$turmaId/chamada',
  path: '/professor/$turmaId/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoTurmaIdAlunoIdIndexRoute =
  AlunoTurmaIdAlunoIdIndexRouteImport.update({
    id: '/aluno/$turmaId/$alunoId/',
    path: '/aluno/$turmaId/$alunoId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlunoTurmaIdAlunoIdTrilhaRoute =
  AlunoTurmaIdAlunoIdTrilhaRouteImport.update({
    id: '/aluno/$turmaId/$alunoId/trilha',
    path: '/aluno/$turmaId/$alunoId/trilha',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediadorTurmaIdApoioIndexIndexRoute =
  MediadorTurmaIdApoioIndexIndexRouteImport.update({
    id: '/mediador/$turmaId/$apoioIndex/',
    path: '/mediador/$turmaId/$apoioIndex/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediadorTurmaIdApoioIndexRelatorioRoute =
  MediadorTurmaIdApoioIndexRelatorioRouteImport.update({
    id: '/mediador/$turmaId/$apoioIndex/relatorio',
    path: '/mediador/$turmaId/$apoioIndex/relatorio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessorTurmaIdAlunoAlunoIdRoute =
  ProfessorTurmaIdAlunoAlunoIdRouteImport.update({
    id: '/professor/$turmaId/aluno/$alunoId',
    path: '/professor/$turmaId/aluno/$alunoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessorTurmaIdFerramentasIndexRoute =
  ProfessorTurmaIdFerramentasIndexRouteImport.update({
    id: '/professor/$turmaId/ferramentas/',
    path: '/professor/$turmaId/ferramentas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessorTurmaIdFerramentasFerramentaRoute =
  ProfessorTurmaIdFerramentasFerramentaRouteImport.update({
    id: '/professor/$turmaId/ferramentas/$ferramenta',
    path: '/professor/$turmaId/ferramentas/$ferramenta',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlunoTurmaIdAlunoIdFerramentasIndexRoute =
  AlunoTurmaIdAlunoIdFerramentasIndexRouteImport.update({
    id: '/aluno/$turmaId/$alunoId/ferramentas/',
    path: '/aluno/$turmaId/$alunoId/ferramentas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlunoTurmaIdAlunoIdFerramentasFerramentaRoute =
  AlunoTurmaIdAlunoIdFerramentasFerramentaRouteImport.update({
    id: '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta',
    path: '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediadorTurmaIdApoioIndexFerramentasIndexRoute =
  MediadorTurmaIdApoioIndexFerramentasIndexRouteImport.update({
    id: '/mediador/$turmaId/$apoioIndex/ferramentas/',
    path: '/mediador/$turmaId/$apoioIndex/ferramentas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediadorTurmaIdApoioIndexFerramentasFerramentaRoute =
  MediadorTurmaIdApoioIndexFerramentasFerramentaRouteImport.update({
    id: '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta',
    path: '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/infoteca': typeof InfotecaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/tv': typeof TvRoute
  '/dashboard/acessos': typeof DashboardAcessosRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/atividades': typeof DashboardAtividadesRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/fichas-acesso': typeof DashboardFichasAcessoRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/ferramentas/$ferramenta': typeof FerramentasFerramentaRoute
  '/aluno/': typeof AlunoIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/mediador/': typeof MediadorIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/professor/$turmaId/chamada': typeof ProfessorTurmaIdChamadaRoute
  '/aluno/$turmaId/': typeof AlunoTurmaIdIndexRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
  '/professor/$turmaId/': typeof ProfessorTurmaIdIndexRoute
  '/aluno/$turmaId/$alunoId/trilha': typeof AlunoTurmaIdAlunoIdTrilhaRoute
  '/mediador/$turmaId/$apoioIndex/relatorio': typeof MediadorTurmaIdApoioIndexRelatorioRoute
  '/professor/$turmaId/aluno/$alunoId': typeof ProfessorTurmaIdAlunoAlunoIdRoute
  '/professor/$turmaId/ferramentas/$ferramenta': typeof ProfessorTurmaIdFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId/': typeof AlunoTurmaIdAlunoIdIndexRoute
  '/mediador/$turmaId/$apoioIndex/': typeof MediadorTurmaIdApoioIndexIndexRoute
  '/professor/$turmaId/ferramentas/': typeof ProfessorTurmaIdFerramentasIndexRoute
  '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta': typeof AlunoTurmaIdAlunoIdFerramentasFerramentaRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta': typeof MediadorTurmaIdApoioIndexFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId/ferramentas/': typeof AlunoTurmaIdAlunoIdFerramentasIndexRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas/': typeof MediadorTurmaIdApoioIndexFerramentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/infoteca': typeof InfotecaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/tv': typeof TvRoute
  '/dashboard/acessos': typeof DashboardAcessosRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/atividades': typeof DashboardAtividadesRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/fichas-acesso': typeof DashboardFichasAcessoRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/ferramentas/$ferramenta': typeof FerramentasFerramentaRoute
  '/aluno': typeof AlunoIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/mediador': typeof MediadorIndexRoute
  '/professor': typeof ProfessorIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/professor/$turmaId/chamada': typeof ProfessorTurmaIdChamadaRoute
  '/aluno/$turmaId': typeof AlunoTurmaIdIndexRoute
  '/dashboard/turmas': typeof DashboardTurmasIndexRoute
  '/professor/$turmaId': typeof ProfessorTurmaIdIndexRoute
  '/aluno/$turmaId/$alunoId/trilha': typeof AlunoTurmaIdAlunoIdTrilhaRoute
  '/mediador/$turmaId/$apoioIndex/relatorio': typeof MediadorTurmaIdApoioIndexRelatorioRoute
  '/professor/$turmaId/aluno/$alunoId': typeof ProfessorTurmaIdAlunoAlunoIdRoute
  '/professor/$turmaId/ferramentas/$ferramenta': typeof ProfessorTurmaIdFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId': typeof AlunoTurmaIdAlunoIdIndexRoute
  '/mediador/$turmaId/$apoioIndex': typeof MediadorTurmaIdApoioIndexIndexRoute
  '/professor/$turmaId/ferramentas': typeof ProfessorTurmaIdFerramentasIndexRoute
  '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta': typeof AlunoTurmaIdAlunoIdFerramentasFerramentaRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta': typeof MediadorTurmaIdApoioIndexFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId/ferramentas': typeof AlunoTurmaIdAlunoIdFerramentasIndexRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas': typeof MediadorTurmaIdApoioIndexFerramentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/infoteca': typeof InfotecaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/tv': typeof TvRoute
  '/dashboard/acessos': typeof DashboardAcessosRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/atividades': typeof DashboardAtividadesRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/faltas': typeof DashboardFaltasRoute
  '/dashboard/fichas-acesso': typeof DashboardFichasAcessoRoute
  '/dashboard/frequencia': typeof DashboardFrequenciaRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/programacao': typeof DashboardProgramacaoRoute
  '/ferramentas/$ferramenta': typeof FerramentasFerramentaRoute
  '/aluno/': typeof AlunoIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/mediador/': typeof MediadorIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/professor/$turmaId/chamada': typeof ProfessorTurmaIdChamadaRoute
  '/aluno/$turmaId/': typeof AlunoTurmaIdIndexRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
  '/professor/$turmaId/': typeof ProfessorTurmaIdIndexRoute
  '/aluno/$turmaId/$alunoId/trilha': typeof AlunoTurmaIdAlunoIdTrilhaRoute
  '/mediador/$turmaId/$apoioIndex/relatorio': typeof MediadorTurmaIdApoioIndexRelatorioRoute
  '/professor/$turmaId/aluno/$alunoId': typeof ProfessorTurmaIdAlunoAlunoIdRoute
  '/professor/$turmaId/ferramentas/$ferramenta': typeof ProfessorTurmaIdFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId/': typeof AlunoTurmaIdAlunoIdIndexRoute
  '/mediador/$turmaId/$apoioIndex/': typeof MediadorTurmaIdApoioIndexIndexRoute
  '/professor/$turmaId/ferramentas/': typeof ProfessorTurmaIdFerramentasIndexRoute
  '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta': typeof AlunoTurmaIdAlunoIdFerramentasFerramentaRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta': typeof MediadorTurmaIdApoioIndexFerramentasFerramentaRoute
  '/aluno/$turmaId/$alunoId/ferramentas/': typeof AlunoTurmaIdAlunoIdFerramentasIndexRoute
  '/mediador/$turmaId/$apoioIndex/ferramentas/': typeof MediadorTurmaIdApoioIndexFerramentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/avaliacao'
    | '/coordenacao'
    | '/infoteca'
    | '/login'
    | '/sobre'
    | '/tv'
    | '/dashboard/acessos'
    | '/dashboard/alunos'
    | '/dashboard/atividades'
    | '/dashboard/aulas'
    | '/dashboard/avaliacao'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/fichas-acesso'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/ferramentas/$ferramenta'
    | '/aluno/'
    | '/dashboard/'
    | '/ferramentas/'
    | '/mediador/'
    | '/professor/'
    | '/dashboard/turmas/$turmaId'
    | '/professor/$turmaId/chamada'
    | '/aluno/$turmaId/'
    | '/dashboard/turmas/'
    | '/professor/$turmaId/'
    | '/aluno/$turmaId/$alunoId/trilha'
    | '/mediador/$turmaId/$apoioIndex/relatorio'
    | '/professor/$turmaId/aluno/$alunoId'
    | '/professor/$turmaId/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId/'
    | '/mediador/$turmaId/$apoioIndex/'
    | '/professor/$turmaId/ferramentas/'
    | '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
    | '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId/ferramentas/'
    | '/mediador/$turmaId/$apoioIndex/ferramentas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/avaliacao'
    | '/coordenacao'
    | '/infoteca'
    | '/login'
    | '/sobre'
    | '/tv'
    | '/dashboard/acessos'
    | '/dashboard/alunos'
    | '/dashboard/atividades'
    | '/dashboard/aulas'
    | '/dashboard/avaliacao'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/fichas-acesso'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/ferramentas/$ferramenta'
    | '/aluno'
    | '/dashboard'
    | '/ferramentas'
    | '/mediador'
    | '/professor'
    | '/dashboard/turmas/$turmaId'
    | '/professor/$turmaId/chamada'
    | '/aluno/$turmaId'
    | '/dashboard/turmas'
    | '/professor/$turmaId'
    | '/aluno/$turmaId/$alunoId/trilha'
    | '/mediador/$turmaId/$apoioIndex/relatorio'
    | '/professor/$turmaId/aluno/$alunoId'
    | '/professor/$turmaId/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId'
    | '/mediador/$turmaId/$apoioIndex'
    | '/professor/$turmaId/ferramentas'
    | '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
    | '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId/ferramentas'
    | '/mediador/$turmaId/$apoioIndex/ferramentas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/avaliacao'
    | '/coordenacao'
    | '/infoteca'
    | '/login'
    | '/sobre'
    | '/tv'
    | '/dashboard/acessos'
    | '/dashboard/alunos'
    | '/dashboard/atividades'
    | '/dashboard/aulas'
    | '/dashboard/avaliacao'
    | '/dashboard/configuracoes'
    | '/dashboard/faltas'
    | '/dashboard/fichas-acesso'
    | '/dashboard/frequencia'
    | '/dashboard/grupos'
    | '/dashboard/programacao'
    | '/ferramentas/$ferramenta'
    | '/aluno/'
    | '/dashboard/'
    | '/ferramentas/'
    | '/mediador/'
    | '/professor/'
    | '/dashboard/turmas/$turmaId'
    | '/professor/$turmaId/chamada'
    | '/aluno/$turmaId/'
    | '/dashboard/turmas/'
    | '/professor/$turmaId/'
    | '/aluno/$turmaId/$alunoId/trilha'
    | '/mediador/$turmaId/$apoioIndex/relatorio'
    | '/professor/$turmaId/aluno/$alunoId'
    | '/professor/$turmaId/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId/'
    | '/mediador/$turmaId/$apoioIndex/'
    | '/professor/$turmaId/ferramentas/'
    | '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
    | '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
    | '/aluno/$turmaId/$alunoId/ferramentas/'
    | '/mediador/$turmaId/$apoioIndex/ferramentas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  CoordenacaoRoute: typeof CoordenacaoRoute
  InfotecaRoute: typeof InfotecaRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
  TvRoute: typeof TvRoute
  DashboardAcessosRoute: typeof DashboardAcessosRoute
  DashboardAlunosRoute: typeof DashboardAlunosRoute
  DashboardAtividadesRoute: typeof DashboardAtividadesRoute
  DashboardAulasRoute: typeof DashboardAulasRoute
  DashboardAvaliacaoRoute: typeof DashboardAvaliacaoRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardFaltasRoute: typeof DashboardFaltasRoute
  DashboardFichasAcessoRoute: typeof DashboardFichasAcessoRoute
  DashboardFrequenciaRoute: typeof DashboardFrequenciaRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardProgramacaoRoute: typeof DashboardProgramacaoRoute
  FerramentasFerramentaRoute: typeof FerramentasFerramentaRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
  MediadorIndexRoute: typeof MediadorIndexRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
  DashboardTurmasTurmaIdRoute: typeof DashboardTurmasTurmaIdRoute
  ProfessorTurmaIdChamadaRoute: typeof ProfessorTurmaIdChamadaRoute
  AlunoTurmaIdIndexRoute: typeof AlunoTurmaIdIndexRoute
  DashboardTurmasIndexRoute: typeof DashboardTurmasIndexRoute
  ProfessorTurmaIdIndexRoute: typeof ProfessorTurmaIdIndexRoute
  AlunoTurmaIdAlunoIdTrilhaRoute: typeof AlunoTurmaIdAlunoIdTrilhaRoute
  MediadorTurmaIdApoioIndexRelatorioRoute: typeof MediadorTurmaIdApoioIndexRelatorioRoute
  ProfessorTurmaIdAlunoAlunoIdRoute: typeof ProfessorTurmaIdAlunoAlunoIdRoute
  ProfessorTurmaIdFerramentasFerramentaRoute: typeof ProfessorTurmaIdFerramentasFerramentaRoute
  AlunoTurmaIdAlunoIdIndexRoute: typeof AlunoTurmaIdAlunoIdIndexRoute
  MediadorTurmaIdApoioIndexIndexRoute: typeof MediadorTurmaIdApoioIndexIndexRoute
  ProfessorTurmaIdFerramentasIndexRoute: typeof ProfessorTurmaIdFerramentasIndexRoute
  AlunoTurmaIdAlunoIdFerramentasFerramentaRoute: typeof AlunoTurmaIdAlunoIdFerramentasFerramentaRoute
  MediadorTurmaIdApoioIndexFerramentasFerramentaRoute: typeof MediadorTurmaIdApoioIndexFerramentasFerramentaRoute
  AlunoTurmaIdAlunoIdFerramentasIndexRoute: typeof AlunoTurmaIdAlunoIdFerramentasIndexRoute
  MediadorTurmaIdApoioIndexFerramentasIndexRoute: typeof MediadorTurmaIdApoioIndexFerramentasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao': {
      id: '/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof CoordenacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infoteca': {
      id: '/infoteca'
      path: '/infoteca'
      fullPath: '/infoteca'
      preLoaderRoute: typeof InfotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/aluno'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/acessos': {
      id: '/dashboard/acessos'
      path: '/dashboard/acessos'
      fullPath: '/dashboard/acessos'
      preLoaderRoute: typeof DashboardAcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/alunos': {
      id: '/dashboard/alunos'
      path: '/dashboard/alunos'
      fullPath: '/dashboard/alunos'
      preLoaderRoute: typeof DashboardAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/atividades': {
      id: '/dashboard/atividades'
      path: '/dashboard/atividades'
      fullPath: '/dashboard/atividades'
      preLoaderRoute: typeof DashboardAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/aulas': {
      id: '/dashboard/aulas'
      path: '/dashboard/aulas'
      fullPath: '/dashboard/aulas'
      preLoaderRoute: typeof DashboardAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/avaliacao': {
      id: '/dashboard/avaliacao'
      path: '/dashboard/avaliacao'
      fullPath: '/dashboard/avaliacao'
      preLoaderRoute: typeof DashboardAvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/dashboard/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/faltas': {
      id: '/dashboard/faltas'
      path: '/dashboard/faltas'
      fullPath: '/dashboard/faltas'
      preLoaderRoute: typeof DashboardFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/fichas-acesso': {
      id: '/dashboard/fichas-acesso'
      path: '/dashboard/fichas-acesso'
      fullPath: '/dashboard/fichas-acesso'
      preLoaderRoute: typeof DashboardFichasAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/frequencia': {
      id: '/dashboard/frequencia'
      path: '/dashboard/frequencia'
      fullPath: '/dashboard/frequencia'
      preLoaderRoute: typeof DashboardFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/dashboard/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/programacao': {
      id: '/dashboard/programacao'
      path: '/dashboard/programacao'
      fullPath: '/dashboard/programacao'
      preLoaderRoute: typeof DashboardProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/ferramentas'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/$ferramenta': {
      id: '/ferramentas/$ferramenta'
      path: '/ferramentas/$ferramenta'
      fullPath: '/ferramentas/$ferramenta'
      preLoaderRoute: typeof FerramentasFerramentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/': {
      id: '/mediador/'
      path: '/mediador'
      fullPath: '/mediador/'
      preLoaderRoute: typeof MediadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/professor'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$turmaId/': {
      id: '/aluno/$turmaId/'
      path: '/aluno/$turmaId'
      fullPath: '/aluno/$turmaId/'
      preLoaderRoute: typeof AlunoTurmaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/': {
      id: '/dashboard/turmas/'
      path: '/dashboard/turmas'
      fullPath: '/dashboard/turmas/'
      preLoaderRoute: typeof DashboardTurmasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/$turmaId': {
      id: '/dashboard/turmas/$turmaId'
      path: '/dashboard/turmas/$turmaId'
      fullPath: '/dashboard/turmas/$turmaId'
      preLoaderRoute: typeof DashboardTurmasTurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/$turmaId/': {
      id: '/professor/$turmaId/'
      path: '/professor/$turmaId'
      fullPath: '/professor/$turmaId/'
      preLoaderRoute: typeof ProfessorTurmaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/$turmaId/chamada': {
      id: '/professor/$turmaId/chamada'
      path: '/professor/$turmaId/chamada'
      fullPath: '/professor/$turmaId/chamada'
      preLoaderRoute: typeof ProfessorTurmaIdChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$turmaId/$alunoId/': {
      id: '/aluno/$turmaId/$alunoId/'
      path: '/aluno/$turmaId/$alunoId'
      fullPath: '/aluno/$turmaId/$alunoId/'
      preLoaderRoute: typeof AlunoTurmaIdAlunoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$turmaId/$alunoId/trilha': {
      id: '/aluno/$turmaId/$alunoId/trilha'
      path: '/aluno/$turmaId/$alunoId/trilha'
      fullPath: '/aluno/$turmaId/$alunoId/trilha'
      preLoaderRoute: typeof AlunoTurmaIdAlunoIdTrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/$turmaId/$apoioIndex/': {
      id: '/mediador/$turmaId/$apoioIndex/'
      path: '/mediador/$turmaId/$apoioIndex'
      fullPath: '/mediador/$turmaId/$apoioIndex/'
      preLoaderRoute: typeof MediadorTurmaIdApoioIndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/$turmaId/$apoioIndex/relatorio': {
      id: '/mediador/$turmaId/$apoioIndex/relatorio'
      path: '/mediador/$turmaId/$apoioIndex/relatorio'
      fullPath: '/mediador/$turmaId/$apoioIndex/relatorio'
      preLoaderRoute: typeof MediadorTurmaIdApoioIndexRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/$turmaId/aluno/$alunoId': {
      id: '/professor/$turmaId/aluno/$alunoId'
      path: '/professor/$turmaId/aluno/$alunoId'
      fullPath: '/professor/$turmaId/aluno/$alunoId'
      preLoaderRoute: typeof ProfessorTurmaIdAlunoAlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/$turmaId/ferramentas/': {
      id: '/professor/$turmaId/ferramentas/'
      path: '/professor/$turmaId/ferramentas'
      fullPath: '/professor/$turmaId/ferramentas/'
      preLoaderRoute: typeof ProfessorTurmaIdFerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/$turmaId/ferramentas/$ferramenta': {
      id: '/professor/$turmaId/ferramentas/$ferramenta'
      path: '/professor/$turmaId/ferramentas/$ferramenta'
      fullPath: '/professor/$turmaId/ferramentas/$ferramenta'
      preLoaderRoute: typeof ProfessorTurmaIdFerramentasFerramentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$turmaId/$alunoId/ferramentas/': {
      id: '/aluno/$turmaId/$alunoId/ferramentas/'
      path: '/aluno/$turmaId/$alunoId/ferramentas'
      fullPath: '/aluno/$turmaId/$alunoId/ferramentas/'
      preLoaderRoute: typeof AlunoTurmaIdAlunoIdFerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta': {
      id: '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
      path: '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
      fullPath: '/aluno/$turmaId/$alunoId/ferramentas/$ferramenta'
      preLoaderRoute: typeof AlunoTurmaIdAlunoIdFerramentasFerramentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/$turmaId/$apoioIndex/ferramentas/': {
      id: '/mediador/$turmaId/$apoioIndex/ferramentas/'
      path: '/mediador/$turmaId/$apoioIndex/ferramentas'
      fullPath: '/mediador/$turmaId/$apoioIndex/ferramentas/'
      preLoaderRoute: typeof MediadorTurmaIdApoioIndexFerramentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta': {
      id: '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
      path: '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
      fullPath: '/mediador/$turmaId/$apoioIndex/ferramentas/$ferramenta'
      preLoaderRoute: typeof MediadorTurmaIdApoioIndexFerramentasFerramentaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  CoordenacaoRoute: CoordenacaoRoute,
  InfotecaRoute: InfotecaRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
  TvRoute: TvRoute,
  DashboardAcessosRoute: DashboardAcessosRoute,
  DashboardAlunosRoute: DashboardAlunosRoute,
  DashboardAtividadesRoute: DashboardAtividadesRoute,
  DashboardAulasRoute: DashboardAulasRoute,
  DashboardAvaliacaoRoute: DashboardAvaliacaoRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardFaltasRoute: DashboardFaltasRoute,
  DashboardFichasAcessoRoute: DashboardFichasAcessoRoute,
  DashboardFrequenciaRoute: DashboardFrequenciaRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardProgramacaoRoute: DashboardProgramacaoRoute,
  FerramentasFerramentaRoute: FerramentasFerramentaRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
  MediadorIndexRoute: MediadorIndexRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
  DashboardTurmasTurmaIdRoute: DashboardTurmasTurmaIdRoute,
  ProfessorTurmaIdChamadaRoute: ProfessorTurmaIdChamadaRoute,
  AlunoTurmaIdIndexRoute: AlunoTurmaIdIndexRoute,
  DashboardTurmasIndexRoute: DashboardTurmasIndexRoute,
  ProfessorTurmaIdIndexRoute: ProfessorTurmaIdIndexRoute,
  AlunoTurmaIdAlunoIdTrilhaRoute: AlunoTurmaIdAlunoIdTrilhaRoute,
  MediadorTurmaIdApoioIndexRelatorioRoute:
    MediadorTurmaIdApoioIndexRelatorioRoute,
  ProfessorTurmaIdAlunoAlunoIdRoute: ProfessorTurmaIdAlunoAlunoIdRoute,
  ProfessorTurmaIdFerramentasFerramentaRoute:
    ProfessorTurmaIdFerramentasFerramentaRoute,
  AlunoTurmaIdAlunoIdIndexRoute: AlunoTurmaIdAlunoIdIndexRoute,
  MediadorTurmaIdApoioIndexIndexRoute: MediadorTurmaIdApoioIndexIndexRoute,
  ProfessorTurmaIdFerramentasIndexRoute: ProfessorTurmaIdFerramentasIndexRoute,
  AlunoTurmaIdAlunoIdFerramentasFerramentaRoute:
    AlunoTurmaIdAlunoIdFerramentasFerramentaRoute,
  MediadorTurmaIdApoioIndexFerramentasFerramentaRoute:
    MediadorTurmaIdApoioIndexFerramentasFerramentaRoute,
  AlunoTurmaIdAlunoIdFerramentasIndexRoute:
    AlunoTurmaIdAlunoIdFerramentasIndexRoute,
  MediadorTurmaIdApoioIndexFerramentasIndexRoute:
    MediadorTurmaIdApoioIndexFerramentasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
