/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAlunosRouteImport } from './routes/dashboard/alunos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard/configuracoes'
import { Route as DashboardGruposRouteImport } from './routes/dashboard/grupos'
import { Route as DashboardTurmasIndexRouteImport } from './routes/dashboard/turmas/index'
import { Route as DashboardTurmasTurmaIdRouteImport } from './routes/dashboard/turmas/$turmaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunosRoute = DashboardAlunosRouteImport.update({
  id: '/dashboard/alunos',
  path: '/dashboard/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/dashboard/configuracoes',
  path: '/dashboard/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/dashboard/grupos',
  path: '/dashboard/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasIndexRoute = DashboardTurmasIndexRouteImport.update({
  id: '/dashboard/turmas/',
  path: '/dashboard/turmas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTurmasTurmaIdRoute = DashboardTurmasTurmaIdRouteImport.update({
  id: '/dashboard/turmas/$turmaId',
  path: '/dashboard/turmas/$turmaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas': typeof DashboardTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/login': typeof LoginRoute
  '/dashboard/alunos': typeof DashboardAlunosRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/turmas/$turmaId': typeof DashboardTurmasTurmaIdRoute
  '/dashboard/turmas/': typeof DashboardTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/login'
    | '/dashboard/alunos'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/login'
    | '/dashboard/alunos'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/login'
    | '/dashboard/alunos'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/'
    | '/dashboard/turmas/$turmaId'
    | '/dashboard/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  LoginRoute: typeof LoginRoute
  DashboardAlunosRoute: typeof DashboardAlunosRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTurmasTurmaIdRoute: typeof DashboardTurmasTurmaIdRoute
  DashboardTurmasIndexRoute: typeof DashboardTurmasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/alunos': {
      id: '/dashboard/alunos'
      path: '/dashboard/alunos'
      fullPath: '/dashboard/alunos'
      preLoaderRoute: typeof DashboardAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/dashboard/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/dashboard/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/': {
      id: '/dashboard/turmas/'
      path: '/dashboard/turmas'
      fullPath: '/dashboard/turmas/'
      preLoaderRoute: typeof DashboardTurmasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/turmas/$turmaId': {
      id: '/dashboard/turmas/$turmaId'
      path: '/dashboard/turmas/$turmaId'
      fullPath: '/dashboard/turmas/$turmaId'
      preLoaderRoute: typeof DashboardTurmasTurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  LoginRoute: LoginRoute,
  DashboardAlunosRoute: DashboardAlunosRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTurmasTurmaIdRoute: DashboardTurmasTurmaIdRoute,
  DashboardTurmasIndexRoute: DashboardTurmasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
